### PR TITLE
Fix catchable-username.json

### PR DESCRIPTION
**Pull request by ffigueroa**
Short Description: 

Fixes:
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2687
- 
-

### CODE REVIEW

**Comment by dezayner** [comment]
Duplicate with https://github.com/PokemonGoF/PokemonGo-Bot/pull/2719

**Comment by MikeDX** [comment]
I think #2719 is a dupe of this, not the other way around.

**Comment by dezayner** [comment]
But #2719 already merged to dev

**Comment by MikeDX** [comment]
Which is weird, as this is a cleaner commit, and was posted earlier.

**Comment by Nihisil** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/2719

**Pull request closed without merging**
