### PR TITLE
Various Walking Fixes

### PR DESCRIPTION
**Pull request by th3w4y**
Fixes:

- Add API limit reached pickle for directions			7f7cf28
- Handle special speed values		1d1dc9f 982570e
- add sleep(1) when teleporting because self.dist < self.speed 	579e85a
-  Update documentation regarding the speed unit of measurement		3259fb6

### CODE REVIEW

**Comment by mjmadsen** [comment]
:+1:

**Comment by Anakin5** [comment]
Me again.
I have something strange, is that upon restart, the patterns are more or less nice.

image

**Comment by Anakin5** [comment]
Not sure it is related entirely to restart though. Could be that polyline return small steps which makes the noise much more noticeable.

**Comment by mjmadsen** [comment]
Without noise enabled, I imagine? Was there a pull between (I assume you're normally on latest dev)?

Which part is after the restart (top and bottom)? The bottom is what it should look like (imo).

**Comment by mjmadsen** [comment]
What are your noise values?

**Comment by Anakin5** [comment]
I guess you are talking about those:
```
	"gps_default_altitude": 8.0,
	"replicate_gps_xy_noise": false,
	"replicate_gps_z_noise": false,
	"gps_xy_noise_range": 0.00025,
	"gps_z_noise_range": 12.5,
```

**Comment by mjmadsen** [comment]
Hm, not even enabled... The walking variance built in shouldn't very that much - plus some of those jumps look like it's not in the direction of your destination.. what the heck..

**Comment by Anakin5** [comment]
Actually, I think it happen for the steps that are small, but not small enough to be direct teleport. As I said, looks like the "noise" for our random is predominant for small steps,

**Comment by mjmadsen** [comment]
Should we have a minimum step size of some sort, do you think?

**Comment by Anakin5** [comment]
oh, ok, you guys removed the random stuff. So yes it should not happen. Something funny also is that the bot might pass by the same location again and have a nice path.
It behaves like we are picking a random value at some point of initilization of the Polyline, and if bad luck in the rand, we get crappy patterns.

**Comment by Anakin5** [comment]
I will do more tests, it is not very conclusive for now, it is too random.

**Comment by mjmadsen** [comment]
BTW @Anakin5 thanks for helping us fine tune this. You're a great help :+1:

**Comment by mjmadsen** [comment]
Default min/max walk values?

**Comment by th3w4y** [comment]
@Anakin5 i think there is something real strange with that..

but there is not delta in the small teleporting steps that i can confirm...

**Comment by th3w4y** [comment]
@Anakin5 your picture actually worries me a bit... is the upper with this commit and the bottom with before?

**Comment by th3w4y** [comment]
do you maybe have conflicting follow tasks?

**Comment by th3w4y** [comment]
@you are using your CampFort task?

**Comment by th3w4y** [comment]
@what other follow task you have beside CampFort?

**Comment by mjmadsen** [comment]
Mine looks distinctively different

https://s18.postimg.org/tcikj8a95/test5.jpg

**Comment by th3w4y** [comment]
@mjmadsen we have no jitter for small steps... the offset_angle applies only when distance > speed

**Comment by mjmadsen** [comment]
The only movement task I have enabled in this is movetofort

**Comment by th3w4y** [comment]
@mjmadsen can you do a small test.. 

in polyline_walker.py L21 change

```
        super(PolylineWalker, self).__init__(self.bot, self.pol_lat, self.pol_lon,
                                             self.pol_alt, fixed_speed=self.speed)
```

to

```
        super(PolylineWalker, self).__init__(self.bot, self.pol_lat, self.pol_lon,
                                             self.pol_alt, fixed_speed=self.speed*.90)
```

**Comment by th3w4y** [comment]
@mjmadsen i am curious what results you'll get... that is a ugly workaround to make sure we got in distance > speed

**Comment by mjmadsen** [comment]
[2016-09-04 09:24:32] [MoveToFort] [INFO] Moving towards pokestop Historic Travelers Insurance Sign - 106.67m
I'll try the change in a moment, this is from a reboot:

[2016-09-04 09:24:37] [MoveToFort] [INFO] Moving towards pokestop Historic Travelers Insurance Sign - 95.49m
[2016-09-04 09:24:42] [MoveToFort] [INFO] Moving towards pokestop Historic Travelers Insurance Sign - 78.66m
[2016-09-04 09:24:48] [MoveToFort] [INFO] Moving towards pokestop Historic Travelers Insurance Sign - 66.46m
[2016-09-04 09:24:53] [MoveToFort] [INFO] Moving towards pokestop Historic Travelers Insurance Sign - 57.43m
[2016-09-04 09:24:59] [MoveToFort] [INFO] Moving towards pokestop Historic Travelers Insurance Sign - 47.74m

test6

**Comment by th3w4y** [comment]
no need to try that anymore... even with 0.9*speed we still hit the one step part...

**Comment by mjmadsen** [comment]
test7

**Comment by Anakin5** [comment]
I was testing with only MoveToFort and my walking is the standard 2.16-4.16. The issue is hard to reproduce, maybe there is something with the position of the forts as well.
I am not going to spend time on this for now, it is not major issue.

**Comment by th3w4y** [comment]
I identified one more issue and have a PR now https://github.com/PokemonGoF/PokemonGo-Bot/pull/5181

**Pull request merged**
