### PR TITLE
Making the README.md better

### PR DESCRIPTION
**Pull request by luizperes**
Short Description: This PR adds some cools stuff do the readme, check it out :)

### CODE REVIEW

**Comment by sniok** [comment]
Todo table is unnecessarily big and fancy

**Comment by luizperes** [comment]
@sniok I have updated it back to the previous way

**Comment by dominikue** [comment]
Probably center the donate button at the bottom. And maybe make the icon under the **PokemonGo-Bot** font - still love the poke icon :+1:

**Comment by solderzzc** [comment]
oops, conflicts need be resolved please

**Comment by luizperes** [comment]
@solderzzc the conflict has been solved :)

**Comment by solderzzc** [comment]
super :)

**Pull request merged**
