### PR TITLE
Allow to keep stronger pokemon

### PR DESCRIPTION
**Pull request by Nihisil**
## Motivation of this PR

I build for ability implement `Catch them all` mode :) It is useful for new players and for building whole collection.

After each capture bot will check do you have a new pokemon or not.

If you don't have it, it will keep it (no matter was it strong or weak pokemon).

If you already have it, it will keep a stronger version and will transfer the a weaker one.

It can compare pokemons based on CP or IV.

This PR based on #668 PR with some improvements.

If this PR will be merged, I will add description of attributes here https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

Examples of output:

> **I don't have a pokemon**
> [08:10:07] Captured Drowzee [CP 72] [6/11/7]
> [08:10:07] Not owning Drowzee [CP 72] [Potential 0.53]. Keeping it!
> 
> **I already have a weaker pokemon**
> [08:32:47] Captured Zubat! [CP 56] [6/6/8]
> [08:32:47] Owning weaker Zubat [CP 41] [Potential 0.51]. Replacing it with Zubat [CP 56] [Potential 0.44]!
> [08:32:48] Weaker Zubat [CP 41] [Potential 0.51] has been exchanged for candy!
> 
> **I have a better pokemon**
> [08:33:07] Captured Zubat! [CP 24] [0/8/14]
> [08:33:07] Owning better Zubat [CP 56] [Potential 0.44] already!
> [08:33:08] Zubat has been exchanged for candy!

> **Compare based on IV**
> [09:00:43] Captured Drowzee! [CP 96] [Potential 0.33] [2/7/6]
> [09:00:43] Owning better Drowzee [CP 75] [Potential 0.71] already!

### CODE REVIEW

**Comment by douglascamata** [comment]
@Nihisil what if I want to keep best IV instead of best CP? Please implemented this situation too.

**Comment by Nihisil** [comment]
@douglascamata I implemented it already. You need to set `keep_best_iv` instead of `keep_best_cp`

**Comment by douglascamata** [comment]
@Nihisil awesome! Please add one example of `keep_best_iv` to the configuration and updated the README accordingly.

**Comment by douglascamata** [comment]
@Nihisil BTW, one big thing I forgot: we're moving all release logic to an specific release worker. See #1286. We will merge it first and then can you fix conflicts accordingly?

**Comment by Nihisil** [comment]
@douglascamata I have added `keep_best_iv` example into config. 

I can't change Readme.md, because it is in the wiki now https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files
So, I will change a wiki once this PR will be merged.

Got it about release worker. Yeah, I will merge it and will resolve conflicts

**Comment by douglascamata** [comment]
@Nihisil #1286 was merged.

**Comment by Nihisil** [comment]
@douglascamata I have merged dev and have resolved all conflicts.

Tested a bot after it a little bit, and it seems like it is working.

**Comment by solderzzc** [comment]
@Nihisil The wiki can be edit publicly, right?

**Comment by Nihisil** [comment]
@solderzzc Yep, it seems like this. At least I have "Edit button.

**Comment by solderzzc** [comment]
👍

**Comment by Nihisil** [comment]
I have been tested it last one hour (from latest commit) and everything is working :)

**Comment by Nihisil** [comment]
Thanks. I have updated wiki https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#release-configuration

**Comment by TheSavior** [comment]
@douglascamata Remember to refactor this to remove the evolve worker from the pokemon catch worker.

**Pull request merged**
