### PR TITLE
Add optional simple lure attraction feature

### PR DESCRIPTION
**Pull request by z4ppy**

### CODE REVIEW

**Comment by douglascamata** [comment]
👍 

@TheSavior review, please.

**Comment by MFizz** [comment]
Can someone explain what lure attraction is, in this context - what the feature enables?

**Comment by z4ppy** [comment]
What is "help to test" ? i can do something for help the integration ?

**Comment by z4ppy** [comment]
@MFizz Patch for move_to_fort for enable "lure_attraction". You already include some of my code in your PR about cluster (lambda lure selection) but this patch dont do the same of your : bot will be attracted by lure and not go directly on lure.

Sorry for

**Comment by douglascamata** [comment]
@z4ppy it means that we want more ppl to test for some time before merging.

**Comment by 1cu** [comment]
I love it :+1:

**Comment by douglascamata** [comment]
@MFizz it's just a normal MoveToFort but giving priority to fort with lures.

**Comment by z4ppy** [comment]
@MFizz maybe we can merge both PR, using yours clusters points (very nice work) injected in move_to_fort with a new abstract attraction feature (cluster/lure/other). What do you mean about that ?

**Comment by douglascamata** [comment]
@z4ppy @MFizz's task is isolated and can be combined with yours. It's better to keep each task isolated like we have now.

**Comment by z4ppy** [comment]
I agree : i mean about many task for waypoint/attraction/map generation and some navigators for consume it (spiral, move_to_fort, ...). Too many navigator can't works (i mean), we will see some priority problem with the current system (who can preempt first ?)

**Comment by 1cu** [comment]
Works pretty great - moviing from lure to lure and catching a lot of pokemon on the way :+1:

**Comment by selmuth** [comment]
working great :+1:

**Comment by mchouvel** [comment]
I have an error, or maybe I do it wrong...

```
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/Users/user/PokemonGo-Bot/pokemongo_bot/__init__.py", line 14, in <module>
    from cell_workers import PokemonCatchWorker, SeenFortWorker, MoveToFortWorker, InitialTransferWorker, EvolveAllWorker
  File "/Users/user/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 5, in <module>
    from move_to_fort_worker import MoveToFortWorker
  File "/Users/user/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 2, in <module>
    from pokemongo_bot.constants import Constants
ImportError: No module named constants
```

**Comment by MZorzy** [comment]
please add slow down/camping near a fort with lures, to incerase possibility to catch pokemon

**Pull request merged**
