### PR TITLE
Better text for Pokemon appearing

### PR DESCRIPTION
**Pull request by Reaver01**

### CODE REVIEW

**Comment by Reaver01** [comment]
```
looping: step 1 of 100
steplimit: 100 x: 0 y: 0 pos: 1 dx: 0 dy -1
(Lat, Long, 0)
got the maps
map_cells are 21
Something rustles nearby!
A Wild Eevee appeared! [CP75]
Captured Eevee! [CP75] - exchanging for candy
Exchanged successfuly!
looping: step 2 of 100
steplimit: 100 x: 1 y: 0 pos: 1 dx: 1 dy 0
(Lat, Long, 0)
got the maps
map_cells are 21
Something rustles nearby!
A Wild Clefairy appeared! [CP48]
Captured Clefairy! [CP48] - exchanging for candy
Exchanged successfuly!
```

That looks so much nicer than it did this morning!

**Comment by Reaver01** [comment]
I have a discord if you want to have chat for development of this.

**Comment by eggins** [comment]
@Reaver01 send it through - I have an idea on something I want to do.

**Comment by Reaver01** [comment]
https://discord.gg/MKxZG

**Pull request merged**
