### PR TITLE
Added Telegram support

### LINKED ISSUE #4353: Telegram bot integration
### Short Description
Telegram bot integration for remote progress updates

### Possible solution
Integrate a telegram bot feeding mechanism so that users can see their bots progress while away

### How it would help others
Users will be able to remotely check progress and see if bot is active and request basic stat updates: active time, XP gained, stardust gained, pokemons caught, XP per hour, stardust per hour, pokemons per hour, item list, pokemon list ordered by highest cp, iv, time, etc.

*by the way, many thanks for the effort you are putting in. Great experience so far.

### PR DESCRIPTION
**Pull request by askovpen**
## Short Description:

Telegram Support

## Fixes/Resolves/Closes (please use correct syntax):

Closes #4353

### CODE REVIEW

**Comment by solderzzc** [comment]
This would be funny.

**Comment by solderzzc** [comment]
@askovpen Only one bot can login one api key?

**Comment by askovpen** [comment]
@solderzzc yes. you can create unlimited bots https://core.telegram.org/bots#3-how-do-i-create-a-bot

**Comment by solderzzc** [comment]
Is that possible to split the api into auth.conf ? We now have -af auth.conf to easy the configuration copy job after changes. But I tried to setup another task list in the auth.conf, it's not working.

**Comment by askovpen** [comment]
yes

**Comment by alexyaoyang** [comment]
This is awesome! Thank you @askovpen !

**Pull request merged**
