### PR TITLE
Hotfix for EvolvePokemon

### PR DESCRIPTION
**Pull request by alexyaoyang**

### CODE REVIEW

**Comment by solderzzc** [comment]
CI build failed here.

**Comment by alexyaoyang** [comment]
@simbazhang2016 That's weird, ran tests on my side, all passed. Let me look into it.

**Comment by solderzzc** [comment]
maybe caused by the old commit
> Merge remote-tracking branch 'origin/dev' into dev			35b446e

**Comment by alexyaoyang** [comment]
That commit didn't change any files. Let me revert and re-submit.

**Comment by alexyaoyang** [comment]
@solderzzc All good now. Just now, somehow `test_api_call_throttle_should_fail` in api_wrapper_test.py didn't throw a `TimeoutError`.

**Pull request merged**
