### PR TITLE
Multiple Config File Support

### PR DESCRIPTION
**Pull request by ColeGreenlee**

### CODE REVIEW

**Comment by solderzzc** [comment]
SIMBA: This is documented well, I want to merge. 
Github: This branch has conflicts that must be resolved

**Comment by ColeGreenlee** [comment]
What do I need to do to resolve the conflicts? A bit new to this.

**Comment by solderzzc** [comment]
click 'Use the command line'  below this line, many thanks
      |
      |

**Comment by ColeGreenlee** [comment]
Sorry, I'm not seeing anywhere to click that? Can you specify a bit more?

**Comment by solderzzc** [comment]
hmm, you can search 'Use this command line' in this page :)

**Comment by ColeGreenlee** [comment]
Yeah, still not seeing it. Are you able to see it since you've got more permissions than I?

**Comment by solderzzc** [comment]
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b ColeGreenlee-dev dev
git pull https://github.com/ColeGreenlee/PokemonGo-Bot.git dev
Step 2: Merge the changes and update on GitHub.

git checkout dev
git merge --no-ff ColeGreenlee-dev
git push origin dev

**Comment by dmateusp** [comment]
@ColeGreenlee you can also do a quick
git fetch [FROM THE DEV BRANCH]
git pull [FROM THE DEV BRANCH]

then you solve merge issues
commit changes to your branch
push to your branch

This will update automatically the Pull request and should solve merging issues

**Comment by ColeGreenlee** [comment]
Okay, I done goofed and killed my local stuff. I'm gonna try this again in a second. Thanks for the help

**Pull request closed without merging**
