### PR TITLE
Transfer Pomemon if bag is full instead of flooding "Something rustles nearby!"

### PR DESCRIPTION
**Pull request by haykuro**
Short Description: Adds a "[x] Pokemon Bag is full!" message if you encounter a pokemon but can't catch it because your pokemon bag is full. (a.k.a. status 7 is returned when encounter is sent)

Fixes:
```
[#] Walking from (34.0092419, -118.4976037) to (34.013523, -118.492144) for approx. 278.0 seconds
[#] Something rustles nearby!
[#] Something rustles nearby!
[#] Something rustles nearby!
[#] Something rustles nearby!
[#] Something rustles nearby!
[#] Something rustles nearby!
...
```

Will instead do:
```
[#] Walking from (34.0092419, -118.4976037) to (34.013523, -118.492144) for approx. 278.0 seconds
[#] Something rustles nearby!
[x] Pokemon Bag is full!
[x] Initial Transfer.
[x] Preparing to transfer all Pokemon duplicates, keeping the highest CP of each one type.
[x] Releasing Pokemon #129 and CP 28
[x] Releasing Pokemon #129 and CP 23
[x] Releasing Pokemon #129 and CP 10
[x] Releasing Pokemon #140 and CP 48
[x] Releasing Pokemon #21 and CP 10
...
```

### CODE REVIEW

**Comment by douglascamata** [comment]
@haykuro please raise a RuntimeError with the message instead of just printing, because the bot will be stuck forever, so it's better to stop it.

**Comment by haykuro** [comment]
Fixed to run the transfer if the bag is full.

**Comment by haykuro** [comment]
Just realized this is similar to #277 ..

However, I'm utilizing the bot.initial_transfer function which already does smart transfers..

Perhaps we can use his switch to enable/disable this feature?

**Comment by solderzzc** [comment]
Looks good let me merge.

**Comment by TSM-EVO** [comment]
Very similar to this: 

If you run out of bag space for balls, you'll continue to "rustle" nearby pokemon, and then say that you have no balls, but you won't continue walking to the next pokestop to get it.

Maybe there needs to be some sort of flag to say 'I'm out of pokeballs' and then only run the 'search' function if you have useable balls available. Or perhaps keep a running count of pokeballs , and include a count check before trying to catch a pokemon.

**Pull request merged**
