### PR TITLE
Added Procfile to deploy to Heroku

### PR DESCRIPTION
**Pull request by AbelIngrand**
Adds a Procfile to easily deploy to Herpku

### CODE REVIEW

**Comment by douglascamata** [comment]
:+1:

**Comment by TheSavior** [comment]
👍

**Comment by TheSavior** [comment]
@AbelIngrand This needs to get pointed to dev instead of master. I think that is why it is not building and why we can't merge it.

**Comment by AbelIngrand** [comment]
Should I delete this PR and make a new one on dev branch or is there a way to change the branch the PR points to ?

**Comment by surfaace** [comment]
please change to dev branch with new PR

**Pull request closed without merging**
