### PR TITLE
Fix 5459

### LINKED ISSUE #5459: transfer_pokemon: Show candies with pokemon name without evolve
**Expected Behavior**
Keeping best 1 Pidgeotto, based on iv
\*Pidgeotto Released\* You now have 4 Pidgey candies

**Actual Behavior**
Keeping best 1 Pidgeotto, based on iv
\*Pidgeotto Released\* You now have 4 Pidgeotto candies

**Steps to Reproduce**
Update to the latest dev commit

### PR DESCRIPTION
**Pull request by DeXtroTip**
## Short Description:
Change `pokemon.name` to `candy.type`

## Fixes/Resolves/Closes (please use correct syntax):
- Fix #5459

### CODE REVIEW

**Comment by javajohnHub** [comment]
With the event text formatted like that.... does it still work in telegram?

**Comment by DeXtroTip** [comment]
@javajohnHub Oh okay, I didn't know that, I'll revert that then.

**Comment by javajohnHub** [comment]
Thanks.

**Comment by crvfts** [comment]
I was checking this out before merge and received this error:

`Traceback (most recent call last):
 File "pokecli.py", line 841, in <module>
   main()
 File "pokecli.py", line 200, in main
   bot.tick()
 File "C:\fresh\PokemonGo-Bot\pokemongo_bot\__init__.py", line 715, in tick
   if worker.work() == WorkerResult.RUNNING:
 File "C:\fresh\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 30, in work
   self._release_pokemon_worst_in_group(group, pokemon_name)
 File "C:\fresh\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 146, in _release_pokemon_worst_in_group
   self.release_pokemon(pokemon)
 File "C:\fresh\PokemonGo-Bot\pokemongo_bot\cell_workers\transfer_pokemon.py", line 254, in release_pokemon
   candy.type)
eyError: 'candy'`

I changed starting at 28L and working now:
`formatted="Exchanged {} (CP: {}, IV: {}, IVCP: {:.2f}) You now have"
                      " {} {} candies".format(pokemon.name,
                                              pokemon.cp,
                                              pokemon.iv,
                                              pokemon.ivcp,
                                              candy.quantity,
                                              candy.type)`

**Comment by DeXtroTip** [comment]
@crvfts Oh yeah, forgot to remove that when reverting. Thanks!

**Pull request merged**
