### PR TITLE
Fix using great/ultra balls when no more pokeballs

### PR DESCRIPTION
**Pull request by Shoh**
Short Description: 

Fixes:
- Fix using great/ultra balls when no more pokeballs
- Added Pokemon names to initial transfer output
- Added logic to prevent using last of Great and Ultra Balls on low cp pokemon

### CODE REVIEW

**Comment by dmateusp** [comment]
nice code and the logic is great for choosing pokeballs, I like the fact that it saves pokeballs for higher CP encounters when it is low.

Well done !

**Comment by solderzzc** [comment]
conflicts need to be fixed .....

**Comment by Shoh** [comment]
I've resolved the conflicts again

**Comment by skydrome** [comment]
@Shoh can you redo this and submit again, someone pushed their old and removed your code

**Pull request merged**
