### PR TITLE
Clarify Max_distance for Sniping

### PR DESCRIPTION
**Pull request by Jasperrr91**
Added a comment to the map config example to clarify the max_distance variable.

### CODE REVIEW

**Comment by Jasperrr91** [comment]
@mjmadsen here, hope this helps.

**Comment by mjmadsen** [comment]
Would you mind adding to configuration_files.md as well? Maybe note the unit (meters?).

**Comment by Jasperrr91** [comment]
Yes, done so. Unit is in KM, calculated with the Haversine formula.

**Comment by mjmadsen** [comment]
:-1:

**Comment by mjmadsen** [comment]
:+1: 

Thanks for the PR!

**Comment by mjmadsen** [comment]
Aw shoot. Does this have the recent changes to configuration_files.md (merged last half hour).

**Comment by Jasperrr91** [comment]
Now it should

**Comment by mjmadsen** [comment]
:+1:

**Pull request merged**
