### PR TITLE
Check awarded badges updates try 2

### PR DESCRIPTION
**Pull request by duttonw**
## Short Description:
update to store player_data and check_awarded_badges on success
emit events when awarded badge is returned and begin code changes for equip badge
add color to badge log

## Fixes
begin fixing #4522 

#4721 fixes

### CODE REVIEW

**Comment by solderzzc** [comment]
I'll test this PR tonight before merging, thanks.

**Comment by duttonw** [comment]
have tested with a brand new account, self.api.equip_badge(badge_type=badge) does not work but i've commented it out. will need to know if they send it with another request maybe. 

it displays

**Comment by mjmadsen** [comment]
@duttonw Just change init a bit ago

**Comment by duttonw** [comment]
Merged, no changes to my section.

**Comment by solderzzc** [comment]
Let's merge in :)

**Pull request merged**
