### PR TITLE
Dynamic subscriptions and password-based authentication with Telegram

### LINKED ISSUE #5192: Telegram master username improvements
I want to log this as an issue which needs further discussion/investigation. Basically, the issue is this:

The Telegram API does not support sending messages to a user by username. Instead, the user's id is needed.

We are currently trying to work around this by permitting users to enter their username in the config (instead of id), then performing various bits of voodoo to get the id from the username. This requires that the user send a message to the bot to initialize it, and only works if the user has specified a username in the Telegram app itself (not required by default and needs a settings change).

@DBa2016 has recently done some good work in making this id persistent in the database, so this initialization message only needs to be done once, and then it should be fine. 

That's a big improvement, but it would be even better if no initialization message was needed, and if the bot could just lookup the user's id from their username.

My feeling is that we should stop supporting username, and force use of ID until we can make it work as desired, but it seems to be a contentious issue, and fair enough since some users have no doubt gone through the setup process with "username" and have it working, so removing that functionality would seem a backward step.

Would appreciate others' thoughts and possible suggestions to make this actually work the way it should.

### PR DESCRIPTION
**Pull request by DBa2016**
## Short Description:
- implementing password-based authentication with TelegramTask (thereby circumventing the inability to get numeric ID from username)
- implementing dynamic subscriptions (see docs/telegramtask.md for details)

## Fixes/Resolves/Closes (please use correct syntax):
- Resolves #5192

### CODE REVIEW

**Comment by DBa2016** [comment]
Hmmm, what's up with Travis CI?...

**Comment by solderzzc** [comment]
hmm don't know.

**Comment by solderzzc** [comment]
👍

**Comment by DBa2016** [comment]
I had to rebase due to a commit made in the meantime...

**Comment by DBa2016** [comment]
Tested with: no master at all, numeric master, wrong symbolic master and correct master. Worked so far for me.

Please note: master is case-sensitive.

**Comment by solderzzc** [comment]
@DBa2016 It's time to merge. This is very good.

**Comment by solderzzc** [comment]
👍

**Comment by madzul** [comment]
Got this error (after latest pull):

Traceback (most recent call last):
  File "pokecli.py", line 803, in <module>
    main()
  File "pokecli.py", line 150, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 108, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 92, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/tree_config_builder.py", line 79, in build
    instance = worker(self.bot, task_config)
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/base_task.py", line 23, in __init__
    self.initialize()
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/cell_workers/telegram_task.py", line 21, in initialize
    self.bot.event_manager.add_handler(TelegramHandler(self.bot, self.config))
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/event_handlers/telegram_handler.py", line 292, in __init__
    initiator = TelegramDBInit(bot.database)
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/event_handlers/telegram_handler.py", line 264, in __init__
    self.initDBstructure()
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/event_handlers/telegram_handler.py", line 276, in initDBstructure
    self.initDBobject(objname, db_structure[objname])
  File "/Users/madzul/work/PoGoBot/PGB-Dev/pokemongo_bot/event_handlers/telegram_handler.py", line 282, in initDBobject
    if len(res) > 0 and res[0] != sql: # object exists and sql not matching
TypeError: object of type 'NoneType' has no len()

**Comment by DBa2016** [comment]
Fixed by #5252, thanks to @rbusquet

**Comment by rbusquet** [comment]
I was searching for an issue/pull dealing with this problem. I'm glad that helped ^^

**Comment by Gobberwart** [comment]
Looking good, but I've encountered a problem:

"master": gobberwart
no password set

Try sending message from Telegram. Response: please /login first

```
[2016-09-07 07:17:15] [MainThread] [PokemonGoBot] [INFO] Telegram message from gobberwart (244691262): /info
[2016-09-07 07:17:15] [MainThread] [PokemonGoBot] [ERROR] Telegram message received from unknown sender. Please either make sure your username or ID is in TelegramTask/master, or a password is set in TelegramTask section and /login is is
```

I removed the "@" and the bot logged:

```
[2016-09-07 07:21:33] [MainThread] [PokemonGoBot] [WARNING] Telegram message received from correct user, but master is not numeric, updating datastore.
```

but no response received.

Tried "/info" again and received response: "No password nor master configured..." message.

Something's not quite right.

**Comment by Gobberwart** [comment]
Authentication by password works perfectly.

**Comment by madzul** [comment]
Still got "No password nor master configured in TelegramTask section, bot will not accept any commands" 
Mine is latest commit (1b8cf13ffa183962df4c0ddfe92e6a9906da236b)

how's the right example TelegramTask config?

**Comment by rawgni** [comment]
@madzul https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#sample-configuration-5

**Comment by solderzzc** [comment]
Seems current telegram bot is hard to use.

**Comment by rawgni** [comment]
Maybe should stick with 1 way of configuring the telegram bot, ie. either using master or password.
The simplest is probably just specify a password, then msg the bot with the password and you are all set.

**Comment by Gobberwart** [comment]
I tend to agree @rawgni. Password works perfectly. Why keep master userid/password as well?

**Comment by davidspeijer** [comment]
{
         "type": "TelegramTask",
         "password": "Welkom01",
         "config": {
            "enabled": true, 
            "master": 1112223,
            "min_interval": 60,
            "alert_catch": {
               "all": {"operator": "or", "cp": 800, "iv": 0.8}
            }
         }         
      }
"No password nor master configured in TelegramTask section, bot will not accept any commands"

Just did a git pull

**Comment by DBa2016** [comment]
@Gobberwart , @rawgni : I am hesitant to remove a working method ("master" authentication), this would break working configs - therefore worked around to make both work (not sure why it did not work for your "master", @Gobberwart , can you check the case of your username? is it really all-small?).

But yes, I think password is easier and more flexible to use.

**Comment by Gobberwart** [comment]
@DBa2016 I hear you, but I think at some point we have to bite the bullet and say, "This method is shit and confuses people. Let's ditch it and go with what works."

**Comment by Gobberwart** [comment]
We can always add a log message "master in TelegramTask is deprecated, must use password instead"

**Pull request merged**
