### PR TITLE
Add RandomAlivePause task

### PR DESCRIPTION
**Pull request by cmezh**
This task keeps bot alive while it paused. Placed on the top of task list it drops execution of following tasks.
During pause it calls heartbeat and set_location for noising coordinates (of course, if noise is set in config).

Based on RandomPause task.
Inspired by (and also closes) #4583

### CODE REVIEW

**Comment by J-A-B-S** [comment]
So your saying that during paused time, It will move to a fort or something like that but without actually send the info to server and then when pause is over it will be at the location it was last at during the paused time?

**Comment by cmezh** [comment]
Nope. During the pause bot will not execute tasks set in task list after
RandomAlivePause. That's why RandomAlivePause must be placed on the top of
task list.

24 авг. 2016 г. 17:13 пользователь "J-A-B-S" <notifications@github.com>
написал:

**Comment by mhdasding** [comment]
Exactly what i want, thought of doing it myself but thanks to you i don't have to =P  👍

**Comment by solderzzc** [comment]
Why need alive pause ? In iPhone, if you switch app to background, still packet to server?

**Comment by cmezh** [comment]
@solderzzc Not all users switch app to background when they have a short break for coffee or talk with friends or whatever more. And, in my opinion, the more bot behaviour different, the more it's humanized.

**Comment by solderzzc** [comment]
ok, since it's optional, we can merge for testing, thanks a lot. @cmezh

**Comment by cmezh** [comment]
Thank you, @solderzzc :)

**Comment by imetanon** [comment]
if bot was in RandomAlivePause, how to cancel or stop ?

**Pull request merged**
