### PR TITLE
Adding initial REST Framework; Adding method to get user stats

### PR DESCRIPTION
**Pull request by bstascavage**
This is the same as #204 , which was reverted with no explanation.  Basically looking for feedback as to the revert and how this code can comply better with the main branch.  Thank you!

### CODE REVIEW

**Comment by jtdroste** [comment]
Sorry about that! I was going to re-open your PR, but something else got in the way

1. flask and flask-classy need to be added to requirements.txt
2. flask-classy import is deprecated

```
ExtDeprecationWarning: Importing flask.ext.classy is deprecated, use flask_classy instead.
  .format(x=modname), ExtDeprecationWarning
```

3. Server auto starts, binding on all ports (0.0.0.0) instead of localhost.  Could be a security risk

4. Flask debug is printing out to stdout (should not, unless `config.debug` is enabled)

5.  We currently have a basic web server as well.  Please implement the functionality into yours (i.e. google maps page on index, showing current bot coords).  The server is located in /web

**Comment by douglascamata** [comment]
@bstascavage if just wasn't being really used by anything and we're already working on web ui in another way. 

Please, next time if you want just to discuss or ask something try to reach us at the slack chat. Right now we cannot invite more ppl because our invite bot got rate limited.

**Comment by bstascavage** [comment]
Ok, so can I get an invite to the Slack channel?  It is really hard to collaborate if I am missing out on the main avenue of communication?

**Comment by bstascavage** [comment]
@jtdroste If the invite bot is rate limited, can I please get a manual invite to the Slack channel?  My email is brian@stascavage.com

**Comment by bstascavage** [comment]
I would also argue that a REST Framework is not mutually exclusive to a web ui.  On top of the web ui being able to call the framework for information, other tools that other developers might want to write around the bot can use the framework as well.

Again, I would love to discuss this further, but I am unable to join the Slack team.  I understand that the invite bot is overwhelmed, but can't you manually invite through Slack?  @jtdroste @douglascamata

**Pull request closed without merging**
