### PR TITLE
Fixed list of charged attacks for Venonat (#3548) + BaseDefense/BaseStamina info fix

### PR DESCRIPTION
**Pull request by amal**
Fixed error #3548

### CODE REVIEW

**Comment by TheSavior** [comment]
Sorry @amal. Can you include this fix in a revert of the revert?

**Comment by nikhil-pandey** [comment]
Lol

**Comment by amal** [comment]
@TheSavior ok :)

**Comment by amal** [comment]
@TheSavior revert of revert added + fixes

Also removed exception in case of unknown movest – added fallback variant and error message in log

**Comment by TheSavior** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/PokemonGoF/PokemonGo-Bot/pull-request/3550/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=PokemonGoF/PokemonGo-Bot)

**Pull request merged**
