### PR TITLE
Add readme GNU License

### PR DESCRIPTION
**Pull request by maestroi**
Short Description: 
Add the gnu license to readme

Fixes:
- 
- 
-

### CODE REVIEW

**Comment by ironbishop** [comment]
which version?

**Comment by tdurieux** [comment]
According to the file [LICENCE](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/LICENSE) in dev branch the licence is MIT. It is not a good idea to have two different licence for the same project

**Comment by ironbishop** [comment]
It is possible to multi-license a product. and many projects do that. It really depends on the original developer's choice.

**Comment by tdurieux** [comment]
In this case, it's a licence change (no licence -> GNU licence), theoretically you must have the agreement of all the contributors.

**Comment by ironbishop** [comment]
That's already been done in dev, I assume you agreed on that.

**Comment by maestroi** [comment]
@tdurieux pokemongof wanted to know opinion of others but he liked the idea.

**Comment by maestroi** [comment]
The problem is people selling this bot with close source.

**Comment by tdurieux** [comment]
My point of view does not count I'm not a contributor... 
My comment is just to point out that the license change is not a trivial matter.

> The problem is people selling this bot with close source.

I was not aware of this situation.

**Comment by ironbishop** [comment]
that's funny :) selling something useless (well, the only use is earning fake points in a fake world), and being able to find somone who buys it anyway with real name

**Comment by ironbishop** [comment]
By the way, this is not going to stop people from selling the bot: in fact, using a GNU license means encuraging them to sell it! :) 

Without a license, every software is closed source, so it's illegal to copy and sell it. With a MIT or GNU license, copying and selling gets legal.

**Comment by maestroi** [comment]
@ironbishop yes but it needs to be open source not closed source,
```The GNU GPLv3 is a copyleft license that requires anyone who distributes your code or a derivative work to make the source available under the same terms, and also provides an express grant of patent rights from contributors to users.```

**Comment by pokecunt** [comment]
download

**Comment by th3w4y** [comment]
@maestroi yes so they will be obliged to publish their changes... how will one keep track of what those changes are? and were are the modified sources available?
under GPL one is obliged to provide the code only on request even against a fee for delivering the source code on a DVD or something..

practically i am not sure that relicensing is of any use case, it only adds more obligations to the contributors at this stage.

if i want to reuse parts that i wrote for this project in a different project for example, 
then i would have to license under GPL my full new product...

**Comment by maestroi** [comment]
@th3w4y there is no reference to any license atm, we could make it MIT or GPL it was just a suggestion have a license

**Comment by solderzzc** [comment]
let me close, thanks for all the discuss.

**Pull request closed without merging**
