### PR TITLE
Re-loggin in if session token is close to expiring

### PR DESCRIPTION
**Pull request by MikeDX**
Short Description: 

Check for stale login and re-login if necessary

Fixes:

Bot working on "nothing" after a while due to session expiry

### CODE REVIEW

**Comment by MikeDX** [comment]
It should do, I've done all the sanity checks, just letting it run for a while now to see if it does or not...

**Comment by MikeDX** [comment]
This failed for some reason, and I'm now trying to work out why, so please don't merge (for now)

**Comment by solderzzc** [comment]
sure.

**Comment by MikeDX** [comment]
A change is needed in the pgoapi.py file. PokemonGo-Map has a different file to us. Since we use a cloned version and not our own, any idea of the best way to go about changing it?

The second login is failing because the RPC endpoint is not returned for the second login. PokemonGo-Map either uses a different branch to us or a custom file (I can't tell which since they have the API folder included in their git repo and not sourced)

**Comment by Nihisil** [comment]
Are you sure, that it can't be fixed without changes in pgoapi? For example you can try to reinit API on login, or you can try to set `api._auth_token = None`. Something like this.

**Comment by bool-** [comment]
It appears the relevant changes are here. https://github.com/AHAAAAAAA/PokemonGo-Map/commit/c24590ec1ba6e925cc480855b26b3736784af3cf

**Comment by MikeDX** [comment]
You are both correct 

@bool you confirmed what I was trying to change

@Nihisil I have reset the api, and this appears to work!

Pushing new changes now

**Comment by dddbliss** [comment]
+1 on this.

**Comment by Nihisil** [comment]
I tested it a little bit, and it seems like to be a working solution 👍 

> [2016-07-25 10:46:19] [#] Attempting login to Pokemon Go.
> [2016-07-25 10:46:24] [+] Login to Pokemon Go successful.
> ...
> [2016-07-25 11:44:34] Session stale, re-logging in
> [2016-07-25 11:44:34] [#] Attempting login to Pokemon Go.
> [2016-07-25 11:44:37] [+] Login to Pokemon Go successful.
> [2016-07-25 11:45:20] [#] Something rustles nearby!

**Comment by MikeDX** [comment]
Thanks @Nihisil for the tip about resetting the API. That was a much better solution than hacking the pgoapi (which imho is broken when trying to get a new token, but there we go) :)

**Comment by MikeDX** [comment]
Mine has been running for 4 hours now and still farming away!

**Comment by solderzzc** [comment]
can you have the conflict fixed ?

**Comment by tonz134** [comment]
This works like a charm.
 been on for 3 hours now

**Comment by myeunggithub** [comment]
Just forked the new __init__.py file to my bot, will report back on results.

**Comment by solderzzc** [comment]
This branch has conflicts that must be resolved ....... oops, duplicated review....... I need this merged badly.

**Comment by MikeDX** [comment]
Didn't have any conflicts when I submitted it!!! :(

Fine I'll go fix it :P

**Comment by skydrome** [comment]
working here, thanks for this much needed fix!

**Comment by MikeDX** [comment]
ok this has the conflicts resolved, but I've no idea what the travis build errors are for/from.

**Comment by tstumm** [comment]
Can you move the session expiration check to a separate function?

**Comment by MikeDX** [comment]
I can, but I will wait until this branch is fixed before I do so, otherwise I will probably end up with more merge conflicts

**Comment by tstumm** [comment]
Well we don't like monolithic code. It just makes the code more readable and more clear.

**Comment by MikeDX** [comment]
Ok, well, as I asked before - can you clarify what part you want? Just the call to get the remaining_time value or the whole section from the first if check down to login?

**Comment by tstumm** [comment]
```
        # Check session expiry
        if self.api._auth_provider and self.api._auth_provider._ticket_expire:
            remaining_time = self.api._auth_provider._ticket_expire/1000 - time.time()

            logger.log("Session stale, re-logging in", 'yellow')
            self.login() 
```

That part.

**Comment by douglascamata** [comment]
@MikeDX would you want to extract login logic out of the Bot class and into a worker, just like all the other?

**Comment by douglascamata** [comment]
Waiting code isolation into separate worker to merge.

**Comment by MikeDX** [comment]
I've moved the login check out of the work_on_cell function and moved it to its own method. 

This has gone from being a nice easy fix to being a real time consuming exercise 👎

**Comment by douglascamata** [comment]
@MikeDX I know, but it's for the best of the codebase, because we're moving towards behaviour trees and we need to make code more modular. Even though you didn't do as I suggested, that's no problem because now it's easy for me to do it myself.

**Comment by MikeDX** [comment]
@douglascamata I'm happy for you to do it, I'm still not 100% up to speed with the whole new refactoring of the project, and having that horrible broken commit (with the teleporting) really put me off - felt like untested code was getting merged and useful code that prevent actual crashes like this was being nitpicked ;)

**Comment by douglascamata** [comment]
@MikeDX it's more like we have too many different situations to test code :/

**Comment by MikeDX** [comment]
I can appreciate that.

There are two times I can tell code has been merged with no apparent testing

- LCD support 
- walker / teleporting (testing this on anything beyond seeing if it compiles would have thrown the error everyone reported)

I am sure there have been others.

This fix I did originally was purely meant to satisfy a problem everyone was having - that the bot was dying after ~one hour, I wasn't prepared for the extra merge fixes (understandable) and subsequent refactoring.

I want to contribute to this project and have many ideas for improvements, but if the testing / approval / merge process is as shabby as this, it's just going to be a frustrating experience, which nobody wants.

**Comment by douglascamata** [comment]
@MikeDX it will become better when behaviour tree lands. With isolation code will become easier for us to review. Right now ppl are always trying to add too many features inside a method that they become bloated and errors are hard to spot.

**Comment by LasseSkogland** [comment]
Typo in code `pokemongo_boy/__init__.py`
On line 73 change location to position.

**Comment by MikeDX** [comment]
Oh for goodness sake.

Why the hell is it **location** in take_step and **position** in work_on_cell

This codebase is just a total mess.

Guess I"ll go and make a new pull request...

**Pull request merged**
