### PR TITLE
Fixed a small bug when user didn't have a VIP config!

### PR DESCRIPTION
**Pull request by xc-mezcal**
Short Description: 
This fix a small bug when user didn't update their config file for VIP pokemon setting (leave it for empty)

Fixes:
Return false if there is no such a setting instead of crashing.
- 
-

### CODE REVIEW

**Comment by xc-mezcal** [comment]
@solderzzc need to add 2 lines there for a small bug

**Comment by mercuriete** [comment]
I hit that bug.
I dont have vip pokemon.

**Comment by solderzzc** [comment]
sure, thanks a lot.
I was thinking this part :)

**Comment by mercuriete** [comment]
nice!

**Pull request merged**
