### PR TITLE
Added protection in polyline_generator.py.

### PR DESCRIPTION
**Pull request by solderzzc**
Added protection in polyline_generator.py.

### CODE REVIEW

**Comment by mjmadsen** [comment]
https://files.slack.com/files-tmb/T1U6G9ZEW-F283L8F8A-e8cf0dde04/pasted_image_at_2016_09_04_03_01_am_480.png

Someone just posted that @solderzzc looks related

**Comment by solderzzc** [comment]
@mjmadsen  yep, I agree.

**Comment by th3w4y** [comment]
@solderzzc that for the fix...

it was a big rewrite, i am sorry for the slipped bugs..

**Comment by mjmadsen** [comment]
Ah, so it's working in dev branch?

@th3w4y We've all been there :smile:

**Pull request merged**
