### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Reaver01**
Make Walking look better, Add html file for displaying player location

### CODE REVIEW

**Comment by necrozis** [comment]
(Just for fun :smile:)
@Reaver01 can we use switching:
'┌(￣ー￣)┘' and '└(￣o￣)┐'
for walking ?

**Comment by douglascamata** [comment]
@Reaver01 please remember there is no walking hook in `pgoapi` now. I removed our custom version in favor of the original at tejado/pgoapi.

**Comment by douglascamata** [comment]
@Reaver01 my work is on dev branch though.

**Comment by Reaver01** [comment]
I hadn't seen that yet.  Will do.

**Comment by douglascamata** [comment]
@Reaver01 naaahh, no need to close, just edit it. :P

**Pull request closed without merging**
