### PR TITLE
Add troubleshoot section to FAQ

### PR DESCRIPTION
**Pull request by sniok**
Short Description: 
Add troubleshoot section to FAQ and fix table of contents

### CODE REVIEW

**Comment by douglascamata** [comment]
@sniok add in the necessary information to report bug that we need logs, please.

**Comment by sniok** [comment]
What kind of logs?

**Comment by douglascamata** [comment]
Bot logs, lol. The ones you see in the terminal

**Comment by solderzzc** [comment]
cleaning up the pull-request folder, please reopen when you done the rebase.

**Pull request closed without merging**
