### PR TITLE
Changes in API

### PR DESCRIPTION
**Pull request by msoedov**
Short Description: 

Fixes:

-  Dev branch is not working #320
-  Tabs instead spaces (see pep8)

### CODE REVIEW

**Comment by msoedov** [comment]
KeyError: 'GET_MAP_OBJECTS'  still doesn't wok :(

**Comment by msoedov** [comment]
For some reason GET_MAP_OBJECTS is always empty
```
[!] Failed to save location
{'auth_ticket': {'end': 'VrtP1PrREQBqdJh/Ydhw==\n',
                 'expire_timestamp_ms': 1469235136142L,
                 'start': 'fF+Zmk2io6OVmNv9dpMiDxtI7Fo8leZhtBDoazc+iTpL6EuI6cYCdDMG+cm1925t+VANJiti9x\n3W41fZ0ccg==\n'},
 'responses': {'GET_MAP_OBJECTS': {}},
 'unknown2': 8145806132888207460L}
```

**Comment by smith-and-web** [comment]
ball stock is empty. needs update as well.

**Comment by douglascamata** [comment]
You're running out of date code or in a dirty environment. Please remove your working directory, cleanup your Python environment and use virtualenv. It should work.

**Pull request closed without merging**
