### PR TITLE
Added heartbeat threshold, it's not reasonable to send heartbeat to server every second.

### PR DESCRIPTION
**Pull request by solderzzc**
## Short Description:
Send heartbeat to server every second is not smart.

Added 'heartbeat_threshold' option and set default to 10.

### CODE REVIEW

**Comment by cmezh** [comment]
Is this option should be user-configurable?

**Comment by solderzzc** [comment]
yes, it is, I need update config.example.

**Comment by cmezh** [comment]
Hmm... I can't imagine the reason why users would like to change this option. Or maybe I not fully understand it.

**Comment by solderzzc** [comment]
They don't need to as always they use default value :)

**Comment by k4n30** [comment]
@solderzzc should there be a check for if the user sets a value too low? ie less than 5 (to prevent bans maybe?) Happy to be told no

**Pull request merged**
