### PR TITLE
Added Rudimentary IV Functionality

### PR DESCRIPTION
**Pull request by 05-032**
Short Description: 
This should allow the bot to decide when to transfer Pokemon based on IV in addition to CP. It adds, the individual IV values together, assuming a zero if the value isn't present and divides that by the max total IV value, creating a ratio.

### CODE REVIEW

**Comment by solderzzc** [comment]
This feature is very good, please help to rebase.

**Comment by 05-032** [comment]
Sorry, I'm really new to Git. What is rebasing?

**Comment by solderzzc** [comment]
Great PR, please help for the Readme.me if possible :)

**Comment by 05-032** [comment]
Thanks! I'll do what I can.

**Comment by MaxLeiter** [comment]
@solderzzc is there a chance you could enforce squashing of commits in PRs? It's great functionality, but two commits saying "no comment" isn't helpful for anyone.

**Comment by TheSavior** [comment]
Maintainers can squash commits when merging PRs via the UI. https://github.com/blog/2141-squash-your-commits

**Comment by 05-032** [comment]
@MaxLeiter Sorry about the commits. This is my first time using Github and I had some conflicts and in the process of trying to resolve them, I made the two commits. I'll make sure not to do that next time.

**Pull request merged**
