### PR TITLE
[FEATURE] Releasing account from soft ban

### PR DESCRIPTION
**Pull request by weknin**
Short Description: 
After jumping between distances, account will be soft-banned.
This feature will remove the ban.

Fixes:
Issue #1187, #1321

### CODE REVIEW

**Comment by krook1024** [comment]
This'd be so useful!

**Comment by DayBr3ak** [comment]
Shouldn't you add some sleep feature to not spam the server ? Or did I miss it ? If that's the case my bad. 
Seems like a great feature for the travelers :)

**Comment by douglascamata** [comment]
Has conflicts with dev and have a much more easy fix: just remove the RuntimeError being raised in line 118 of SeenFortWorker (original file from dev).

**Comment by douglascamata** [comment]
👎

**Comment by douglascamata** [comment]
#1522 has much better implementation!

**Pull request closed without merging**
