### PR TITLE
Update PokemonGo-Bot-Install.bat

### PR DESCRIPTION
**Pull request by simonsmh**
#4065
@LuckyMe4Evers improved the windows installer. New people can now install the full package. the installer gives you the choice to download and install the 32-Bit or 64-Bit Versions of the needed programs (Python, Git, Visual C++ for Python), after this they can choose in the menu to install the bot. I just need some links to download the encryptfiles to complete the installation.

### CODE REVIEW

**Comment by nivong** [comment]
👍

**Comment by LuckyMe4Evers** [comment]
I improved some things but don't have rights to sync changes.

**Comment by simonsmh** [comment]
Just post it here and we will help you.  @LuckyMe4Evers

**Comment by LuckyMe4Evers** [comment]
i have installed Github Desktop, but when i try to sync my changes i get the message that i don't have the permission.

**Comment by simonsmh** [comment]
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

**Comment by danielsdian** [comment]
This is going to conflict with PR 3898, but brings a lot of improvements that arent in that PR. I will need to take some time to check both install batches and merge whats best from both. (i.e Protoc installation using pip)

**Comment by simonsmh** [comment]
Add all these feature to your bat and then this pr can be closed. @danielsdian

**Comment by LuckyMe4Evers** [comment]
With the following changes, the batch install the appropriate version according to the 32 or 64 Bit OS
--Changes i made:

ECHO. 1) Install 32-Bit Programs
ECHO.
ECHO. 2) Install 64-Bit Programs
ECHO.
ECHO. 3) Install PokemonGo-Bot

-- Change in:
if "%OS%" == "32-BIT" (
	ECHO. 1 Install 32-Bit Programs
	) ELSE (
	ECHO. 1 Install 64-Bit Programs
	)
ECHO. 2 Install PokemonGo-Bot

-- more changes

IF "%_ok%" == "1" SET CHOICE=32Bit&GOTO :32Bit
IF "%_ok%" == "2" SET CHOICE=64Bit&GOTO :64Bit
IF "%_ok%" == "3" SET CHOICE=GoBot&GOTO :GoBot

-- change in
if "%OS%" == "32-BIT" IF "%_ok%" == "1" SET CHOICE=32Bit&GOTO :32Bit
if "%OS%" == "64-BIT" IF "%_ok%" == "1" SET CHOICE=64Bit&GOTO :64Bit
IF "%_ok%" == "2" SET CHOICE=GoBot&GOTO :GoBot

-- and last changes
cls
call:ech
set /p _Choose=Did you choose 32-Bit or 64-Bit Installation (1/2) ? 
if "%_Choose%" == "1" pip2 install --upgrade "%PGBotPath%\windows_bat\PyYAML-3.11-cp27-cp27m-win32.whl"
if "%_Choose%" == "2" pip2 install --upgrade "%PGBotPath%\windows_bat\PyYAML-3.11-cp27-cp27m-win_amd64.whl"

-- change in

if "%OS%" == "32-BIT" pip2 install --upgrade "%PGBotPath%\windows_bat\PyYAML-3.11-cp27-cp27m-win32.whl"
if "%OS%" == "64-BIT" pip2 install --upgrade "%PGBotPath%\windows_bat\PyYAML-3.11-cp27-cp27m-win_amd64.whl"

**Comment by danielsdian** [comment]
I successfully merged this PR with PR #3898 . Im adding the installation path option

**Comment by LuckyMe4Evers** [comment]
Did you apply the changes i made above ? @danielsdian

**Comment by danielsdian** [comment]
I didnt upload on GitHub yet, Im doing some testing on the installation path first. Will be doing until the end of the day.

**Pull request closed without merging**
