### PR TITLE
Consecutive Vanish Limit & Rest

### PR DESCRIPTION
**Pull request by alexyaoyang**
## Fixes/Resolves/Closes (please use correct syntax):
- #4510

screenshot 2016-09-02 at 12 52 29 pm

Note: If there is a `sqlite3.OperationalError: no such table: vanish_log` error, delete DB file to fix ( `data/yourusername.db`). This resets your daily catch limit tho. Maybe @BreezeRo has an better fix?

### CODE REVIEW

**Comment by solderzzc** [comment]
@alexyaoyang  How do you think to have this feature? 
And I feel the way to structure code in the capture worker is turning this file bigger. Is that better to have separated process logic ? We already have a alive/random/deep sleep workers, how should those tasks be structured ?

**Comment by alexyaoyang** [comment]
@solderzzc It's actually from FR #4510. Yes I totally agree, I was thinking of moving all the anti-ban measurements into another worker, but don't want to make this PR too huge to approve. I will submit another separate PR for code decoupling or separation of concern 👍

**Comment by solderzzc** [comment]
@alexyaoyang  If so, it's up to you to merge this PR in to keep it up to date.

**Comment by solderzzc** [comment]
👍

**Comment by alexyaoyang** [comment]
:+1

**Comment by solderzzc** [comment]
👍

**Pull request merged**
