### PR TITLE
Fixed 'pokemon_caught' event

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:
Fixes "catch error 2" appearing in telegram instead of correct catch message.

Fix removes a lot of redundant code. Tested with no errors.

## Fixes/Resolves/Closes (please use correct syntax):
- #5533

### CODE REVIEW

**Comment by Gobberwart** [comment]
DO NOT MERGE... minor bug-fix to come.

**Comment by Gobberwart** [comment]
pokemon_caught needs additional logic so it can be limited to only specific conditions (iv>x, cp>y etc.)

as for the other ones... shrug. Someone's personal formatting preference?

**Comment by Gobberwart** [comment]
OK this should be right to merge now.

**Comment by Gobberwart** [comment]
Should be OK to merge now

**Comment by solderzzc** [comment]
👍

**Pull request merged**
