### PR TITLE
output a txt file recording all the 'caught and keep' pokemons's IV

### PR DESCRIPTION
**Pull request by luoy2**
just a simple output

### CODE REVIEW

**Comment by douglascamata** [comment]
👎

**Comment by douglascamata** [comment]
@luoy2 you can check this information with the web ui.

**Comment by luoy2** [comment]
Thanks! so how should exactly I go to the web UI? couldn't find this information on ReadMe. is there a url that i can go to?

**Comment by douglascamata** [comment]
@luoy2 check this: https://github.com/OpenPoGo/OpenPoGoWeb

**Comment by douglascamata** [comment]
It works with our bot, follow the instructions.

**Comment by luoy2** [comment]
Thanks!

**Pull request closed without merging**
