### PR TITLE
Move adjustments for Movesets

### PR DESCRIPTION
**Pull request by davidakachaos**
See: https://www.reddit.com/r/TheSilphRoad/comments/6icwu4/type_effectiveness_changes/
We don't have the immunity in our stats, but as we don't fight gyms, I don't think we need it?
Noticed these changes when looking into #6069 but these changes are unrelated with the fast dps...

### CODE REVIEW

**Comment by solderzzc** [comment]
@davidakachaos you should have a pending invitation from pokemongof github team?

**Comment by davidakachaos** [comment]
@solderzzc I haven't seen it, where do you see such an invite?

**Comment by davidakachaos** [comment]
@solderzzc Never mind, found it and joined the team 😸

**Comment by solderzzc** [comment]
@davidakachaos nice, then you can do the pull approve for other PR, I guess the first invitation was sent on year 2016. lol

**Comment by solderzzc** [comment]
👍

**Pull request merged**
