### PR TITLE
Fix first egg incubating

### PR DESCRIPTION
**Pull request by DeXtroTip**
## Short Description:
Seems like when incubating first egg the `start_km_walked` is not found and the bot will use 9001. Maybe if we set it to 0 it might work, since after this, every other time the `start_km_walked` is found.
Fixed it.

## Fixes/Resolves/Closes (please use correct syntax):
- Fixes [#4687](https://github.com/PokemonGoF/PokemonGo-Bot/issues/4687)

### CODE REVIEW

**Comment by k4n30** [comment]
9001? wtf

**Comment by rawgni** [comment]
@mjmadsen

**Comment by mjmadsen** [comment]
Let me take a look in a bit.

**Comment by mjmadsen** [comment]
Took me entirely too long looking into the shelve key error. This looks good (on a 2nd run account).

Thanks for the PR!

**Pull request merged**
