### PR TITLE
Useful features sketches.

### PR DESCRIPTION
**Pull request by necrozis**
- [Pokeballs stock refill.] 
- [Great ball usage.] 
- [Store All pokemons from inventory, sort them by id.] 
- [Transfer all pokemon duplicates (>1) except most CP.] 

Please fix my code, i am still learning Python but i'm trying :dash:

### CODE REVIEW

**Comment by douglascamata** [comment]
@necrozis you mind waiting for my code refactor to use objects wherever possible to help me merge your work with mine?

**Comment by necrozis** [comment]
@douglascamata what should i do to help you?
Still need code to check gathered items from pokestop and change balls_stock values.
Also need code to trash some potions (if there are available) if inventory is full.

**Comment by douglascamata** [comment]
@necrozis in a few hours I'll update my fork with refactored code. Then I need help to merge our works. I think it will be easier to add your work on top of mine, because I'm reorganising stuff in a better way.

**Comment by necrozis** [comment]
@douglascamata, ok no problem.

**Comment by douglascamata** [comment]
@necrozis my code just finished its first walk! \o/

**Comment by PokemonGoF** [comment]
Wow, I just finished a meeting, would you mind if I add you as collaborators? @douglascamata @necrozis

**Comment by necrozis** [comment]
@PokemonGoF, ok :smile:

**Comment by PokemonGoF** [comment]
Invitation sent @necrozis :)

**Comment by douglascamata** [comment]
@necrozis we merged my big code structure refactor. So we need you to rebase your changes on master :(

**Comment by PokemonGoF** [comment]
I can do the merge, maybe... let me try.

**Comment by PokemonGoF** [comment]
Oops, I can't modify it  @necrozis would you mind to do the merge again?

**Comment by necrozis** [comment]
I,ll make new merge.

**Pull request closed without merging**
