### PR TITLE
Merge Dev to Master

### PR DESCRIPTION
**Pull request by MerlionRock**
Forked PGoAPI version changes causes those on master not able to run bot.

Need to merge this asap.

### CODE REVIEW

**Comment by TheCannings** [comment]
You also need to change run.sh line 25

required=(cat requirements.txt | sed -e 's/.*pgoapi$/pgoapi==1.2.0/' -e 's/[-_]//g' -e 's/==\(.*\)/:\1/' | awk '{print tolower($0)}')

to

required=(cat requirements.txt | sed -e 's/.*pgoapi$/pgoapi==1.2.1/' -e 's/[-_]//g' -e 's/==\(.*\)/:\1/' | awk '{print tolower($0)}')

**Comment by MerlionRock** [comment]
@TheCannings Done. And merged to Dev

**Comment by BreezeRo** [comment]
Revising

**Comment by MerlionRock** [comment]
Hi @BreezeRo Can join us in Discord?

**Pull request merged**
