### PR TITLE
Polyline rework

### PR DESCRIPTION
**Pull request by kanemasa1987**
## Short Description:
Rework on polyline.
It should  [swim across the Atlantic Ocean](http://googlesystem.blogspot.jp/2012/10/more-funny-directions-in-google-maps.html) now, just like we do.

## Fixes (provide links to github issues if you can):
-Added option to use PolylineWalker with MoveToMapPokemon
-Fixed it to get it work as intended

## Actual Paths

image

### CODE REVIEW

**Comment by kanemasa1987** [comment]
Puzzled with the tests, leaving them for now...

**Comment by k4n30** [comment]
@kanemasa1987 can you resolve merge conflicts please

**Comment by kanemasa1987** [comment]
@k4n30 
Updated!

**Comment by douglascamata** [comment]
👍 

LGTM!

@TheSavior, please review this!

**Comment by BriceSD** [comment]
Hail to the Italian stallion !  Yes please review this @TheSavior

**Comment by k4n30** [comment]
@TheSavior (just incase you didnt get the first 2 pings :p)

**Comment by TheSavior** [comment]
Yeah, this seems fine. Thanks for the repeated ping!

:+1:

**Comment by neohunter** [comment]
This works for all the walkers? like MoveToFort?

**Comment by kanemasa1987** [comment]
It needs minor fix for that, and I will work for it soon.
There is a possible teleport bug if many multiple workers start using this walker, so it is currently provided only for MapPokemon.

**Pull request merged**
