### PR TITLE
Decouple hb from step walker

### PR DESCRIPTION
**Pull request by sohje**
## Short Description:
Decouple hb from step walker due to #5243
## Fixes/Resolves/Closes (please use correct syntax):
- Fix

### CODE REVIEW

**Comment by th3w4y** [comment]
@sohje what is calling heartbeat now?

**Comment by sohje** [comment]
Heartbeat works in separate thread now, with timer and another checks, like block hb from sniping.

**Comment by th3w4y** [comment]
@sohje  That part i noticed, what is did not noticed yet is when is this called except .login()
>Heartbeat works in separate thread now, with timer and another checks, like block hb from sniping.

**Comment by sohje** [comment]
@th3w4y 
```python
threading.Timer(self.heartbeat_threshold, self.heartbeat).start()
```

**Comment by th3w4y** [comment]
@sohje  so it is actually this change that made the bot walk faster not our StepWalker PolylineWalker! and not the speeds match the reality!

**Comment by sohje** [comment]
@th3w4y How can this be possible? We sending requests as usual.

**Comment by th3w4y** [comment]
@sohje but that is a good thing that we can respect the speed settings...

**Comment by th3w4y** [comment]
@sohje Looks perfect to me

like I was saying previous comments this actually fixes a real bug
 (a new thread would have been spawn on every bot.tick())

**Comment by solderzzc** [comment]
👍

**Pull request merged**
