### PR TITLE
Catches pokemon and spins pokestops on --mode all

### PR DESCRIPTION
**Pull request by mortii**
Short Description: 
Stops on the way to pokestops so you can capture pokemon on --mode all. I've tried to merge this in for 2 days now, but the my changes are too big and the code base too unstable for me to do this. As a consequence I've reverted and/or changed alot of code just to make it runnable. 

Fixes:
-  catches pokemon and spins pokestops on --mode all

### CODE REVIEW

**Comment by solderzzc** [comment]
I like this commit, I was trying to do this days ago, just interrupted by other issue. 
Please fix the conflicts :)

**Comment by douglascamata** [comment]
first thing, remove the pgoapi folder, because we install it using pip

**Comment by douglascamata** [comment]
You're clearly coming from a working dir that is messed up with `master` and `dev` code. It's impossible to consider to merge your pull request until you get a clean environment and test everything you said you fixed again.

**Comment by mortii** [comment]
max_steps function was just broken so I removed it, but it should be easier to implement a working version with my code.

**Pull request closed without merging**
