### PR TITLE
Huge refactoring in favor of objects and responsibility separation

### PR DESCRIPTION
**Pull request by douglascamata**
I add description in a few minutes. Coding + cooking just made me cut my finger, lol. 

----

Basically I split the code in:

- the Bot class, the main controller of the bot
- the Stepper class, responsible for (guess what?) taking steps 
- cell_worker, classes responsible to process the many different type of cells we can find

### CODE REVIEW

**Comment by douglascamata** [comment]
I already saw some un-used stuff I want to remove, please don't merge yet.

**Comment by douglascamata** [comment]
Incoming tomorrow: a small framework to create reports for when the bot finishes, which will be also used to log events properly instead of just printing stuff.

**Comment by bebef1987** [comment]
This is failing: 
- 0 xp
Traceback (most recent call last):
  File "pokecli.py", line 105, in <module>
    main()
  File "pokecli.py", line 102, in main
    bot.take_step()
  File "/home/bebe/PokemonGo-Bot/bot.py", line 26, in take_step
    self.stepper.take_step()
  File "/home/bebe/PokemonGo-Bot/stepper.py", line 59, in take_step
    self.bot.work_on_cell(cell,position)
  File "/home/bebe/PokemonGo-Bot/bot.py", line 43, in work_on_cell
    hack_chain = worker.work()
  File "/home/bebe/PokemonGo-Bot/cell_workers/seen_fort_worker.py", line 48, in work
    for item in spin_details['items_awarded']:
KeyError: 'items_awarded'

**Comment by douglascamata** [comment]
@bebef1987: give me 5 minutes

**Comment by bebef1987** [comment]
@douglascamata np I will retest it after that

**Comment by douglascamata** [comment]
@bebef1987, please, test again.

**Comment by bebef1987** [comment]
@douglascamata  not sure the protocol but r+

**Comment by bebef1987** [comment]
thanks for fixing it

**Comment by PokemonGoF** [comment]
Haven't seen any issue. R+

**Comment by berend** [comment]
oh, cool, this looks quite good. It interferes with my https://github.com/PokemonGoF/PokemonGo-Bot/pull/86, but it touches different area. I concentrated on output and logging, this on here on classes and objects. If in doubt, merge this one here first

**Comment by PokemonGoF** [comment]
@douglascamata  Please merge when you feel comfortable. Invitation sent.

**Comment by douglascamata** [comment]
@PokemonGoF thank you very much! It's a pleasure to contribute and an honor to be part of the team. 

I'll merge this and start working on report framework.

**Comment by PokemonGoF** [comment]
@douglascamata  The honor is mine. Looking forwarding for it.

**Pull request merged**
