### PR TITLE
Added some variance in max amount of pokemon bag before releasing

### PR DESCRIPTION
**Pull request by Napator**
For more human behaviour.

### CODE REVIEW

**Comment by solderzzc** [comment]
how to trigger the CI again, seems I just fixed it

**Comment by BriceSD** [comment]
Lets say min_free_slot = 0. In other words, transfer pokemons once my bag is full. It’ll take a lot of try before transferring, you’ve 5% chance to do so.
Same issue when 0 ≤ min_free_slot ≤ 20.

Do you use every possible option ? Personally I don’t like to be forced to use one. What about adding this to the config file ?

**Comment by Anakin5** [comment]
Seems to me that  it is going to rand a new number at every loop, so random distribution  is very bad and you are going to release at your configured value or very close to it most of the time.

**Comment by solderzzc** [comment]
@Anakin5 so what should we do? Any further suggestion?

**Comment by Anakin5** [comment]
Rand a number in the init and after work is done. That way, you will hold onto that number.
Also, check you always stay between 0 and inventory size.

**Pull request merged**
