### PR TITLE
Added release_below_ivcp and keep_best_ivcp

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:

Added release_below_ivcp and keep_best_ivcp to TransferPokemon

**Reviewers please check this very carefully as I may have missed something important** 

## Fixes/Resolves/Closes (please use correct syntax):
- #5225

### CODE REVIEW

**Comment by Gobberwart** [comment]
Heh, I might wait for another review... @solderzzc @DBa2016 @alexyaoyang @mjmadsen ?

**Comment by solderzzc** [comment]
👍  seems good. I haven't found issues with this PR.

**Comment by Gobberwart** [comment]
Alright. Merging. Hope it's right :)

**Comment by Gobberwart** [comment]
Dammit, I knew there'd be an error somewhere. Looking at it.

**Comment by Gobberwart** [comment]
Hmmm line 59 isn't even a line..

**Comment by Gobberwart** [comment]
Nope, I'm out. Wine. Anyone?

**Comment by Gobberwart** [comment]
I can't see the issue... Not even sure it's got anything to do with this PR. 

```
    def _release_pokemon_worst_in_group(self, group, pokemon_name):
        keep_best, keep_best_cp, keep_best_iv, keep_best_ivcp = self._validate_keep_best_config(pokemon_name)
```

**Comment by alexyaoyang** [comment]
Found it, opening PR. 👍

**Pull request merged**
