### PR TITLE
Add missing submodule update to setup.sh

### PR DESCRIPTION
**Pull request by agentcpper**
## Short Description:
Currently script is only doing `git submodule init`, but it needs to do `git submodule update` before attempting to pull master or the `web` submodule will not be checked out.

### CODE REVIEW

**Comment by simonsmh** [comment]
Do you know what does this mean?
git submodule foreach git pull origin master
Close this pr plz

**Comment by simonsmh** [comment]
sorry I known what you mean.
Although this is required but it will only need once. I will add this into install.sh. Thx.

**Comment by simonsmh** [comment]
For now use git submodules update --init to replace both two lines is better.

**Comment by nivong** [comment]
@simonsmh please use the edit button ;-)

I would recommend you change it to:
```
git submodule update --init --recursive

**Comment by nivong** [comment]
added this to here to make it more simple:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/3593

**Comment by TheSavior** [comment]
Closing in favor of #3593

**Comment by stefanahman** [comment]
How are submodules updated when running Docker?

**Pull request closed without merging**
