### PR TITLE
fix unicode issues

### PR DESCRIPTION
**Pull request by CapCap**
Short Description: 

Fixes:
- #1814 
- 
-

### CODE REVIEW

**Comment by vieira** [comment]
The problem is that the log function is sometimes called with an already decoded utf8 str while some other times it is called with an unicode sequence that needs to be decoded before print. 

```
def log(string, color='white'):
    try:
        string = string.decode('utf8')
    except UnicodeEncodeError:
        pass

<rest of the original code>
```

This is enough to fix the problem and make log work with both str and unicode sequences.

**Comment by DayBr3ak** [comment]
190640f06fc623f804c554ce1ac9264c9fa8b22d makes this irrelevant

**Comment by vieira** [comment]
@DayBr3ak still getting errors if the initial location contains any special characters.

**Comment by vieira** [comment]
#1825 should fix the issue with the initial location.

**Pull request closed without merging**
