### PR TITLE
Insert random speed to make bot more human like

### PR DESCRIPTION
**Pull request by BoGnY**
Short Description: 
Insert a random speed in interval 0/+2 km/h in step_walker.py to make bot more human like

### CODE REVIEW

**Comment by douglascamata** [comment]
This doesn't make a lot of difference, anyway. And speed isn't in any unit, it's just an empirical number. Docs are outdated with regards to this.

**Comment by tstumm** [comment]
km/h would be the wrong unit too.

**Comment by TheSavior** [comment]
I agree with douglas. This is essentially random because of the random delay between each step we take, and we modify the coordinates we go to with a random amount of jitter.

**Comment by BoGnY** [comment]
So what is the utility of speed on config.json???

**Comment by tstumm** [comment]
It's the distance you "walk" after each tick if there is no other task blocking it.

**Comment by Nik0lashka** [comment]
@tstumm , distance in km or miles or smth else? And what is tick and what is the frequency of it?

**Comment by tstumm** [comment]
Meters. A tick is just a term for the whole task chain running once. There is no exact frequency, since the runtime of one tick is not deterministic.

**Comment by Nik0lashka** [comment]
@tstumm, i suppose that tick is like processor time and it doesn't directly correlate with real time? Is it about millisecond or so?

**Pull request closed without merging**
