### PR TITLE
Loiter new meaning

### PR DESCRIPTION
**Pull request by janpascal**
## Short Description:

Add a `loiter` option to the json path used by `FollowPath`.  Similar to `wander` but it doesn't allow lower priority task to run while loitering.

Also make the progress log from `FollowPAth` a bit more informative by logging the location as found in the json file instead of the raw coordinates.

### CODE REVIEW

**Comment by janpascal** [comment]
@alexyaoyang This one also OK with you?

**Comment by alexyaoyang** [comment]
I think this is OK, but do we really need it? The exact same effect can be achieved with wander by not having any task below FollowPath, am I right?

**Comment by janpascal** [comment]
Not exactly, since `loiter`/`wander` are per-point options; one might want to `wander` at one point of the route, and `loiter` at another. E.g., `loiter` at (one or more) known spawn points, and `wander` visiting a number of pokestops inbetween.

**Comment by Gobberwart** [comment]
So... correct me if I'm wrong, but this basically means go to point, then do absolutely nothing at all for a specified number of seconds. No catching, no spinning fort, no inventory maintenance, just standing still doing nothing. Is that right? If so, what's the purpose?

**Comment by alexyaoyang** [comment]
It could be useful to make the bot behave more human-like, most people take breaks at/near pokestops rather than randomly in the middle of a street for example. Similar to CampFort but without the need for lured forts.

**Comment by janpascal** [comment]
No, during loiter the bot would still spin forts, catch pokemon etc but not any lower priority tasks like, in the default config, MoveToFort. Keep in mind that you can configure this for every point in the path, so if one of the points in the route is a spawn point you can configure to stay exactly there (`loiter`) for a while to catch the pokemon spawning there. Then walk to a known area with some forts: add a  `wander` to that point in your `path.json`  to walk to the some of the forst and spin a  them. Then continue with the next point in the route.

**Comment by solderzzc** [comment]
👍

**Pull request merged**
