### PR TITLE
Unban Immediately When You Fly

### PR DESCRIPTION
**Pull request by wilsonyqm**
Short Description: 
  Since the SoftBan can be resolved, trainer is able to fly to some specific location to catch legendary Pokemon. In order to do so,  you need to encounter the Pokemon first, and fly back to the home location you have set.

Only thing we need to do: change the location, set your home location where you cannot get banned in `config.json`, run the program.  Set `'home_location' = "home, location"`,  in `configs/config.json`.

Better Close 
```json
      {
        "type": "FollowSpiral"
      }
```
Fixed:
`self.softban` -> `self.bot.softban`, to make sure softban works on Bot Object.

### CODE REVIEW

**Comment by JohnnyOmm** [comment]
I changed the position on top of the pokemon I want but it just vanishes like normal
[image](http://prntscr.com/bzc2xk)

**Comment by wilsonyqm** [comment]
Did you turn `location_cache` off, and make sure you have a `location_cache` file

**Comment by JohnnyOmm** [comment]
Ya I have both of those, but im not certain of there is a pokestop nearby :p ill test it again and then probably go to bed. thankyou!

**Comment by wilsonyqm** [comment]
I feel like you are not on the current dev branch, My output is `Moving towards fort efcee43f7ee748ad8edf0927e47c596e.16` but yours is `Moving to new fort efcee43f7ee748ad8edf0927e47c596e.16`

**Comment by gregtampa** [comment]
This branch has conflicts that must be resolved

**Comment by douglascamata** [comment]
@wilsonyqm you must use the softban worker for this.

**Comment by douglascamata** [comment]
👎

**Comment by wilsonyqm** [comment]
Import a new config params, and squash all the changes in the Workers File, try a different way of unbanning: `set the location back when encountered`, now, it has nothing to do with Softban worker.

**Comment by douglascamata** [comment]
I don't see you reset home_location ever and it's not clear how this code works....

**Comment by TheSavior** [comment]
@wilsonyqm There are a couple of other things people are doing right now to support what it seems like you are trying to support. There are a couple different approaches in the works right now for sniping pokemon, and we have a HandleSoftBan worker. If those are sufficient, great. If not, please reach out again and we can make sure we are supporting what you are trying to do.

**Pull request closed without merging**
