### PR TITLE
[Feature] add config for minimum snipe priority #2450

### PR DESCRIPTION
**Pull request by mhdasding**
Short Description: 
if snipe is enabled only snipe pokemon with a minimum priority, still walk to pokemon below this priority.

### CODE REVIEW

**Comment by mhdasding** [comment]
also fixes #2443

**Comment by chrismapes** [comment]
This sounds great! How would you feel about a PR that did:

- Attempt to "drive" to pokemon instead of snipe
   - Get lat lon of pokemon, send current coordinates and pokemon coordinates to Google Directions Server
   - Get Path
   - Follow Path at random speed between 30-45 mph
   - Ease out speed upon approach to pokemon to 5 mph.
   - Catch pokemon
   - Either drive to next pokemon on snipe queue, or return to walk area and resume walk.

- Have option to snipe only if pokemon is impossible to reach in time via "driving". Maybe also drive closer before sniping to minimize distance and potentially reduce future ban hammer likelihood.

If you don't think this is valuable I'll probably end up writing a PR for it in the next week, I'm just up to my ears with real "work" dev work and don't have time ATM. My only hesitation with the snipe feature is that if Niantic is keeping a history of pokemon spawned and the nest they were spawned at (thereby knowing lat long), and user location history, it's going to be really easy for them to write a filter to find pokemon catches that weren't possible due to unrealistic player distances from the nest and do a mass ban. I'd hate to build up my bot player and then suddenly out of the blue get banned.

**Comment by mhdasding** [comment]
@PlanetoftheMapes that would be totally valuable :D i suggest putting the driving logic tho in a new `DriveWalker` so it could be interchanged for `StepWalker`.

**Comment by PlanetoftheMapes** [comment]
@mhdasding Good call, I'll dig into it next week unless someone else ends up championing it.

**Comment by maradlgl** [comment]
please fix line 107
error

**Comment by mhdasding** [comment]
will close this for now, will reopen a PR after some major PRs got merged

**Pull request closed without merging**
