### PR TITLE
PgoAPI Change

### PR DESCRIPTION
**Pull request by MerlionRock**
Once committed, will force user to be use latest PGoAPI.

If anyone updated their PGoAPI without these changes, they can't run the bot.

Latest PGoAPI at 0.59.2

### CODE REVIEW

**Comment by MerlionRock** [comment]
👍

**Comment by MerlionRock** [comment]
@pogarek Can commit? After this, we can merge all changes to Master

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
merged #5997

**Pull request merged**
