### PR TITLE
Optimizer fix [Now against DEV]

### PR DESCRIPTION
**Pull request by davidakachaos**
Same as previous, but now PR against dev instead of master

### CODE REVIEW

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
merged #6011

**Comment by Jcolomar** [comment]
Sorry but still no working
sin titulo


Log of optimicer here: https://pastebin.com/mkh61cXH

**Comment by Jcolomar** [comment]
My mistake, i was on master branch. I'll test asap pogo_optimizer start on my second acc.

**Comment by Jcolomar** [comment]
Tested and works. TYVM

**Pull request merged**
