### PR TITLE
Telegram - Alternate method of finding master id

### PR DESCRIPTION
**Pull request by Gobberwart**
Will not respond to unknown sender, but will instead generate helpful log messages.

This is in response to people struggling to find master (#5150), and is an alternative solution to PR #5153 

- Eliminates current security issue of bot responding to unknown sender
- Prints detailed log information to assist users in entering user id in config file as master

### CODE REVIEW

**Comment by mjmadsen** [comment]
I'd say update the configuration_files.md and I prefer over #5153 

@askovpen Do you find this to be a satisfactory compromise to the initial goal?

**Comment by mjmadsen** [comment]
:+1:

**Comment by DBa2016** [comment]
From what I see, this PR breaks existing functionality of providing a username as master. Can we have it reverted and implemented correctly please?

**Comment by askovpen** [comment]
with telegram bot api can't use correct usernames (only userids)

**Comment by Gobberwart** [comment]
@DBa2016 This change has no effect on the use of "@username" as master. It does, however, strongly encourage using the id instead if no id is supplied (or an incorrect id/username). No need to revert.

**Comment by DBa2016** [comment]
@Gobberwart : sorry, I misread the dff (it looked like you removed the whole non-numeric comparison section, while it is modified and not removed completely). Never read diffs on a cellphone...

**Comment by Gobberwart** [comment]
@DBa2016 That's exactly the same mistake I made reading #5166

**Pull request merged**
