### PR TITLE
Fixed 'Pokemon will now be caught from lures'

### PR DESCRIPTION
**Pull request by aslafy-z**
This PR fixes #1056 typos.

Thanks to the guy behind this :wink:

### CODE REVIEW

**Comment by surfaace** [comment]
approved, 2nd approver needed

**Comment by Calcyfer** [comment]
@surfaace  Don't merge please, it will not work without the new API.

A new PR is coming up.

**Comment by OVO647** [comment]
How can I install this?

**Comment by aslafy-z** [comment]
@OVO647 Check that: [https://lalatendu.org/2015/12/02/cherry-pick-a-pr-pull-request-from-github/](https://lalatendu.org/2015/12/02/cherry-pick-a-pr-pull-request-from-github/)

**Comment by kaoztheory** [comment]
broke causing https://github.com/PokemonGoF/PokemonGo-Bot/issues/1122

**Comment by kaoztheory** [comment]
reinstall of latest dev fixed it fyi

**Pull request merged**
