### PR TITLE
Cleanup the Web UI

### PR DESCRIPTION
**Pull request by vanZeben**
Short Description: 
  Cleans up the UI a bit and hides the panels as they dont need to be shown all the time... Live Demo can be seen: http://pokemon.vanzeben.ca/

### CODE REVIEW

**Comment by jtdroste** [comment]
lgtm - anyone else have any comments before a merge?

**Comment by solderzzc** [comment]
looks safe to me.

**Comment by TheGoldenXY** [comment]
Why would you make a PR if you didn't test the code in the first place and more importantly if the code is not working? Please make sure the code is working before creating a PR.

**Comment by vanZeben** [comment]
@TheGoldenXY Code does work and I posed a live version of the branch where it's working, which I don't see any issues on. Unsure what you're talking about.

**Pull request merged**
