### PR TITLE
Ignore legendaries for in gyms

### PR DESCRIPTION
**Pull request by davidakachaos**
Now with Legendaries being added, we can't place those in gyms.

### CODE REVIEW

**Comment by MerlionRock** [comment]
👍

**Comment by MerlionRock** [comment]
Hmm.... I think have to rebase this in order to merge?

**Comment by MerlionRock** [comment]
👍

**Comment by MerlionRock** [comment]
Hmm... Why the Travis never finish checking...?

**Comment by davidakachaos** [comment]
I don't know?

Op 23 jul. 2017 16:36 schreef "MerlionRock" <notifications@github.com>:

**Comment by goedzo** [comment]
I think this code should not hardcode legendaries. In protos you can find this:


syntax = "proto3";
package POGOProtos.Enums;

enum PokemonRarity {
	POKEMON_RARITY_NORMAL = 0;
	POKEMON_RARITY_LEGENDARY = 1;
	POKEMON_RARITY_MYTHIC = 2;
}

Which is part of:

message PokemonSettings {
	.POGOProtos.Enums.PokemonRarity rarity = 14;
}

In pgoapi it is also there:

_POKEMONSETTINGS = _descriptor.Descriptor(



    _descriptor.FieldDescriptor(
      name='rarity', full_name='pogoprotos.settings.master.PokemonSettings.rarity', index=12,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),


So please use the definition from Niantic.

**Comment by davidakachaos** [comment]
@goedzo Agreed, but currently we haven't implemented PokemonSettings in the bot. We have a file under data called Pokemon.json containing information about the Pokemon, currently we don't download any settings like that. We should(!) but we don't right now.
So I agree we should use that feature (let's open an issue about it) but we currently don't have access to it in the bot.

**Comment by goedzo** [comment]
@davidakachaos Good point :). So this can be merged then.

**Comment by MerlionRock** [comment]
Travis failed. Gym has some changes and has already being merge, so there might be conflict too. I will close this for now and I will compare the different and open another one later.

**Pull request closed without merging**
