### PR TITLE
Telegram-startup optimization

### PR DESCRIPTION
**Pull request by javajohnHub**
## Short Description:
Small change to telegram to remove more unneeded events that could be bogging the bot at startup
## Fixes/Resolves/Closes (please use correct syntax):
-possibly #5527
-
-

### CODE REVIEW

**Comment by Gobberwart** [comment]
My brizzanch? LOL..izzle

I totally agree with removing unnecessary imports, but removing events... not so much. I'm really not sure they have any impact on startup performance, and people might want to know about them.

**Comment by javajohnHub** [comment]
You can test pre removal vs post and see a drastic improvement, but the decision is yours. Thanks for the review.

**Comment by javajohnHub** [comment]
And there is not really a point in knowing about events in telegram that do not produce output anyway.

**Comment by Gobberwart** [comment]
Not sure I agree with removing events, as (a) they shouldn't have any impact on startup - or really anything since they only trigger if the event occurs, and telegram is running in a separate thread, and (b) some people might actually want to see those events.

Removing unneeded imports is a great idea, so long as you're absolutely sure they're not needed - and they shouldn't be since the functionality was moved to chat_handler.py

**Comment by javajohnHub** [comment]
fair enough.

**Pull request closed without merging**
