### PR TITLE
RecycleItemWorker implemented (runs on every tick)

### PR DESCRIPTION
**Pull request by douglascamata**
Simple RecycleItemWorker implementation. Doesn't add any more features on top of already existing code. 

Adds a different call to `bot.item_count_inventory('all')`, which returns the count of every item in the inventory.

### CODE REVIEW

**Comment by TheSavior** [comment]
You are kinda stepping on @surceis toes here @douglascamata. Haha https://github.com/PokemonGoF/PokemonGo-Bot/pull/1143

**Comment by douglascamata** [comment]
@TheSavior I saw that, but that one's code looks gigantic and has more features. This keeps the features we have with simple code.

**Comment by TheSavior** [comment]
I'm worried that if we merge this one, then we won't get those additional features. I like iterative PRs, but @surceis has put in a bunch of work so I want to be supportive and make sure we can get it in.

**Comment by Surceis** [comment]
Sure, you can merge this. Then i can try to PR only info at start with not only pokeballs?

**Comment by TheSavior** [comment]
Alright. Sounds good. Thanks @surceis!

**Comment by TheSavior** [comment]
:+1:

**Comment by douglascamata** [comment]
@TheSavior I'll move the `RecycleItemsWorker(self).work()` to inside `work_on_cells` method, like in @Surceis's PR.

**Comment by TheSavior** [comment]
@douglascamata, get your butt on slack! 👮

**Comment by Surceis** [comment]
```javascript
{ "101": { "keep" : 50 }, "102": { "keep" : 50 }, "103": { "keep" : 50 } }
```
Just in case, what if we have 50 of each balls (150 in sum), and want to keep only a powerful balls, and when they gone (powerful) to keep weaker one (previous), but when powerful is exist and greater than "keep" value, remove weaker one? Can this be solved?

**Comment by tstumm** [comment]
👍

**Comment by douglascamata** [comment]
@Sourceis: nope, this is a complicated but interesting situation.

**Comment by TheSavior** [comment]
:+1:

**Comment by Zgrkaralar** [comment]
I git pull dev version now always try 
Cleaning up Pokemon Bag using the release config
[05:32:35] Pokemon Bag has been cleaned up!

screen shot 2016-07-27 at 12 32 38 pm

**Pull request merged**
