### PR TITLE
Add a little jitter to sleep

### PR DESCRIPTION
**Pull request by brantje**
Should make it a bit harder for them to detect us.

### CODE REVIEW

**Comment by douglascamata** [comment]
@brantje thanks!

**Comment by tstumm** [comment]
I'm not sure if your calculations are correct.

**Comment by tstumm** [comment]
Lets imagine you want so sleep 5 secs.

jitter = 5 * 1000 / 10 = 5 * 100 = 500

so sleep_time is something in [5-500, 5+500] = [-495, 505] ....

**Comment by brantje** [comment]
And that is jitter

**Comment by tstumm** [comment]
Yep but we did not invent time machines yet, so negative seconds are not possible.

**Comment by tstumm** [comment]
Jitter should be like 10% of seconds, so `jitter = 0.1 * seconds`

**Pull request merged**
