### PR TITLE
Fix config.json.pokemons.example

### PR DESCRIPTION
**Pull request by johnw424**
Short Description: 
Fix incorrect settings.

Fixes:
- release_under_cp -> release_below_cp
- release_under_iv -> release_below_iv
- cp_iv_logic -> logic

### CODE REVIEW

**Comment by solderzzc** [comment]
This commit is not approved. 
```
            if not cp_iv_logic:
                cp_iv_logic = self._get_release_config_for('any').get('cp_iv_logic', 'and')

            release_results = {
                'cp':               False,
                'iv':               False,
            }

            if 'release_under_cp' in release_config:
                min_cp = release_config['release_under_cp']
                if cp < min_cp:
                    release_results['cp'] = True

            if 'release_under_iv' in release_config:
                min_iv = release_config['release_under_iv']
                if iv < min_iv:
                    release_results['iv'] = True
```
will break thing.

**Comment by solderzzc** [comment]
maybe I was wrong, let 2nd reviewer do again.

**Comment by ironbishop** [comment]
@solderzzc You were not wrong. When i write this, the correct variables are "under". Maybe it's not the correct English word, but this commit definitely break things.

https://github.com/PokemonGoF/PokemonGo-Bot/search?utf8=%E2%9C%93&q=release_under_iv 

If you modify release_config.json.example 
you need to modify also:
pokemongo_bot/cell_workers/evolve_all_worker.py
pokemongo_bot/cell_workers/pokemon_catch_worker.py

**Comment by ironbishop** [comment]
@solderzzc , @alvarogzp did this the right way in #980 , so this one (947) should be closed without merge

**Comment by solderzzc** [comment]
@ironbishop  Thanks a lot, some time can't just read code, too exhausted

**Pull request closed without merging**
