### PR TITLE
[Fix] Multiple instances shouldn't fight over dominance of the outfiles

### PR DESCRIPTION
**Pull request by haykuro**
Short Description: Allows multiple instances of the bot to run, with different users, without having to fight over dominance of the `outfiles`.

### CODE REVIEW

**Comment by solderzzc** [comment]
could you please explain how does work? I'm not a Python guy, I'm nodejs/cloud/mobile app/... guy.

**Comment by haykuro** [comment]
If I run multiple instances of the script, and they all want to write to 1 file, e.g. `web/location.json` or `web/catchable.json` they will fight to write to the same file.

The more instances you run, the slower it will get because they want to constantly try to open/lock/write/release the file. It becomes a power struggle and will eat up CPU / IO read/writes.

This PR is sorta incomplete (i just realized what those files do), I will have to update the [`web/index.html`](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/web/index.html#L53-L75) javascript to allow the user to perhaps define the usernames you're running?

**Comment by solderzzc** [comment]
I suggest you use different folder or docker for multiple account, that's a good way to do cluster.

**Comment by haykuro** [comment]
This would be in extension to Docker, not really a replacement..

It would be overkill to spin up multiple installations of the bot if 1 install is already capable of running as many as it wants (or as many as the allocated resources allow)..

The only thing preventing one from running multiple bots effectively is the use of the outfiles, and I see this as an enhancement for someone who wants to run 2 docker instances with 5 accounts on each one (as an example)

**Comment by solderzzc** [comment]
The cost of docker is very small, we should keep logic simple for maintain.

**Comment by haykuro** [comment]
No worries, this may be a personal preference.

We can close this for now.

**Comment by solderzzc** [comment]
Thanks, let's discuss later.

**Comment by MaxLeiter** [comment]
I see no downside to this; not everyone wants to use docker or have multiple instances (disk space and all that). :+1: from me

**Comment by TheSavior** [comment]
The approach could be as simple as naming the files based on the username currently signed in.

**Comment by MaxLeiter** [comment]
Did you check the modified files? That's basically what this PR is doing; it appends the username to the end of the file

**Pull request closed without merging**
