### PR TITLE
Adding documentation for how to use and write plugins

### PR DESCRIPTION
**Pull request by TheSavior**

### CODE REVIEW

**Comment by beranPro** [comment]
@TheSavior i've written a cell worker that snipes Pokémon using the coordinates from http://pokesnipers.com
Should i create a plugin for this or create a PR?

**Comment by TheSavior** [comment]
@beranPro Feel free to start as a plugin so that people can use it right away. If it makes sense to, we can later pull it into the core.

**Comment by solderzzc** [comment]
👍

**Comment by douglascamata** [comment]
👍

**Comment by douglascamata** [comment]
@TheSavior add a link to this in the README and merge. :P

**Pull request merged**
