### PR TITLE
Simple lure attraction in move_to_fort worker

### PR DESCRIPTION
**Pull request by z4ppy**
Add optional lure attraction in move_to_fort

### CODE REVIEW

**Comment by douglascamata** [comment]
@z4ppy please break down your lure attraction logic into many smaller methods.

**Comment by douglascamata** [comment]
@z4ppy need to solve merge conflicts with dev too, so I can merge.

**Comment by z4ppy** [comment]
I did some smaller method and is better like that, ty :)

**Comment by z4ppy** [comment]
I did some smaller method and is better like that, ty :)

**Comment by z4ppy** [comment]
How i can ?

The problem is contributor file

**Comment by z4ppy** [comment]
Merge done ! ^^

**Comment by douglascamata** [comment]
@z4ppy more merge conflicts, sorry :/

**Comment by douglascamata** [comment]
@z4ppy your merge is a bit messy, showing modifications that doesn't belong to your PR... but I really want your feature. Do you mind opening another PR?

**Comment by z4ppy** [comment]
I will redo :)

**Pull request closed without merging**
