### PR TITLE
Fix FollowPath bug

### PR DESCRIPTION
**Pull request by alexyaoyang**
## Fixes
- Setting number_lap to -1 is supposed to not limit the number of laps when using FollowPath, but the bot starts to rest after 1 round.

### CODE REVIEW

**Comment by alexyaoyang** [comment]
@solderzzc Ping!

**Comment by solderzzc** [comment]
still, the CI build failed. ...

**Comment by solderzzc** [comment]
how to trigger the CI again, seems I just fixed it

**Comment by alexyaoyang** [comment]
@solderzzc Seems like the server was busy earlier. I see that you've already submitted the fix. I've triggered a new CI build by reopening the PR.

**Comment by solderzzc** [comment]
Great, time to merge :) thanks @alexyaoyang

**Comment by alexyaoyang** [comment]
That's great! 👍

**Pull request merged**
