### PR TITLE
Do you want to open a gitter room for development?

### PR DESCRIPTION
**Pull request by solderzzc**
We do have slack channel, but we've lost millions of chat history, how do you think about this one?
https://gitter.im/pikabot-org/Lobby

### CODE REVIEW

**Comment by alexyaoyang** [comment]
Great decision! 👍

**Comment by Gobberwart** [comment]
love it. git integration is helpful

**Comment by Gobberwart** [comment]
Would be nice to limit it to approved people only (PokemonGoF members, other approved people) instead of "anyone with a git account".

**Comment by solderzzc** [comment]
@Gobberwart  I have not seen this option on gitter...

**Comment by mjmadsen** [comment]
I'd prefer we don't publicly advertise this chat. Instead, invite those who submit PRs and those that are already admins.

**Pull request merged**
