### PR TITLE
'all' in 'release' config discards all pokemon except N best (Closes #4552)

### LINKED ISSUE #4468: Keeping before-the-launch pokemon intact from transfer/evolution
### Short Description
Add an option to preserve any pokemon account had before launching bot. Pokemon caught before botting should be excluded from transfer, evolution and nicknaming.

### Possible solution
1. In `Pokemon` class (inventory.py) Introduce boolean variable `self.is_original` which should be set to True for all pokemon in inventory at bot's early start time. For all bot-captured pokemon set it to False (either by default or at capture time).
2. Later add boolean option to `TransferPokemon`, `NicknamePokemon` and `EvolvePokemon` tasks to optionally preserve pokemon with self.is_original set to True.

### How it would help others
A lot of people play game seriously -- they give names to their "pets", have 10 snorlax pokemon for different gyms and etc. They have their own plans for manually captured pokemon and that is why they often cry that bot acts destructively. That is why keeping X best bots is not a substitute for this. They would be happy to see those pet pokemon intact :)

*p.s.:* wrapping this logic above `is_favorite` is not an option because it is used in-game by user and setting it in automatic manner would be really disrespectful. The same goes for asking user to fav their pokemon (they have their own understanding for using favs).

### LINKED ISSUE #4552: [Feature Request] Releasing all pokemon in bag except X best ones
### Short Description
Currently it is possible to release all pokemon of some type except N best ones based on some criteria:
`"release": {
          "any": {"keep_best_iv": N}
}`
Ability to always keep N best pokemon in bag would be useful. For example, player may want to keep 150 best CP and 50 best IV pokemon always in his bag and to release everyone else.

### Possible solution
Implement new "pokemon name" `all` which is executed after all other rules (first we discard pokemon based on specific rules, than in what remains we keep best 150 pokemon):
`"release": {
    "all": { "keep_best_custom": "iv, cp, hp_max", "amount": 150 }
}`

This may be a naive implementation which ignores application order:

1. In `_release_pokemon_get_groups` we always return one extra fake group with pokemon_id = 10000. This group containa all pokemons from other groups (just fav/fort-filtered `inventory.pokemons().all()`).
2. On line 28 in `transfer_pokemon.py` we replace getting pokemon name with `pokemon_name = Pokemons.name_for(pokemon_id) if pokemon_id > 0 else 'all'`
3. Everything else works as expected.

If we want application order to be correct, things are more difficult (I don't know bot well enough to propose good solution).  As far as I can see:

1. Refactor lines 29-87 (contents of `for` loop except the first line) in `transfer_pokemon.py` in a separate function `_release_pokemon_group(pokemon_list, pokemon_name)` to launch it later below the for loop with pokemon name equals to `'all'`.
2. After the end of `for` loop:
`group = [p for p in inventory.pokemons().all() if p.in_fort is False and p.is_favourite is False]`.
3. Call `_release_pokemon_group(group, 'all')`.
4. Done.

### How it would help others
Well, first of all -- it would be quite nice feature on its own. Also it can solve problems like #4468 quite easily and it would prevent exceeding pokemon bag (which is possible with current configuration options) limits and some other nice features.

### PR DESCRIPTION
**Pull request by LitRidl**
## Closes #4552 , Resolves #4468 
Added keyword 'all' in 'release' config which allows to discards all pokemon in bag except N best. Updated docs and added commented examples in configs.

- "release": {"all": keep_best_cp": 100} globally keeps 100 best CP pokemon;
- fixed description of 'any' in docs and configs;
- added 'all' example in config files;
- added example of 'all' to docs;
- accidentally replaced some tabs in configs to spaces (but hey, that's good - spaces are everywhere in the project).

Changes in code are exactly as described in #4552 solution suggestion (refactored contents of `for` in a separate method and added 3 new lines, that's all).

### CODE REVIEW

**Comment by supercourgette** [comment]
Thanks for your commit. :)

English is not my first language, and I have some difficulty to understand the meaning of your PR (and your proposition in #4552). From my understanding, the actual configuration already allow to discard any Pokemons which does not met customs criteria, to only keep the N best.

In the documentation you said:

```
+```"release": {"any": {"keep_best_cp": 2}}```, ```"release": {"any": {"keep_best_cp": 10}}``` - can be any number. In the latter case for every pokemon type bot will keep no more that 10 best CP pokemon.
+
+If you wish to limit your pokemon bag as a whole, not type-wise, use `all`:
+```"release": {"all": {"keep_best_cp": 200}}```. In this case bot looks for 200 best CP pokemon in bag independently of their type. For example, if you have 150 Snorlax with 1500 CP and 100 Pidgeys with CP 100, bot will keep 150 Snorlax and 50 Pidgeys for a total of 200 best CP pokemon. 
```

For your example with the Snorlax, wouldn't the same output will be done with:

`release": {"any": {"keep_best_cp": 200}} ?`

Thanks you in advance for your explanation. :)

**Comment by LitRidl** [comment]
@supercourgette well, you think exactly as I did before I got into this problem. I though that keep with 'any' works by keeping N best pokemon in bag. But sadly, it doesn't: it tries to replicate deduplication mechanism from Necrobot. For example, if you have 50 pidgeys, 50 rattatas and 50 snorlax and run them through `"any": { "keep_best_cp": 10 }`, you will end up having 10 best pidgeys, 10 best rattatas and 10 best weedle.
If we use new 'all' instead of 'any' in this example we will have 10 global best pokemon no matter of what type. Maybe it would be 5 rattatas, 1 pidgey and 4 weedles -- who knows. Just 10 strongest in total, no more.

`_release_pokemon_get_groups(...)` called in `TransferPokemon.work` creates groups of duplicate pokemon (== pokemon of 1 type) and returns it. Filtering logic in `for` is applied always to 1 group. So, 'any' works by deleting worst duplicate pokemon and keeping only N best ones.

With `all` things are different: there is only 1 big group of all pokemon which gets filtered as a whole.

**Comment by solderzzc** [comment]
>This branch has conflicts that must be resolved
OOPs.

**Comment by LitRidl** [comment]
@solderzzc And what to do? When I published PR there were no conflict. Few hours later -- well, of course they happened to be ) If I will create new PR, time delays will be the same. So they will happen again?

**Comment by solderzzc** [comment]
@LitRidl  Since there're several PRs I merged before yours. You can just on your branch, run `git fetch`, `git merge origin/dev`, then solve the conflict.

**Comment by LitRidl** [comment]
@solderzzc If I try to pull/fetch from dev on my fork, I get "Already up-to-date"

**Comment by LitRidl** [comment]
@solderzzc fixed

**Comment by solderzzc** [comment]
Hmm, I haven't read the code carefully. The release task is out date since PokemonOptimizer did much better on XP.

**Comment by mjmadsen** [comment]
"any" is releasing all but the top as a whole. @solderzzc @LitRidl #4621

**Comment by LitRidl** [comment]
@mjmadsen Strange, how does it come that I have broken 'any'? Sorry, going to look for this

**Comment by mjmadsen** [comment]
@LitRidl Yeah, I haven't found it yet.

**Comment by LitRidl** [comment]
@mjmadsen I have found it -- if 'all' is not present in release config, it falls into 'any'. 'any' logics is organised as default value: if pokemon name is not found in release config, bot gets 'any'. And well, if someone haven't specified 'all'... 'any' runs on the whole pokemon bag :)
Will fix it in 5 minutes, should I open new PR?

**Comment by mjmadsen** [comment]
Yes please. Nice work!

**Comment by LitRidl** [comment]
I am really sorry. Should have tested it better.
I have created PR with fix, please check it. Don't want to break anything again

**Comment by mjmadsen** [comment]
No problem. It happens!

**Pull request merged**
