### PR TITLE
Fixes Windows Title Update

### PR DESCRIPTION
**Pull request by uzzle1987**
Fixes Windows Title Update
Should fix Issue:  #3464

### CODE REVIEW

**Comment by TheSavior** [comment]
Closing this in favor of https://github.com/PokemonGoF/PokemonGo-Bot/pull/3467

**Comment by Moonlight-Angel** [comment]
@TheSavior My PR doesn't fix this issue.

**Comment by uzzle1987** [comment]
@Moonlight-Angel can you add my litte line to your huge changes, which I also prefer.
It's just title vs. title.encode(), which is not changed in your request yet.
I tested this change on three Windows computers with four different players.

Before: Title was updated for me to: "1"
After: Title was updated to: "username | uptime | km walked ..."

Would be awsome if this find its way to the dev version in the long run :-)

**Comment by Moonlight-Angel** [comment]
@uzzle1987 Done. 👍

**Pull request closed without merging**
