### PR TITLE
Bulk Transfer

### PR DESCRIPTION
**Pull request by walaoaaa1234**
Bulk transfer for pokemon optimizer

### CODE REVIEW

**Comment by pogarek** [comment]
interesting. let's test it on dev before going to master

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
merged #5987

**Comment by pogarek** [comment]
sorry, It doesn't work:

```
[2017-03-31 17:01:58] [sentry.errors.uncaught] [ERROR] [u"NameError: global name 'transfer' is not defined", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 206, in main', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 785, in tick', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\pokemon_optimizer.py", line 243, in work', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\pokemon_optimizer.py", line 641, in apply_optimization', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\pokemon_optimizer.py", line 693, in transfer_pokemon']
Error in sys.exitfunc:
[2017-03-31 17:01:58] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'Queue' object has no attribute 'all_tasks_done'", u'  File "E:\\Poke\\Python27\\lib\\atexit.py", line 24, in _run_exitfuncs', u'  File "E:\\Poke\\Python27\\lib\\site-packages\\raven\\transport\\threaded.py", line 67, in main_thread_terminated', u'  File "E:\\Poke\\Python27\\lib\\site-packages\\raven\\transport\\threaded.py", line 98, in _timed_queue_join']
Traceback (most recent call last):
  File "E:\Poke\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 67, in main_thread_terminated
    if not self._timed_queue_join(initial_timeout):
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 98, in _timed_queue_join
    queue.all_tasks_done.acquire()
AttributeError: 'Queue' object has no attribute 'all_tasks_done'
```

**Comment by walaoaaa1234** [comment]
i missed something

**Pull request merged**
