### PR TITLE
Dump cells to enable more front-end features

### PR DESCRIPTION
**Pull request by Davideddu**
Short Description: 
It now dumps the cell list as a json into data/cells-$username.json, so that more front-ends can use this information (I'm working on a Kivy-based one).

### CODE REVIEW

**Comment by surfaace** [comment]
i assume cells becomes inactive after X amount of time, would i then suggest to add a checker to remove old cells during program execution

**Comment by Davideddu** [comment]
Cells are provided by the API, I assume the API knows better what cells are inactive. Also, by using this patch with my program, I can tell you that this happens, as new pokestops appear automatically and "used" ones get marked.

There's no need to do any check, and, anyways, it's not related to what this pull-request adds. It just dumps the existing in-memory information to disk for other programs to use.

By the way, this is the program that uses it: https://github.com/Davideddu/PokeVy

**Comment by solderzzc** [comment]
please sub pr to our dev branch, we need only PR to dev to make thing easy.
Let me close this one, waiting for PR on dev.

**Comment by Davideddu** [comment]
Okay, thank you. I see there have been a lot of changes, I'll read the code and re-implement it.

**Comment by Davideddu** [comment]
Submitted. #1019

**Pull request closed without merging**
