### PR TITLE
Do a Heartbeat even when a step was short

### PR DESCRIPTION
**Pull request by mhdasding**
Short Description: 
When you supply a path for the PathNavigator and the waypoints are too dense the web-location json won't be updated.

Fixes:
- Do a heartbeat even when the StepWalker made a short step

### CODE REVIEW

**Comment by douglascamata** [comment]
Is it really necessary?

**Comment by mhdasding** [comment]
i use 13.5 km/h walk speed which makes it a lot easier to get caught in that if statement and it won't update the web ui location never again when the waypoints are a bit dense. I don't see a reason not to do a heartbeat in thise case.

**Comment by douglascamata** [comment]
@mhdasding I have my speed set to 80 and I don't get any softban while botting.

**Comment by mhdasding** [comment]
@douglascamata surely you won't get softbanned for using 80 as speed, but i doubt your eggs are hatching while speeding like this.

But that's not the issue here, the issue is that the web ui does not update when using dense gpx paths. That's why i would like to add this heartbeat.

**Comment by douglascamata** [comment]
@mhdasding yes, they are.... because our speed is not m/s or km/h, it's an empirical number. We ALWAYS walks in small steps.

**Comment by douglascamata** [comment]
update_web_location is going away with the websocket events I'll implement tomorrow tho

**Comment by mhdasding** [comment]
Simple question then: do you want a heartbeat to happen on each bot.tick?

**Comment by douglascamata** [comment]
@mhdasding not at every tick, it's a waste of time

**Comment by mhdasding** [comment]
ok then this can be closed, i hope your websocket implementation will trigger the web location on each tick or at least with a lower boundary tick rate.

The info in pokecli.py line 201 
`"Walk instead of teleport with given speed (meters per second, e.g. 2.5)"`
might need to be updated if it's an empirical number.

**Pull request closed without merging**
