### PR TITLE
Pokemon Optimizer Improvements: buddy, evolve to final, evolve for xp

### PR DESCRIPTION
**Pull request by Anakin5**
- Add parameter to select next buddy based on criteria similar to evolve and upgrade
- Gather candies generated by buddy
- Add `candy`, `candy_to_evolution` and `evolution_cost` criteria to help in the selection of next buddy. They can also be used for keep, evolve and upgrade.
- Add `max_cp` criteria
- Add possibility to reverse sort a criteria: `candy` = from highest to lowest, `-candy` = from lowest to highest.
- Support list of Pokemon in `evolve_for_xp` parameter (read the doc !)
- Support `evolve_to_final` parameter (read the doc !)
- Rescale upgrade from 1-80 to 1-40
- Update doc
- Update config example
- Other: move `transfer_wait_min` and `transfer_wait_max` to `action_wait_min` and `action_wait_max` since the timer is used for all actions in inventory.

#4693 #5188 #5390

### CODE REVIEW

**Comment by solderzzc** [comment]
Are you sure we want to use new feature on old API version?

**Comment by Anakin5** [comment]
I guess we have to use the most recent version of the API .

**Comment by DeXtroTip** [comment]
It's also needed to add the buddy distance for each pokemon at `pokemon.json`. I've already done that and can give it to you.
I'm working on a buddy task too and I might still make a PR since not everyone uses PokemonOptimizer, I think.

**Comment by solderzzc** [comment]
PokemonOptimizer is my main pokemon maintain task, it's very helpful.

**Comment by Anakin5** [comment]
I added the distances in the file. Cannot see it in the review because too big but it's there.

**Comment by solderzzc** [comment]
👍  The feature list is really good. Haven't go deeply into the code.

**Comment by YvesHenri** [comment]
I dont use optimizer. Too lazy to set it up and the last and only time I did, it released all my 7 100% snorlaxes rofl

**Comment by Anakin5** [comment]
Anyone to approve ?

**Comment by solderzzc** [comment]
👍

**Pull request merged**
