### PR TITLE
Small telegram fixes

### PR DESCRIPTION
**Pull request by javajohnHub**
Fixed output and removed the displaying of +100 stardust every catch

fixed daily_catch_limit

### CODE REVIEW

**Comment by Gobberwart** [comment]
@DBa2016 Likely because it's always 100?

**Comment by DBa2016** [comment]
It's the same for EXP (more or less).

**Comment by javajohnHub** [comment]
Yes its always 100. Unlike exp wich have bonuses.


Sent from my Sprint Samsung Galaxy Note5.
-------- Original message --------From: Stuart Travers <notifications@github.com> Date: 9/25/16  8:13 PM  (GMT-05:00) To: PokemonGoF/PokemonGo-Bot <PokemonGo-Bot@noreply.github.com> Cc: John Edwards <joedw1978@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [PokemonGoF/PokemonGo-Bot] Small telegram fixes (#5675) 
@DBa2016 Likely because it's always 100?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PokemonGoF/PokemonGo-Bot","title":"PokemonGoF/PokemonGo-Bot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PokemonGoF/PokemonGo-Bot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Gobberwart in #5675: @DBa2016 Likely because it's always 100?"}],"action":{"name":"View Pull Request","url":"https://github.com/PokemonGoF/PokemonGo-Bot/pull/5675#issuecomment-249455867"}}}

**Comment by Gobberwart** [comment]
Yeah if it's ALWAYS 100, then whatev.

**Pull request closed without merging**
