### PR TITLE
Fix no ncp config in vips config

### PR DESCRIPTION
**Pull request by thuydx55**
Fix:
- Bot always considers all pokemons as vip

### CODE REVIEW

**Comment by Anakin5** [comment]
It does not look like a fix, more like hiding it I would say. People can still remove ncp from their config if they want.

**Comment by alexyaoyang** [comment]
I agree, this is more of a workaround.

**Comment by Gobberwart** [comment]
It's also not correct...

My config:
`"any": {"catch_above_cp": 1500, "catch_above_iv": 0.9, "logic": "or" },`

Result:
```
[2016-09-21 21:35:11] [MoveToFort] [INFO] Moving towards pokestop Australia Post Collins Street - 0.06km
[2016-09-21 21:35:14] [PokemonCatchWorker] [INFO] *A wild Poliwag appeared!* (CP: 608) (NCP: 0.76) (Potential 0.51) (A/D/S 13/1/9)
[2016-09-21 21:35:25] [PokemonCatchWorker] [INFO] Great throw! Used Ultraball, with chance 47.20 (4 left)
[2016-09-21 21:35:25] [PokemonCatchWorker] [INFO] Captured Poliwag! [CP 608] [NCP 0.76] [Potential 0.51] [13/1/9] (214/800) [+150 exp] [+100 stardust]
[2016-09-21 21:35:26] [PokemonCatchWorker] [INFO] You now have 27 Poliwag candy!
```

No ncp in config, no incorrect VIPs.

**Comment by Gobberwart** [comment]
This issue was fixed recently and since then I've seen no evidence of anyone using the up-to-date dev branch who is still experiencing it.

**Comment by Gobberwart** [comment]
Closing this as it achieves nothing useful.

**Pull request closed without merging**
