### PR TITLE
Added only_catch_better_iv and only_catch_better_cp 

### PR DESCRIPTION
**Pull request by davidakachaos**
Added ability for the bot to do a basic check if a Pokemon to be caught is a higher IV or CP than the one we have (highest one we have) and see if we need to try and catch it.

### CODE REVIEW

**Comment by MerlionRock** [comment]
I don't understand the need of this... Just catch... Can earn some stardust... Later use optimizer to release... This sound redundant....

**Comment by davidakachaos** [comment]
Agreed, but look at #6154 why someone wants to change catch parameters all the time

**Comment by Jcolomar** [comment]
this is better than #6154

**Comment by Jcolomar** [comment]
works only around IV and CP, but only see pokemon_id? or also family_id?

**Comment by goedzo** [comment]
I am not liking the way this is coded:

if pokemon_config.get('only_catch_better_cp', False):

This will fail if the key is missing in json. So we need to avoid config fails whenever something new is added. Please default the values and allow the key not to be in config.

**Comment by davidakachaos** [comment]
> This will fail if the key is missing in json.
It doesn't with me? I believe I provide a default value with the False here, so if no value found it will default to False?

**Comment by davidakachaos** [comment]
@Jcolomar it works based on a Pokemon, not on a family of Pokemon, so no family_id

**Comment by goedzo** [comment]
@davidakachaos sorry missed the false there :).

**Comment by Jcolomar** [comment]
@davidakachaos so u need a rule for each pokemon...

**Comment by davidakachaos** [comment]
Yes, I mean this rule isn't for every Pokémon? Like the candy rule, it
works like that, so it checks the Pokémon about to be caught versus the
rule(s) matched, so it would be able to match multiple Pokémon?

Op 1 aug. 2017 14:38 schreef "Jhero" <notifications@github.com>:

**Comment by solderzzc** [comment]
@davidakachaos @Jcolomar You want to merge this pr?

**Comment by Jcolomar** [comment]
Ya np. We kept opened but @davidakachaos is in vacation.

**Pull request merged**
