### PR TITLE
Add ColoredLoggingHandler

### PR DESCRIPTION
**Pull request by eevee-github**
Short Description: 
---
- ColoredLoggingHandler class added to `pokemongo_bot/event_handlers/` which looks like:
 colored-log
- Add config key `logging_color` to enable colorized logging.
 - If set to `"logging_color": true`, ColoredLoggingHandler will be used.

Fixes:
---
- Current logging style is a bit uncomfortable for human.

Edit:
---
- Config name has been changed during review

### CODE REVIEW

**Comment by Jamezin** [comment]
For some reason cant import module fcntl

`  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "C:\Users\Jamezin\Desktop\Pokemon Go Bot\pokemongo_bot\__init__.py", line 26, in <module>
    from pokemongo_bot.event_handlers import LoggingHandler, SocketIoHandler, ColoredLoggingHandler
  File "C:\Users\Jamezin\Desktop\Pokemon Go Bot\pokemongo_bot\event_handlers\__init__.py", line 3, in <module>
    from colored_logging_handler import ColoredLoggingHandler
  File "C:\Users\Jamezin\Desktop\Pokemon Go Bot\pokemongo_bot\event_handlers\colored_logging_handler.py", line 6, in <module>
    import fcntl
ImportError: No module named fcntl`

**Comment by eevee-github** [comment]
@Jamezin Thank you for testing! I'm working to fix that.

**Comment by Jamezin** [comment]
You can get rid of 
`import fcntl`
and then add this to colored_logging_handler.py
`def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""`
But then you will get import error for 'Termios'

**Comment by eevee-github** [comment]
* Fixed `fcntl` and `termios` issue on Windows. I've tested this on Windows10
* Rebased to latest `dev`

**Comment by Nihisil** [comment]
This one looks really nice for me! I would like to have it merged 👍

**Comment by eevee-github** [comment]
I know there already exists a PR (https://github.com/PokemonGoF/PokemonGo-Bot/pull/2604) about color logging.
I'm sorry for PR duplication... :pray:

**Comment by solderzzc** [comment]
Yes,seems we need merge https://github.com/PokemonGoF/PokemonGo-Bot/pull/2604 ...

**Comment by Nihisil** [comment]
This PR looks better for me than #2604 because of modular structure

**Comment by TheSavior** [comment]
@douglascamata can you review this? It looks like this is a great approach of the structure I was talking about in the other colored logging PR.

**Comment by renatorib** [comment]
Need to merge! Awesome

**Comment by eevee-github** [comment]
I've found some events has not been colorized yet (eg. `pokemon_capture_failed`, `no_pokeballs`, etc).
I'm working to fix this.

**Comment by douglascamata** [comment]
@eevee-github the socketio event handler should be added if, and only if, websocket server url is set in the config. There's no need to add an additional configuration for the socketio handler itself.

Can you just keep the specific logging handler configuration? Like:

```
"logging_color": true
```

**Comment by eevee-github** [comment]
@douglascamata Thanks for reviewing this PR!
I'm working to remove `"event_handlers": [...]` config, and add `"logging_color": true`.
So, `PokemonGoBot#_setup_event_system` will be:
```python
    def _setup_event_system(self):
        handlers = []
        if self.config.logging_color:
            handlers.append(ColoredLoggingHandler())
        else:
            handlers.append(LoggingHandler())

        if self.config.websocket_server_url:
            if self.config.websocket_start_embedded_server:
                self.sio_runner = SocketIoRunner(self.config.websocket_server_url)
                self.sio_runner.start_listening_async()

            websocket_handler = SocketIoHandler(
                self,
                self.config.websocket_server_url
            )
            handlers.append(websocket_handler)

            if self.config.websocket_remote_control:
                remote_control = WebsocketRemoteControl(self).start()

        self.event_manager = EventManager(*handlers)
        self._register_events()
        if self.config.show_events:
            self.event_manager.event_report()
            sys.exit(1)
```

Is this OK?

**Comment by ulovehash** [comment]
eevee-github, Could u pls show an example of adding this config to config.json?

**Comment by douglascamata** [comment]
@eevee-github LGTM.

**Comment by eevee-github** [comment]
@douglascamata Thanks!
* Updated the config key (remove `config.event_handlers`, and add `config.logging_color`)
 * Tested for several minutes in both cases: `logging_color` = `true` and `false`, and looks good for me.
* Rebased to latest `dev`

**Comment by eevee-github** [comment]
@ulovehash You can see example of config here: `configs/config.json.example`.
Just add `"logging_color": true,` to your `config.json`.

**Comment by TCB13** [comment]
The reason why we've so many color log PRs is because someone it holding back on this basic feature. Please merge this, we always had that and we need it. What's the problem now?

**Comment by ulovehash** [comment]
@eevee-github i did it, but nothing changed

**Comment by eevee-github** [comment]
@ulovehash Can you use `git`?

**Comment by ulovehash** [comment]
@eevee-github here is my config

 "tasks": [
	    {
	      "type": "CollectLevelUpReward"
	    },
	    {
	      "type": "IncubateEggs",
	      "config": {
	        "longer_eggs_first": true
	      }
	    },
	    {
	      "type": "RecycleItems",
	      "config": {
	        "run_interval": 60,
	        "item_filter": {
	          "Pokeball": {
	            "keep": 70
	          },
	          "Greatball": {
	            "keep": 70
	          },
	          "Ultraball": {
	            "keep": 70
	          },
	          "Masterball": {
	            "keep": 70
	          },
	          "Potion": {
	            "keep": 0
	          },
	          "Super Potion": {
	            "keep": 0
	          },
	          "Hyper Potion": {
	            "keep": 0
	          },
	          "Max Potion": {
	            "keep": 0
	          },
	          "Revive": {
	            "keep": 0
	          },
	          "Max Revive": {
	            "keep": 30
	          },
	          "Razz Berry": {
	            "keep": 70
	          }
	        }
	      }
	    },
	    {
	      "type": "EvolvePokemon",
	      "config": {
	        "evolve_all": "Pidgey,Rattata,Zubat,Weedle,Drowzee,Spearow,Venonat,Caterpie,Krabby,Paras,Jigglypuff,Sandshrew,Vulpix,Meowth,Psyduck,Mankey,Tentacool,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Voltorb,Horsea,Goldeen,Staryu,Ekans",
	        "first_evolve_by": "cp",
	        "evolve_above_cp": 0,
	        "evolve_above_iv": 0,
	        "logic": "or",
	        "evolve_speed": 1,
	        "use_lucky_egg": false,
	        "run_interval": 180
	      }
	    },
	    {
	      "type": "TransferPokemon",
	      "config": {
	        "run_interval": 180
	      }
	    },
	    {
	      "type": "MoveToFort",
	      "config": {
	        "lure_attraction": true,
	        "lure_max_distance": 2000,
	        "ignore_item_count": true
	      }
	    },
	    {
	      "type": "SpinFort",
	      "config": {
	        "ignore_item_count": true
	      }
	    },
	    {
	      "type": "CatchVisiblePokemon"
	    },
	    {
	      "type": "CatchLuredPokemon"
	    }
	  ],
	  "map_object_cache_time": 5,
	  "forts": {
	    "avoid_circles": true,
	    "max_circle_size": 500
	  },
	  "websocket_server": false,
	  "logging_color": true,
	  "logging_color": true, 
	  "walk": 80,
	  "action_wait_min": 0,
	  "action_wait_max": 1,
	  "debug": false,
	  "test": false,
	  "health_record": false,
	  "location_cache": false,
	  "distance_unit": "m",
	  "reconnecting_timeout": 15,
	  "evolve_captured": "NONE",
	  "catch_randomize_reticle_factor": 1.0,
	  "catch_randomize_spin_factor": 1.0,
	  "catch": {
	    "any": {
	      "always_catch": true
	    }
	  },
	  "release": {
	    "any": {
	      "keep_best_iv": 1
	    },
	    "Moltres": {
	      "keep_best_iv": 3
	    },
	    "Zapdos": {
	      "keep_best_iv": 3
	    },
	    "Articuno": {
	      "keep_best_iv": 3
	    },
	    "Mewtwo": {
	      "keep_best_iv": 3
	    },
	    "Dragonite": {
	      "keep_best_iv": 3
	    },
	    "Dratini": {
	      "keep_best_iv": 3
	    },
	    "Dragonair": {
	      "keep_best_iv": 3
	    },
	    "Snorlax": {
	      "keep_best_iv": 3
	    }
	  },
	  "vips": {
	    "any": {
	      "catch_above_cp": 1200,
	      "catch_above_iv": 0.9,
	      "logic": "or"
	    },
	    "Lapras": {},
	    "Moltres": {},
	    "Zapdos": {},
	    "Articuno": {},
	    "Mewtwo": {},
	    "Dragonite": {},
	    "Snorlax": {},
	    "Mew": {},
	    "Arcanine": {},
	    "Vaporeon": {},
	    "Gyarados": {},
	    "Exeggutor": {},
	    "Muk": {},
	    "Weezing": {},
	    "Flareon": {}
	  }
	}

**Comment by eevee-github** [comment]
@ulovehash OK, I would like to recommend you to wait until this PR is merged. This feature (colorized logging) is not available at this time.

**Comment by ulovehash** [comment]
@eevee-github ok, thx

**Comment by douglascamata** [comment]
@TCB13 it's a basic feature that needs to be designed correctly and only me and @TheSavior are actively reviewing PRs and looking to keep the best architecture for the bot. We both have a life outside the bot and also jobs, so time is short and there are much more important stuff to merge that makes a real difference and not only turns your log output into a rainbow. I would like to remember that having colors is a PLUS, because logs aren't colored by default in any software and logs also doesn't need to a story that a 7 years old child can read. Please, think a bit before saying stuff like this otherwise I need to be ignorant like now.

**Comment by douglascamata** [comment]
@eevee-github after work I'll have a look and merge, thx!

**Comment by eevee-github** [comment]
- Rebased to latest `dev`

**Comment by eevee-github** [comment]
- Updated `CONTRIBUTORS.md`

**Comment by douglascamata** [comment]
@eevee-github yet one more time, merge conflicts... sorry :/

**Comment by nanogirl21** [comment]
@Nihisil  How do I apply your color scheme above to my files?

**Comment by jomarocas** [comment]
Testing with
git fetch origin pull/2889/head:colored-log
git checkout colored-log 

and later in my config


    "logging_color": true,

but no working? any suggestion

os: ubuntu 16.04

**Comment by zx900930** [comment]
merge conflicts with dev commit b94d369 ("Log stats on terminal (#3312)", 2016-08-09)
```
$ git pull
Removing setup.py
Auto-merging pokemongo_bot/cell_workers/transfer_pokemon.py
Auto-merging pokemongo_bot/cell_workers/recycle_items.py
CONFLICT (content): Merge conflict in pokemongo_bot/cell_workers/recycle_items.py
Auto-merging pokemongo_bot/cell_workers/nickname_pokemon.py
Auto-merging pokemongo_bot/cell_workers/incubate_eggs.py
Auto-merging pokemongo_bot/cell_workers/evolve_pokemon.py
Auto-merging pokemongo_bot/cell_workers/catch_visible_pokemon.py
CONFLICT (content): Merge conflict in pokemongo_bot/cell_workers/catch_visible_pokemon.py
Auto-merging pokemongo_bot/cell_workers/catch_lured_pokemon.py
CONFLICT (content): Merge conflict in pokemongo_bot/cell_workers/catch_lured_pokemon.py
Auto-merging pokemongo_bot/__init__.py
CONFLICT (content): Merge conflict in pokemongo_bot/__init__.py
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by eevee-github** [comment]
* Rebased to `dev`, again

**Comment by eevee-github** [comment]
Thanks! 🎉

**Comment by FilipePedro** [comment]
thanks man :)

**Comment by FilipePedro** [comment]
thanks man :)

**Comment by sergiopalacio** [comment]
On which terminal did you test this on windows10? Can't get this working on git bash. Trying to download the new windows bash beta to test..

**Comment by eevee-github** [comment]
It seems all color codes for `print` or `sys.stdout.write` don't work after `colorama.init()` called (in `cell_workers/utils.py`), under Windows `mintty` terminal.

@sergiopalacio I had tested this on standard `cmd`. Thank you for reporting an issue. Anyway, could you please create a new issue for this? (because this PR had been already closed)

**Comment by eevee-github** [comment]
@sergiopalacio Could you try this? `winpty python pokecli.py --config ...`
This works good for me, on Windows 10 Git Bash.

After some investigations, I've found that there is known issue about Git Bash MinTTY:
https://github.com/git-for-windows/build-extra/blob/43d672f/installer/ReleaseNotes.md#known-issues

**Comment by ulovehash** [comment]
Are there any other options to make logs colored on osX?

**Comment by mvolli** [comment]
@eevee-github `winpty ....` works

**Comment by jomarocas** [comment]
yes no the latest commit working for me apply python poke ... in ubuntu 16.04 and terminator

**Comment by ryanb93** [comment]
This doesn't preserve the debug level, so everything get's printed.

**Pull request merged**
