### PR TITLE
Added PR tutorial in readme

### PR DESCRIPTION
**Pull request by alexyaoyang**
## Fixes/Resolves/Closes (please use correct syntax):
- Facilitates first time git(hub) users
- Improve PR quality (and in turn repo quality)

### CODE REVIEW

**Comment by javajohnHub** [comment]
Thank you for this.

**Comment by k4n30** [comment]
Looks good to me

**Comment by alexyaoyang** [comment]
@k4n30 Start your comment with a 👍 so pullapprove goes through :)

**Comment by solderzzc** [comment]
👍  nice, better have a `don't delete, please rename only` :)

**Comment by k4n30** [comment]
@alexyaoyang i'm not part of a team with pull approval rights :(

**Comment by alexyaoyang** [comment]
@k4n30 Wut! Really? Unfortunately I don't have the rights to give you that right too :(

**Pull request merged**
