### PR TITLE
Sniper fixes

### PR DESCRIPTION
**Pull request by davidakachaos**
## Short Description:
Fixes for these issues I noticed:
- Fixes an issue with [a source](http://pokedex100.com/tie9/data/) hiding latitude and longitude of Pokemons when using it without a subscription.
- Also converts IV to float instead of an integer. Some sites use IVs like 96.7
- Adds a cooldown to sniping, to prevent Niantic from seeing you [jumping all over the world](https://www.youtube.com/watch?v=ZrPaEUjtYvQ) :smile:
- Fixes an logic issue, where sniper would snipe Pokemon below the special IV instead of that and above.

selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by MerlionRock** [comment]
Wondering how does cool down prevent Niantic not seeing you jumping around the world.... Lol....

**Comment by davidakachaos** [comment]
It was an idea I had; after sniping Niantic might "flag" an account to be more closely monitored. Nothing based on proof, just feeling lke something I would do when I was combatting bots...
And no, it wouldn't prevent it, but it does screw with a detecting strat to see if some accounts are sniping...
I would be happy to remove the cooldown if you think it has no use at all 😉

**Comment by pogarek** [comment]
I think it would be good to expose cooldown to config.json , with default behavior like it was before the PR. :) Plus, of course, a proper modification to sample config and docs :)

**Comment by davidakachaos** [comment]
@pogarek Done 😉

**Comment by pogarek** [comment]
👍 
let's test it out on dev :) However I'll stick with my current config. Works for a last few months :-P

**Comment by pogarek** [comment]
merged #5962

**Pull request merged**
