### PR TITLE
Telegram refactor

### PR DESCRIPTION
**Pull request by javajohnHub**
Last try.

### CODE REVIEW

**Comment by javajohnHub** [comment]
Travis failing with:
The command "conda install -y protobuf pylint -q" failed and exited with 1 during .

**Comment by solderzzc** [comment]
Is this woking ??

**Comment by javajohnHub** [comment]
Yes.

**Comment by solderzzc** [comment]
👍  Nice

**Comment by javajohnHub** [comment]
I can no longer merge so some else will need to.

**Pull request merged**
