### PR TITLE
Full API Support for 0.67.2 based on latest compile from POGOProtos

### LINKED ISSUE #6075: 0.67.2
I know bossland/PokeFarmer has had all sorts of problems with capacity/authentication etc so haven't been focusing on the new API, I read a comment saying that even through the API has progressed form 0.67.1 the old endpoint can still be used, does anyone know if this is correct? 

No longer use the bot for catching, just sorting/mass evolving and wanted to know how "safe" it is

### PR DESCRIPTION
**Pull request by goedzo**
Recompiled latest https://github.com/AeonLucid/POGOProtos API and added to my own maintained repository.

fixes #6075

### CODE REVIEW

**Comment by MerlionRock** [comment]
Can don't merge this first? Can we discuss this issue in discord?

**Comment by Jcolomar** [comment]
Full explanation of the changes, and why we should use ur pogoapi repo instead official one

**Comment by goedzo** [comment]
@Jcolomar the reason for this change is that the original api decided to remove calls from protos. So they did not compile all proto files. Their argument for that is, that they will never support gyms hence removing those calls within the compilation. This resulted in numerous forks of the api and just recompiling protos again. So is this fork, that exposes the full protos methods.

**Comment by Jcolomar** [comment]
Ty for explanation

**Comment by goedzo** [comment]
Based on the discussion discord with @MerlionRock and @davidakachaos  I think we can conclude that this pull request can go-on for now, so that we are fully compatible with the 0.67.2 API in the bot. Whenever the API is updated, we can always discuss again on how to proceed and what to implement / leave out.

**Comment by davidakachaos** [comment]
wut? How did this get merged? Looking into it, sorry people...

**Comment by davidakachaos** [comment]
@goedzo this PR got automaticly closed because you included in part in your other PR...
This change (changing the API to your fork of it) is [NOT in dev](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/requirements.txt) as far as I can see.
Github didn't understand the history or something. Anyway, this change is not in the codebase for now.
Could you open a new PR for this?
And if you want to develop a new feature, be sure to branch of the dev branch for each new feature. Else git we are forced to leave you PRs open until the previous one is merged.

**Comment by goedzo** [comment]
@davidakachaos, recreated it here: https://github.com/PokemonGoF/PokemonGo-Bot/pull/6088

**Pull request merged**
