### PR TITLE
Added Incense to telegram

### PR DESCRIPTION
**Pull request by TheCannings**
## Short Description:

Added Use incense functionality to the telegram worker

### CODE REVIEW

**Comment by MerlionRock** [comment]
👍

**Comment by davidakachaos** [comment]
Thanks for you PR 😄 
Have you also a solution for #6129 ? And does the bot catch Pokemon attracted to incense?

**Comment by MerlionRock** [comment]
Congrats on your 1st PR :)

**Comment by TheCannings** [comment]
@davidakachaos working on the incense bit at the moment, from what i'm finding out the whole applied_items bit is borked though I keep having to dig deeper

**Comment by davidakachaos** [comment]
@TheCannings okay, good work! Thanks for looking into that!

**Pull request merged**
