### PR TITLE
Fix the teleporting on web ui

### PR DESCRIPTION
**Pull request by heihachi**
Short Description: 
Line of code that shouldn't be there since web location updates every tick
Fixes:
- teleporting on web ui

### CODE REVIEW

**Comment by douglascamata** [comment]
@Reaver01 have a look, please. I also don't think that code line should be there, but I let you decide because you work on web ui.

**Comment by heihachi** [comment]
@douglascamata dont tell anyone but i added that in https://github.com/PokemonGoF/PokemonGo-Bot/pull/800 by accident lol though been for others to pitch in as well

**Comment by surfaace** [comment]
This can be applied safly after reviewing @heihachi last comment

**Comment by surfaace** [comment]
@heihachi can you review this and say if we will need to remove this line: https://github.com/PokemonGoF/PokemonGo-Bot/commit/ff50e37ad8053d22bf7bbb1ffe02661979285880#diff-a8e82d1c2066f1b62d2f396a4e0e585bL119

**Comment by heihachi** [comment]
@surfaace if its in the heartbeat function the only other place that needs it is the _setup_api function so i would say it doesn't need it.

**Comment by surfaace** [comment]
tracked in #1074 that doesnt have merge conflicts

**Comment by heihachi** [comment]
i will eventually have a pr with .vscode ignored lol

**Pull request closed without merging**
