### PR TITLE
Quick fix for no_pokeball infinite loop

### PR DESCRIPTION
**Pull request by umbreon222**
## Short Description:
check for no available pokeballs before trying to catch it.

## Fixes (provide links to github issues if you can):
-#[3449](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3449)
-#[3215](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3215)

### CODE REVIEW

**Comment by cmezh** [comment]
You made PR to master branch., not dev.

**Comment by GitPupper** [comment]
@cmezh He submitted a PR from *his* forked repo's *master* branch, to *this* repo's *dev* branch. You might've read that wrong buddy 👍

**Comment by cmezh** [comment]
@GitPupper Look at files changed.

**Comment by umbreon222** [comment]
[See](https://github.com/PokemonGoF/PokemonGo-Bot/pull/3517)

**Pull request closed without merging**
