### PR TITLE
Updated docs for MoveToMap

### PR DESCRIPTION
**Pull request by DBa2016**
As mentioned in PR#4937, udpated configuration_files.md

### CODE REVIEW

**Comment by Jasperrr91** [comment]
@DBa2016 you messed up the logic in the move_to_map_pokemon. Can you please change it back from:
`if pokemon['dist'] > self.config['max_distance'] and not self.config['snipe']:`

To
` if pokemon['dist'] > self.config['max_distance'] or not self.config['snipe']:`

**Comment by solderzzc** [comment]
The real confusing if comes from the meaning of 'max_distance'. 
It should be split into two config fields:
'max_walk_distance' and 'max_snip_distance', otherwise, no mater how to change, all can't be on the same page.

**Comment by Jasperrr91** [comment]
Indeed, the naming of the field is causing the confusion. It should indeed
be renamed to max_snip_distance. Not sure if we need the max_walk_distance
since after this if statement, there's logic that checks if the distance is
walkable right?

Op woensdag 31 augustus 2016 heeft Simba Zhang <notifications@github.com>
het volgende geschreven:

**Comment by solderzzc** [comment]
@Jasperrr91  Some scary guys want to disable the snipe but only set the bot on the popular location or several bots together as cluster, walk to the location reported by map/others if possible(there's code to calc if have enough time).

**Comment by DBa2016** [comment]
I agree the field should be renamed to "max_snip**e**_distance", however this particular PR is about doc changes only.

**Comment by Jasperrr91** [comment]
I'll put in that PR when I get back to my computer. I had to hijack this PR
as you don't respond to the relevant PR's and you keep blatantly changing
the logic back to AND.

Op woensdag 31 augustus 2016 heeft DBa2016 <notifications@github.com> het
volgende geschreven:

**Comment by Jasperrr91** [comment]
Thereby breaking the bot.

Op woensdag 31 augustus 2016 heeft Jasper van der stoop <
jasper@vanderstoop.nl> het volgende geschreven:

**Comment by DBa2016** [comment]
@Jasperrr91 : there is a reason why a PR needs an approval... If you think a PR breaks the logic - don't approve it. Also - please help me understand the "you don't respond to relevant PRs" statement.

**Comment by mjmadsen** [comment]
@Jasperrr91 Sorry I merged the other and missed the problem!

**Comment by Jasperrr91** [comment]
@DBa2016 the 'breaking' PR https://github.com/PokemonGoF/PokemonGo-Bot/pull/4860 was approved within 10 mins so I hadn't seen it. 

I was referring to https://github.com/PokemonGoF/PokemonGo-Bot/pull/4855 which refers back to https://github.com/PokemonGoF/PokemonGo-Bot/pull/4772. In there I wrote down that the `AND NOT` statement breaks the bot and should be `OR NOT`. Although there's a better solution, working on that now.

@mjmadsen no problem! Those things can happen ^^

**Comment by DBa2016** [comment]
@Jasperrr91 : by all means, I am not following the comments on a PR after it has been closed, I just don't have time for this. So yes, shame on me, I did not realize that "max distance" was in fact meaning "max_sniping_distance", I took it for "max visibility" or something similar.

**Comment by Jasperrr91** [comment]
@DBa2016 no problem, glad that you realise it now. I'm putting out a PR in a few mins.

**Comment by mjmadsen** [comment]
As we've lost some of our original devs, I hope we don't have any bad blood here. We need every programmer we can get our hands on. What I think we can take away is that we should try to clear up variable name conventions to resolve ambiguity. Second, we should be more proactive in commenting our code (it always seems obvious to the person writing it). Third, I'll let PRs sit around a bit longer before merging them - especially for files I do not know thoroughly. 

Aside from that, shall we rebase/merge dev and update our md? :)

**Comment by solderzzc** [comment]
@mjmadsen  how to make good crowd fund organized ? https://github.com/WhisperSystems/Signal-Android#contributing-code  setup a good example.

**Comment by mjmadsen** [comment]
There are a variety of sites to do such things. Beforehand, though, we need to figure out how we'd decide whom gets what, based on some metrics and "position", and how we'd distribute those funds.

**Comment by solderzzc** [comment]
that's the hardest part here. We shouldn't discuss it publicly.

**Comment by mjmadsen** [comment]
@solderzzc I'm going to delete our conversation. Let's establish a dialog elsewhere.

**Comment by solderzzc** [comment]
@mjmadsen  do you have Skype? mine is solderzzc.

**Comment by mjmadsen** [comment]
I'm unable to skype right now. But I'll contact you at some point. If any of the other devs in the chain saw our discussion, would you mind communicating with @solderzzc if he's able and willing? Might help kick us to the next level.

**Comment by solderzzc** [comment]
@mjmadsen  you can also ping me in the slack. The original team had conversation, but keep no profit at the time.

**Comment by DBa2016** [comment]
This is a trivial change for the docs. Is there any reason not to approve it? It prevents me from doing more important stuff.

**Comment by DBa2016** [comment]
Oh, and since we are at it... Any reason #4951 was approved and merged though it is breaking the bot's functionality without anyone giving the contributor hard time?
I cannot even fix it because my repository is being held hostage here.

**Comment by Jasperrr91** [comment]
Sorry if I offended you @DBa2016, I was just a little bit annoyed that the max_distance logic was broken twice after I fixed it. I have not yet looked into the whole Telegram function but if that PR break it, that's indeed not good.

A tip for the future, you can rebranch and work on new fixes while your old PR's remain active in here. I'll merge this PR right away.

**Comment by Jasperrr91** [comment]
@mjmadsen sounds good! I'll work on adding comments to the code and enforcing DRY. Leaving PR's open a little longer also sounds like a good idea 👍

**Pull request merged**
