### PR TITLE
Show pokemon moves when catching

### PR DESCRIPTION
**Pull request by iananass**
Example:
A Wild Staryu appeared! [CP 515] [Potential 0.67] [Quick Attack(7.51 DPS)] [Power Gem(13.79 DPS)]

Fast moves: http://onlinefanatic.com/pokemon-go-normal-move-list/
Charged moves: http://onlinefanatic.com/pokemon-go-charge-move-list/

### CODE REVIEW

**Comment by TheSavior** [comment]
Why is this important? It doesn't effect the bot catching it, right?

**Comment by Nihisil** [comment]
I think this PR is allow to see pokemon attacks, the first and the second with dps. It can be useful to know what is attack dps for your pokemon, when you will fight a gym in real life, but maybe it should be added to the web version?

**Comment by kanemasa1987** [comment]
It should be useful for rename/transfer/gym battles in the future.

**Comment by Nihisil** [comment]
@kanemasa1987 gym battles will not be implemented in this bot

**Comment by kanemasa1987** [comment]
oh, then maybe rename and transfer decision making etc.

**Comment by iananass** [comment]
This feature have is only UI. I think that DPS is very important
As written above in future it could be very useful into transfer decision making. Because pokemon with low CP you can always power up and get strong pokemon. You can do nothing with pokemon which have weak attack to make it strong.

**Comment by TheSavior** [comment]
I don't think changing the log really matters, people are unlikely to see something show up in there log and manually do something with that pokemon. I actually think it is a negative change to the current log statement as it doesn't matter to anyone when catching pokemon.

I do think have the JSON blob is valuable for other workers like transferring or evolving pokemon. I'd be happy to merge that JSON blob so that we can find a more positive way to use this data.

My preference would be for us to not change the log message on catch from where it is now though.

**Comment by Nihisil** [comment]
In the current dev version we have information about pokemon moves inside Pokemon object.

So, if you want to print it when you catch a pokemon, you can do it easily with a new PR.

**Pull request closed without merging**
