### PR TITLE
Upgraded to 0.69.1 api

### PR DESCRIPTION
**Pull request by goedzo**
Note: Version number is updated to 2.13.0 to be in synch with protos version number. 

We are following [semantic versioning](http://semver.org/) for POGOProtos.  Every version will be mapped to their current PokémonGo version.

| Version      | Android       | iOS           | Extra                     |
|--------------|---------------|---------------|---------------------------|
| 2.13.0       | 0.69.1        | 1.39.1        |                           |
| 2.12.0       | 0.69.0        | 1.39.0        |                           |
| 2.11.0       | 0.67.2        | 1.37.2        |                           |
| 2.11.0-beta  | 0.67.1        | 1.37.1        |                           |
| 2.10.x       | 0.63.1        | 1.33.1        |                           |
| 2.9.2        | 0.61.0        | 1.31.0        | Updated protobuf to 3.3.0 |
| 2.9.1        | 0.61.0        | 1.31.0        | Updated protobuf to 3.2.0 |
| 2.9.0        | 0.61.0        | 1.31.0        |                           |
| 2.8.0        | 0.59.1        | 1.29.1        |                           |
| 2.7.0        | 0.57.2        | 1.27.2        |                           |
| 2.6.x        | 0.55.0        | 1.25.0        |                           |
| 2.5.x        | 0.53.1        | 1.23.1        |                           |
| 2.4.x        | 0.51.0        | 1.21.0        |                           |
| 2.3.0        | 0.49.1        | 1.19.1        |                           |
| 2.2.0        | 0.47.1        | 1.17.0        |                           |
| 2.1.0        | 0.45.0        | 1.15.0        |                           |
| 2.1.0-beta   | 0.45.0        | 1.15.0        |                           |
| 2.0.x        | 0.43.4        | 1.13.4        |                           |

### CODE REVIEW

**Comment by davidakachaos** [comment]
👍

**Comment by MerlionRock** [comment]
Those who are on master will get affected again... Can we think of a solution that doesn't affect those on master?

**Comment by Jcolomar** [comment]
can we revert?

**Comment by goedzo** [comment]
No you should upgrade! Because otherwise you have the risk of being banned.

**Comment by Jcolomar** [comment]
oki doki

**Pull request merged**
