### PR TITLE
Sleeper: pause for some time every day

### PR DESCRIPTION
**Pull request by buluba89**
Short Description: 
The bot is playing 24/7, this is not a normal user behavior. This worker pauses the bot every day for some time to simulate the user having some rest. The time and the duration is configurable from the config file, also a random offset is added for both values.  Example of config entry: 
`

    {
         "type": "Sleeper",
         "config": {
           "time": "12:00",
           "duration":"5:30",
           "time_random_offset": "00:30",
           "duration_random_offset": "00:30"
         }
     }
     time: (HH:MM) local time that the bot should sleep
     duration: (HH:MM) the duration of sleep
     time_random_offset: (HH:MM) random offset of time that the sleep will start
                         for this example the possible start time is 11:30-12:30
     duration_random_offset: (HH:MM) random offset of duration of sleep
                         for this example the possible duration is 5:00-6:00

`
I made this to prevent detecting the bot and avoid ban, i hope you find it useful !

### CODE REVIEW

**Comment by solderzzc** [comment]
lol, this is really funny :) @douglascamata @TheSavior

**Comment by TheSavior** [comment]
For a first PR, this is great. Thanks for the quality, and I'm also very impressed that you wrote tests. I think this is the first worker that has tests (other than some helper logic for one of the navigators). Since this doesn't modify any other workers and just adds one, the barrier to merge is pretty low here. 

Can we name it something more clear than just Sleeper? I'm concerned users won't be able to guess what this does just by seeing the name. Perhaps SleepSchedule?

**Comment by buluba89** [comment]
Thanks a lot !
Yes maybe Sleeper is not clear enought... i will rename it asap !

**Comment by buluba89** [comment]
@TheSavior  Its ready !

**Comment by TheSavior** [comment]
:+1:

**Comment by cwild** [comment]
Great work, I had been thinking about something similar and this looks like it will do just the trick!

**Comment by MZorzy** [comment]
hat to change
"type": "Sleeper",
to 
 "type": "SleepSchedule",
in config, but now in test

**Pull request merged**
