### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by devn0ll**
editet Manual install Mac section

### CODE REVIEW

**Comment by solderzzc** [comment]
Merged, thanks a lot.

**Comment by TheSavior** [comment]
@nivong, do we need these instructions or are the shell scripts in the repo good enough to be the one command people need to run in the installer?

**Comment by devn0ll** [comment]
i would always tell people to use the installer but if somone wants to troubleshoot a problem, or wants to now how its done he can just look in here.
so i would keep it just in case

**Comment by nivong** [comment]
Why is this merged? It's wrong wget isn't being used on Mac. 
Also I would suggest making a new file this is growing too much since I'm also working on a Windows version that also has a lot of lines.

**Comment by TheSavior** [comment]
But if you tell them to run the installer and something fails, they can just look at the installer code, right? Code is typically better documentation since it is guarenteed to be in sync.

**Comment by nivong** [comment]
Some people can't read code so it's probably better not to delete it but rather have a special file

**Comment by TheSavior** [comment]
But it is code, right? It's just a copy paste of the commands in the installation script.

**Comment by nivong** [comment]
Yeah that's true and it s just extra code that needs to be maintained. I'll work on it and do a pr later with Windows instructions and a Windows installar and remove these

**Comment by devn0ll** [comment]
wget works with mac if you install it first @nivong

**Comment by devn0ll** [comment]
we could make different pages for every installation

**Comment by nivong** [comment]
You have to assume that people can't wipe there but so having them installing it although curl is already installed and working just fine isn't how you should approach a doc file..

**Comment by devn0ll** [comment]
i can adapt it to use curl insted of wget if you want me todo that @nivong

**Comment by nivong** [comment]
Like @thesavior said this is better to not be here at all.

**Comment by devn0ll** [comment]
actualy ist not a copy paste of the install script. if i folled it correctly the install script was made after i uploaded the [paste](http://pastebin.com/pzPjXT65) here, but who am i to judge.
[here](http://hastebin.com/cicatifexu.vala) ist the install code without the wget.

Do as you please with moving the codes to other side, but i am a person who wants to know what will be installed so i will always use code instead of just executing an installer

**Comment by nivong** [comment]
Maybe add the comments to the setup.sh?

**Comment by devn0ll** [comment]
i would put 3 manual pages up for windows, linux and mac.
and would leave the installer as it is.
If somone wants to kow the code i can go to the subpages.

**Pull request merged**
