### PR TITLE
FollowPath: implement path_mode=single and loitering

### LINKED ISSUE #4662: FollowPath: loitering around each waypoint
### Short Description
When using FollowPath, it would be nice if the bot would loiter around each waypoint, visiting pokestops in the neighbourhood, catching pokemon, before moving on.

### Possible solution
Allow a 'loiter' field in each element of the path json file, e.g.
```
[
        {"location": "52.067425, 4.214394", "loiter": 60},
        {"location": "52.070780, 4.219230", "loiter": 300},
        {"location": "52.084703, 4.239380"},
        {"location": "52.083615, 4.243328", "loiter": 300},
]
```
This should have to bot loiter at each location for the given number of seconds.

### How it would help others
It would help others to give their bots a bit of freedom roaming about, while keeping the the path on a larger timescale.

### LINKED ISSUE #4663: FollowPath: execute path only once
### Short Description
Sometime I prefer the bot to follow the path only once, instead of looping. This could be useful for having the bot walk to a new location following a number of waypoints, and then go chasing pokemon and pokestops at the new location.

### Possible solution
In the FollowPath configuration, implement path_mode = 'single'. In follow_path.py in the work() function, check for this path_mode in the piece of code that handles the situation where the end of the path is reached. If so, return WorkerResult.SUCCESS to allow lower priority tasks to run.

### How it would help others
It would help if you want your bot to walk to another location once, and there in the new area after the path is finished.

### PR DESCRIPTION
**Pull request by janpascal**
## Short Description:
Add two features to FollowPath:
- path_mode: 'single' will follow the path only once
- 'loiter' in the json file will cause the bot pause following the path for a while, and instead execute the next task. E.g. if a MoveToFort task is next, the bot will chase pokestops for the indicated number of seconds, and the resume the path

## Fixes/Resolves/Closes (please use correct syntax):
- Closes #4662
- Closes #4663

### CODE REVIEW

**Comment by alexyaoyang** [comment]
This is a great feature which makes the bot more humanized! 👍  

Just a few suggestions/question:
- Can you update the path.json.example to include your latest update?
- Maybe tell the users **clearly** in configurations.md that they need to have other Move tasks in their task list or else the bot will **not move at all** after a single run on `single` mode or during `loiter`?

**Comment by erdnaxela02** [comment]
loiter work with .gpx files. How to configure please?
Thanks

**Comment by janpascal** [comment]
@erdnaxela02 : gpx files are usually automatically generated, e.g. by a GPS device or tracking software on a mobile phone. If you like the loiter option, I think you should extract the waypoint from the gpx and put them in a json, and add the loiter values by hand.

**Comment by janpascal** [comment]
@alexyaoyang: I've added the documentation you asked for, could you please have another look?

**Comment by alexyaoyang** [comment]
Looks good to me! Merging this as feature does not affect current behavior.

**Comment by alexyaoyang** [comment]
@janpascal A quick test would be great next time! Good job on this feature tho!

**Pull request merged**
