### PR TITLE
Refactor Polyline to support speed variance.

### PR DESCRIPTION
**Pull request by th3w4y**
## Short Description:

Description will be updated soon

## Fixes
-  adds support for speed variance
-  removes .pause() .unpause() methods..
-  removes all timebases internals..
-  some methods become private... they should not be used externally...
- ...

### CODE REVIEW

**Comment by th3w4y** [comment]
@BreezeRo @sohje @solderzzc  @mjmadsen as discussed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/5147 

Please peer review and add the Review and Help tags to this PR

Thanks...

**Comment by th3w4y** [comment]
This is the generated test line... without the noise..

You can see that the dots are not even separated because of changing speed between the steps...
used a big range of min 2.16 max 30 for illustration purpose

screen shot 2016-09-04 at 03 38 05

**Comment by mjmadsen** [comment]
:+1:

**Comment by Anakin5** [comment]
It seems there is still an issue :s. When the google api quota is reached, the MoveToFort task configured with PolylineWalker makes us jump from fort to fort.

**Comment by th3w4y** [comment]
@Anakin5 will try to see where it can go wrong...

**Comment by Anakin5** [comment]
The Polyline only contains starting point and destination. Before, StepWalker was taking care of doing small steps. But now we directly set the destination.

**Comment by th3w4y** [comment]
@Anakin5  it cannot be... we have the speed involved in the calculation...

**Comment by th3w4y** [comment]
@Anakin5 did you check after this commit... https://github.com/PokemonGoF/PokemonGo-Bot/pull/5162

This might also fix something..
I continue looking.

**Comment by th3w4y** [comment]
@Anakin5 I will add a test case for that see were it breaks..

**Comment by th3w4y** [comment]
I am sorry but i cannot reproduce...

all .get_pose() return the next calculated distance on the bearing between origin and destination

```
In [14]: a.get_alt()
Out[14]: 429.5892333984375

In [15]: a.get_pos()
Out[15]: (47.17062271583738, 8.51677331105169)

In [16]: a.get_pos()
Out[16]: (47.17060763167472, 8.516806122094092)

In [17]: a.get_pos()
Out[17]: (47.17059254751201, 8.516838933127204)

In [18]: a.get_pos()
Out[18]: (47.17057746334926, 8.516871744151027)

In [19]: a.get_pos()
Out[19]: (47.170562379186485, 8.51690455516556)

In [20]: a.get_pos()
Out[20]: (47.170547295023674, 8.516937366170804)

In [21]: a.get_pos()
Out[21]: (47.17053221086082, 8.516970177166757)

In [22]: 

```

**Comment by th3w4y** [comment]
@Anakin5 i am not able to simulate the Elevation API limit reach but i doubt that would be cause of the problem...
```

In [29]: while True:
    ...:     a = Polyline(ex_orig, ex_dest, 3)
    ...:     print(a._directions_response['status'], a._elevation_response['status'])
    ...:     
    ...:     
    ...:     
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OK', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OVER_QUERY_LIMIT', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
(u'OK', u'OK')
```

**Comment by th3w4y** [comment]
@Anakin5 how many  tasks do you have, which one are those, 

and.... any 2 tasks use PolylineWalker in the same time?

**Comment by Anakin5** [comment]
It is daily limitation of the direction API. When it happen, there is only 2 steps: the origin and the destination.
get_pos() return the origin at first call and the destination at second call.
On second call, The stepWalker step do a get_new_pos that seems to return the final destination.

**Comment by th3w4y** [comment]
@Anakin5 this not able to reproduce... do you have origin and destination?

in my above example you can see i also had API limit reached and .get_pos() was returning correct:
```

In [15]: a.get_pos()
Out[15]: (47.17062271583738, 8.51677331105169)

In [16]: a.get_pos()
Out[16]: (47.17060763167472, 8.516806122094092)

In [17]: a.get_pos()
Out[17]: (47.17059254751201, 8.516838933127204)

In [18]: a.get_pos()
Out[18]: (47.17057746334926, 8.516871744151027)

In [19]: a.get_pos()
Out[19]: (47.170562379186485, 8.51690455516556)

In [20]: a.get_pos()
Out[20]: (47.170547295023674, 8.516937366170804)

In [21]: a.get_pos()
Out[21]: (47.17053221086082, 8.516970177166757)

In [22]: 
```

**Comment by th3w4y** [comment]
@Anakin5 and btw... first .get_pos() should not return the origin... should return the position after self.speed seconds.. 

are you sure it returns the origin? 
just to know where to look...

**Comment by Anakin5** [comment]
I was trying to print more logs to give you some info, but I found the issue. There is no sleep(1) in the whole bot loop when using PolylineWalker. It gives the impression we teleported while in fact we were setting the position very quickly.

**Comment by th3w4y** [comment]
the Sleep is in StepWalker..

**Comment by Anakin5** [comment]
In my cast, I see the steps of the MoveToFort task with Polyline walker are around 2.25 meters, which is below my speed (2.5). So we teleport there because of the first condition in StepWalker.step.

**Comment by Anakin5** [comment]
And there is no sleep there.

**Comment by th3w4y** [comment]
@Anakin5 you mean this ?:

`if (self.dLat == 0 and self.dLng == 0) or self.dist < self.speed:`

**Comment by Anakin5** [comment]
yes

**Comment by mjmadsen** [comment]
Should we call heartbeat in that `if`?

**Comment by th3w4y** [comment]
@mjmadsen yes that would be fine.. but we also have to sleep

**Comment by Anakin5** [comment]
I am testing removing that branch completely, I do no see why we need it now.

**Comment by th3w4y** [comment]
for now we have this PR https://github.com/PokemonGoF/PokemonGo-Bot/pull/5169

**Comment by th3w4y** [comment]
@Anakin5 i also believe is not needed but if we take it out it will scare people

**Comment by Anakin5** [comment]
It scares me to have it. Seems it is fine without that piece of code. However need to pay attention to the last step. Does the new calculation always return the exact destination point ?

**Comment by th3w4y** [comment]
@Anakin5 strictly from Polyline yes...
Is only the StepWalker that returns a indirect delta of default [-50cm, 50cm]

**Comment by Anakin5** [comment]
So let's remove that branch then.

**Comment by th3w4y** [comment]
@Anakin5 not comfortable with that yet.. is the only branch that returns True..

**Comment by th3w4y** [comment]
@Anakin5 and once again thanks for testing the PolylineWalker... you are usually first to report any bugs related to it. Thanks Thanks

**Comment by th3w4y** [comment]
just worth mentioning not only the Polyline walker would have been affected by this... but all tasks.. at the last step....

(polyline was affected on each step...when random speed fetch by StepWalker from 2.16 to 4.15 would have been smaller then the calculated next pos on the poyline)

**Comment by th3w4y** [comment]
@Anakin5 i still think there might be an issue... not sure of the PolylineObjectHandler is doing it's job

**Comment by th3w4y** [comment]
Seems to return something similar to api limit although is should not...

```
In [32]: PolylineObjectHandler.cached_polyline(ex_orig, ex_dest, 3)._points
Out[32]: [(47.1706378, 8.5167405), (47.1700271, 8.518072999999998)]
```

**Pull request merged**
