### PR TITLE
Increase default walking speed

### PR DESCRIPTION
**Pull request by Bashin**
Short Description: 
Walking speed was changed from m/s to km/h, so i updated the config files to match the old default speed.

### CODE REVIEW

**Comment by Jojo1910** [comment]
Isn´t 14 km/h the perfect speed for eggs?

**Comment by Bashin** [comment]
Maybe.. I just converted 4.16 m/s to 15 km/h (multiplied by 3.6)

**Comment by douglascamata** [comment]
@Bashin StepWalker consider the speed in `m/s`, because our `distance` functions returns in meters:

```
distance(
            self.initLat,
            self.initLng,
            destLat,
            destLng
        )
```

**Comment by Bashin** [comment]
Are you sure about that? -> #1570 
Wiki says km/h too

**Comment by Nihisil** [comment]
I put 14 to the config and bot started to walk really fast (to compare with previous walk speed).

And with this speed eggs still hatching.

**Comment by Bashin** [comment]
I put 15 to the config and if you compare distance traveled and time it has to be km/h.
Egg hatching works for me too

**Comment by MikeDX** [comment]
If you set a higher speed, it may still not work depending upon location - also the egg hatching distance count may not match the actual distance the bot has travelled.

Using a higher value in speed in one location allowed eggs to be hatched at a fairly regular place, but in another, the bot ran for a while and the counter did not go up, with the only difference in config being the location.

**Comment by douglascamata** [comment]
We can't exactly tell how fast the bot is walking, because we make some API calls and have to sleep a of of time, so it's clearly visible that we're NEVER walking at the speed we think to.

Don't think of walking speed as a unit (m/s or km/h), just know that bigger is faster and smaller if slower.

**Comment by Bashin** [comment]
Ok, but the default value is really slow (i get about 4 km/h after a lot of calculating)

**Comment by douglascamata** [comment]
@Bashin 4 km/h is a very human-like walking. We want to provide a default value close to human walking, so it's good.

**Comment by maestroi** [comment]
don't increase default walking speed because in europe i you walk to fast it does not hatch, 4km/h is pretty much a good speed, also there is no use to go faster.

**Comment by douglascamata** [comment]
Closing because the default value should definitely be human-like.

**Comment by Bashin** [comment]
It works for me in europe.. I think you could double the default value without getting any problems and it's still a very human-like value.

**Comment by maestroi** [comment]
normal average walking speed is like 5km/h so would be very strange if u walk like 8 that's pretty quick for walking 6 hours straight especially if you look at a phone screen.

**Comment by A7F** [comment]
i set the speed on 13 and still hatch eggs... i still don't get wether is in km/h or m/s btw works (Europe, Italy)
If the speed is intended in km/h it's still reasonable just because you can move by bike

**Comment by Bashin** [comment]
I think its very reasonable too, but it's ok for me if the value remains as it is (maybe round it to 4 or 5). The wiki should be updated anyway. I'll set walk to 10 in my config as it is working for me an there is still a safety margin up to 14 or 15.
Any chance to get editor rights for the wiki?

**Pull request closed without merging**
