### PR TITLE
Poke hunter lockon

### PR DESCRIPTION
**Pull request by davidakachaos**
## Short Description:
In a Pokemon littered place (London, or where ever) the Pokemon Hunter sometimes doesn't get to a needed Pokemon, because there are all kind of trash pokemon (compaired to the missing one you're hunting) and the bot will catch those first.

Normally this isn't a problem. But because hunting is safer then sniping (no teleporting, just walking to a Pokemon) and I hope to catch those rares better.

Default setting is false (don't "Lock on") and when enabled the bot will notify you when skipping a Pokemon because of the lock on :smile:

### CODE REVIEW

**Comment by solderzzc** [comment]
👍

**Comment by atxfun** [comment]
I just updated my working bot and now I'm getting this error message:
AttributeError: 'PokemonGoBot' object has no attribute 'hunter_locked_target'

**Comment by leefwang** [comment]
I got this message, too.

[2017-02-07 15:16:31] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'PokemonGoBot' object has no attribute 'hunter_locked_target'", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 206, in main', u'  File "pokemongo_bot/__init__.py", line 778, in tick', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 55, in work']

**Comment by davidakachaos** [comment]
I'm sorry you're encountering this error message. Can one of you supply your config (pastebin) so I can troubleshoot this error?
I think it has to do with the order of the tasks (shouldn't be a problem, but maybe it is.)

**Comment by alandeguz** [comment]
Here's a [pastebin](http://pastebin.com/Hxe2eGDz) for my config. It's just a tweak and cleanup from `config.json.example`.

**Comment by davidakachaos** [comment]
Just like I thought; the solution is in #5904 Hope it will get merged soon.

**Pull request merged**
