### PR TITLE
Determine which ball to use base on catch rate %

### PR DESCRIPTION
**Pull request by earthchie**
change to better ball type if catch rate is fall under 35%

image

Minor changes
- display catch rate %
- add [] to color log

### CODE REVIEW

**Comment by surfaace** [comment]
great pull request

**Comment by eggins** [comment]
this is the kind of request we need!

**Comment by eggins** [comment]
Uh-oh. You broke something.

**Comment by surfaace** [comment]
@eggins dont think he did, i copied over the content locally without issues, commit a634b5529fe0a230bf5cb87e5158ab1844cca6b5 did -> #599

**Comment by Shoh** [comment]
Thank you for wiping out my changes... I don't mind the catch % but I would have preferred if you kept my logic to not use great balls or ultra balls if your stock is less than 10.

**Comment by earthchie** [comment]
@Shoh Sorry about that. Dont' worry some one made new PR about this already. https://github.com/PokemonGoF/PokemonGo-Bot/pull/657

**Pull request merged**
