### PR TITLE
Add option to separate usage of incubator unbreakable from breakable (2)

### LINKED ISSUE #3503: Configure which incubators use 2, 5 or 10km
As per #1997

I'm happy to buy incubators, but I only want to use them on the 10km ones. I don't get value for money from 2km eggs. It would be great to do something like:

Infinite: 2km, 5km
Breakable: 10km

It should always prefer using the infinite if available if config allows both types for a particular distance.

### LINKED ISSUE #3552: [Feature Request] Differentiate Between Unlimited and "Purchased" Incubator use.
Blue incubators are difficult to get so I use it only for 10km eggs. Is there any configuration to prevent bot from using Blue Incubator?

### PR DESCRIPTION
**Pull request by supercourgette**
## Short Description:

- The 2, 5 and 10km eggs can be dispatched between either the infinite or the breakables incubators.

I wasn't able to test this option in real-game, since well... My bot is sleeping. From the tests I ran, the option should behave as excepted.

## Fixes/Resolves/Closes (please use correct syntax):
- Closes #3503
- Closes #3552 

Not sure why it failed before (cf #4556)

### CODE REVIEW

**Comment by mjmadsen** [comment]
CI passed this time. Woot.

**Comment by alexyaoyang** [comment]
This is a great feature! Just a quick question. Will the default values on line 27 and 28 of incubate_eggs.py break old configs which doesn't have the new fields?

**Comment by mjmadsen** [comment]
@alexyaoyang #4564 is a fix for that.

**Comment by supercourgette** [comment]
It would have work without the fix though :)

**Comment by mjmadsen** [comment]
@supercourgette From the looks of it, if they did not update their config, both would be empty when we try them.

**Comment by supercourgette** [comment]
Oh, yes I see, It would not have been broken thought but I see a case I
didn't account for. If an user put an empty array then my code just ignore
the option (which now I think about it is not the indented behavior). I
don't have my computer right now, I'll check this case tomorrow. In the
mean time it is a bit broken in case of empty array. I'm sorry for the
inconvenience :(

On Aug 23, 2016 1:45 AM, "Matt J Madsen" <notifications@github.com> wrote:
>
> @supercourgette From the looks of it, if they did not update their
config, both would be empty when we try them.

**Comment by alexyaoyang** [comment]
Don't worry about it, I'll submit a PR :)

**Comment by supercourgette** [comment]
Thanks :). And sorry for the mistake :)

**Comment by alexyaoyang** [comment]
No problem! Thank @mjmadsen too, he pushed & merged the fix already :)

**Comment by mjmadsen** [comment]
I am getting drained. Either I'll fall asleep soon or have more coffee and keep rocking PRs.

**Comment by alexyaoyang** [comment]
@mjmadsen Very productive stretch! Great job!

**Comment by supercourgette** [comment]
Developers sleep? :P

**Comment by k4n30** [comment]
@supercourgette what about the other config files being update? Happy the doco got done though :)

**Pull request merged**
