### PR TITLE
Web UI improvements and updates

### PR DESCRIPTION
**Pull request by Calcyfer**
### Short Description: 
Updates to pokemon bag display on the map

### Fixes:
-  Added CP and IV to caught pokemon on map
-  Improved layout for pokemon bag display on map

### CODE REVIEW

**Comment by jadbalout** [comment]
Nice work, though all those ??? on the eggs makes it look bad. Maybe work out a way to remove the display of those field for eggs?

**Comment by Calcyfer** [comment]
Good idea. I'm also looking into a way to sort the pokemon by name or CP level, will add that soon.

**Comment by jadbalout** [comment]
How about both? ;) Add sorting options mate.

**Comment by Calcyfer** [comment]
Sorting is coming up.

**Comment by TheSavior** [comment]
Screenshots for UI changes are helpful

**Comment by Foxy1990** [comment]
sorting would be really nice :) im running this code atm

**Comment by Calcyfer** [comment]
Sorting has been added and the eggs in your bag are now displayed below your pokemon as "You have x eggs".

sorting_options

**Comment by RedSparr0w** [comment]
Nice work, one more thing though.

[Line 366 - 375](https://github.com/Calcyfer/PokemonGo-Bot/blob/52046a6d5b6847451781e52cdd2c4e59ac477009/web/main.js#L366-L375) Change to
```javascript
 if (menu == 2) {
    document.getElementById('subtitle').innerHTML = "Items in Bag";
    out = '<div class="row items"><div class="col s12"><h5>' + users[0] + '</h5><table>';
    for (var i = 0; i < bagItems.length; i++) {
      out += '<tr><td><img src="image/items/' + bagItems[i].inventory_item_data.item.item_id + '.png" class="item_img"></td><td>Item: ' + itemsArray[bagItems[i].inventory_item_data.item.item_id] +
      '<br>Count: ' + (bagItems[i].inventory_item_data.item.count || 0) + '</td></tr>';
    }
    out += '</table></div></div>';
    document.getElementById('subcontent').innerHTML = out;
  }
```

**Comment by Calcyfer** [comment]
@RedSparr0w Added.

**Comment by Calcyfer** [comment]
Improved responsiveness, items in bag layout and restyled the menu options

ui-changes-mobile
ui-changes-desktop

**Comment by Calcyfer** [comment]
I'm going to rebase and create a new PR, this is starting to become a mess :D

**Comment by RedSparr0w** [comment]
Coming along nicely.

One more thing if you think it would work/have the time.

Could you add a little pokeball icon next to each pokemon in your bag showing which pokeball it was caught with?

snippets of code:
```javascript
pkmPokeball = obj[i].inventory_item_data.pokemon_data.pokeball || 0;
```
```html
<img src="/image/items/' + pkmPokeball + '.png" class="pokeball">
```
```css
.pokeball {
	width: 30px;
	height: auto;
}
```
if it is a starter pokemon it will show:  (0.png)

not sure about eggs though as haven't hatched one yet.

**Comment by Calcyfer** [comment]
@RedSparr0w I've merged my sorting code with the design Sniok created in the new repository.
You can see the PR here : https://github.com/OpenPoGo/OpenPoGoWeb/pull/17 along with a screenshot.

I'll add the pokeball tomorrow.

**Pull request closed without merging**
