### PR TITLE
Fix pokemon exchange error

### PR DESCRIPTION
**Pull request by sniok**
Short Description: 

Fixes:
Error on pokemon exchange

### CODE REVIEW

**Comment by douglascamata** [comment]
@sniok you sure this works?

**Comment by sniok** [comment]
image
yeah

**Comment by sniok** [comment]
I just checked in game and while it writes that it exchanged, pokemon is still there. I need to investigate further

**Comment by douglascamata** [comment]
@sniok ok. Merging it. Thanks!

**Pull request closed without merging**
