### PR TITLE
Nickname: Remove spaces from Nidorans

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:
When generating a new nickname, remove spaces from Nidorans (convert "Nidoran M/F" into "NidoranM/F")

## Fixes/Resolves/Closes (please use correct syntax):
- #3718

This addresses the request in #3718. Not sure if any expansion needed.

### CODE REVIEW

**Comment by Gobberwart** [comment]
Unit test failing during Travis checks. Investigating.

**Comment by solderzzc** [comment]
Rerun CI.

**Comment by Gobberwart** [comment]
Travis CI is working now. Can we include this or no?

**Comment by solderzzc** [comment]
I think we can. The ci was caused by other commit by me. After pushed the fix to dev and rerun the ci, this one turned good.

**Pull request merged**
