### PR TITLE
BUGFIX: Poke hunter lockon

### PR DESCRIPTION
**Pull request by davidakachaos**
## Short Description:
People encounter an error when using the bot but not hunting for Pokemons, or the hunter is behind the catch pokemon task.

## Fixes/Resolves/Closes (please use correct syntax):
- An error introduced in PR #5902 

Ping @solderzzc

### CODE REVIEW

**Comment by jk7g14** [comment]
@davidakachaos  Lovely ! Now the bot is working properly. Thank you so much !

**Comment by uoliaso** [comment]
Can confirm this solves the problem for me too :)

**Comment by azraelppuk** [comment]
Can confirm this solves the problem for me too :)

**Comment by solderzzc** [comment]
👍

**Pull request merged**
