### PR TITLE
Update configuration_files.md

### PR DESCRIPTION
**Pull request by Nexus2k**
## Short Description:
Improve documentation regarding allowed master values for TelegramTask.

### CODE REVIEW

**Comment by askovpen** [comment]
in code strung username not allowed. only id

**Comment by Nexus2k** [comment]
Check https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/event_handlers/telegram_handler.py#L80 looks like username allowed to me.

**Comment by askovpen** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/event_handlers/telegram_handler.py#L125
not support username

**Comment by Nexus2k** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/event_handlers/telegram_handler.py#L82 checks if username is string and restarts telegram handler with user id of provided string username.

**Comment by askovpen** [comment]
why this duct tape? use id.

**Comment by Nexus2k** [comment]
I think username is more intuitive but yeah nevermind then.

**Comment by askovpen** [comment]
but work only after message to bot

**Pull request closed without merging**
