### PR TITLE
Lure encoding fix

### LINKED ISSUE #2718: 'ascii' codec can't decode byte 0xc3
```
2016-08-07 10:51:36,268 [RecycleItems] [INFO] [item_discarded] Discarded 1x Razz Berry (maximum 20).
2016-08-07 10:51:36,875 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Charmander (CP 172/IV 0.18) based on rule: CP < 9 OR IV < 0.97
2016-08-07 10:51:37,437 [TransferPokemon] [INFO] [pokemon_release] Exchanged Charmander [CP 172] [IV 0.18] for candy.
2016-08-07 10:51:37,953 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Estátua Moore - 0.05km (attraction of lure 0.05km)
2016-08-07 10:51:37,953 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-07 10:51:39,679 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Magnemite appeared! [CP 422] [Potential 0.71] [S/A/D 10/11/11]
2016-08-07 10:51:42,526 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 35.29 (127 left)
2016-08-07 10:51:43,728 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Magnemite! [CP 422] [Potential 0.71] [10/11/11] [+210 exp]
2016-08-07 10:51:44,706 [PokemonCatchWorker] [INFO] [pokemon_evolve_fail] Failed to evolve Magnemite!
2016-08-07 10:51:50,245 [       cli] [INFO] 
2016-08-07 10:51:50,245 [       cli] [INFO] Ran for 0:01:58
2016-08-07 10:51:50,245 [       cli] [INFO] Total XP Earned: 1450  Average: 44164.12/h
2016-08-07 10:51:50,245 [       cli] [INFO] Travelled 0.00km
2016-08-07 10:51:50,246 [       cli] [INFO] Visited 8 stops
2016-08-07 10:51:50,246 [       cli] [INFO] Encountered 5 pokemon, 5 caught, 0 released, 0 evolved, 0 never seen before
2016-08-07 10:51:50,246 [       cli] [INFO] Threw 5 poke balls
2016-08-07 10:51:50,246 [       cli] [INFO] Earned 500 Stardust
2016-08-07 10:51:50,246 [       cli] [INFO] 
2016-08-07 10:51:50,246 [       cli] [INFO] Highest CP Pokemon: Machop [CP: 645] [IV: 9/15/11] Potential: 0.78 
2016-08-07 10:51:50,246 [       cli] [INFO] Most Perfect Pokemon: Machop [CP: 645] [IV: 9/15/11] Potential: 0.78 
Traceback (most recent call last):
  File "pokecli.py", line 499, in <module>
    main()
  File "pokecli.py", line 130, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

error appears only with movetofort
with path config no error appears

### PR DESCRIPTION
**Pull request by dkim1000**
Short Description: 
Undo encoding and format to unicode.
Make it consistent with move_to_fort.py

Fixes:
- UnicodeDecodeError: 'ascii' codec can't decode ....

This closes #2718, #2686, #2678, #2677, #2641 and possibly #2722

### CODE REVIEW

**Comment by sandroid10** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 02:38:24,915 [sentry.errors.uncaught] [ERROR] [u'OSError: dlopen(encrypt.so, 6): image not found', u'  File "pokecli.py", line 500, in <module>', u'  File "pokecli.py", line 129, in main', u'  File "pokecli.py", line 138, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 443, in LoadLibrary', u'  File "ctypes/__init__.py", line 365, in __init__']

**Comment by dkim1000** [comment]
@sandroid10 please do not comment the error here. This is a place for code review and errors should be placed in the issues tab.

**Comment by TheSavior** [comment]
@dkim1000 Is there some piece of information that is pointing you to this specific encoding call being the problem? I don't see it in the stack trace and we do this kind of thing in a bunch of places.

**Comment by nburn42** [comment]
Fix worked for me to fix my issue #2718 

Thanks

**Comment by aslafy-z** [comment]
Please merge this, couldn't work without it !

**Comment by dkim1000** [comment]
@TheSavior I had to look at the information being printed out. It always failed when a pokestop had special characters in it.

The exception is being caught in pokecli.py but no where else (which I think is a problem). This is why we always get the stacktrace pointing to pokecli.py

**Comment by TheSavior** [comment]
By popular demand, I'm merging this. :)

**Pull request merged**
