### PR TITLE
API update fixes (i2f etc) and lured pokemon catching

### PR DESCRIPTION
**Pull request by Calcyfer**
### Short Description: 
Allows us to use the new API version. Fixed i2f functions, geocoding and various method/property name changes.
Also adds catching lured pokemon again.

### Fixes:
- Errors related to new tejado pgoapi version
- Pokemon spawning from lures will now be caught
- Geocoding issue with i2f has been resolved

### CODE REVIEW

**Comment by Calcyfer** [comment]
Tested for 20 mins, runs without errors.

pokemongobot-1082 exe

**Comment by OVO647** [comment]
How do I get this to run properly with lure catching?

**Comment by Calcyfer** [comment]
@OVO647 Pull my branch, then run `pip install --upgrade -r requirements.txt`

**Comment by OVO647** [comment]
I'm a noob with coding how do I pull up your branch?

**Comment by OVO647** [comment]
Ok I'm running it now and I get this error.

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 92, in work_on_cell
    worker = MoveToFortWorker(fort, self)
  File "/Users/User/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 11, in __init__
    self.navigator = bot.navigator
AttributeError: 'PokemonGoBot' object has no attribute 'navigator'

**Comment by rhysd** [comment]
Currently 'pgoapi' package commit hash is fixed to avoid the errros.  Please ensure to also update the commit hash in requirements.txt to use the latest pgoapi package.

**Comment by solderzzc** [comment]
Thanks @rhysd , let me close this issue.

**Comment by rhysd** [comment]
My fix in https://github.com/PokemonGoF/PokemonGo-Bot/pull/1117 is just a way to 'avoid' using the latest pgoapi pacakge.  Apart from it, IMO, we need to follow the update of pgoapi because remote Pokémon Go APIs will be updated.

**Comment by rhysd** [comment]
@solderzzc 

Could you tell me why this PR is closed?  I think this fix is needed to follow up 'pgoapi' package update.

**Comment by Calcyfer** [comment]
@rhysd @solderzzc Rebased and reopened here : #1163
Needless to say, it's the last time I'll try merging this.

**Pull request closed without merging**
