### PR TITLE
Output pokemon move name when catching

### PR DESCRIPTION
**Pull request by enjoy2000**
Short Description: 

Output pokemon move name when catching

### CODE REVIEW

**Comment by knobunc** [comment]
Looks good to me!  Nice idea too.

**Comment by surfaace** [comment]
:+1:

**Comment by surfaace** [comment]
same as #2117, but that's more detailed

**Comment by Nihisil** [comment]
In the current dev version we have information about pokemon moves inside Pokemon object.

So, if you want to print it when you catch a pokemon, you can do it easily with a new PR.

**Pull request closed without merging**
