### PR TITLE
Random catch parameters

### PR DESCRIPTION
**Pull request by lightingghost**
Short Description: 
 Random catch parameters to make catching pokemons not always perfect
Fixes:
- 
- 
-

### CODE REVIEW

**Comment by paledrewnem** [comment]
Please, add this as additional parameter in config

**Comment by MikeDX** [comment]
Maybe this should be optional for those who like to play on the edge? I enjoy the extra xp from excellent + with spin catches and willing to risk bans if they use it to detect the bot.

**Comment by douglascamata** [comment]
Waiting for optional configuration toggle for approval + merge.

**Comment by surfaace** [comment]
@lightingghost please make this an option in configs/config.json.example to randomize the data. default value if nothing is defined should be perfect throws

**Comment by lightingghost** [comment]
Sure, I will add a new option. But the recent commit does not automatically appear. I will close this and init a new pull request.

**Comment by xc-mezcal** [comment]
@lightingghost The catch function failed to do any of nice/great/excellent throw, but only curve ball.

This hugely affect the capture rate :(

**Pull request closed without merging**
