### PR TITLE
Pokemon names

### PR DESCRIPTION
**Pull request by Reaver01**
I see now that this was done as I was working on it...  Here is my implementation anyways.

### CODE REVIEW

**Comment by eggins** [comment]
Are you able to fix up the merge conflicts that there currently are?
More than willing to add this once its added.

**Comment by eggins** [comment]
Merged this in - had to fix conflicts

**Comment by Reaver01** [comment]
Currently working on making some of these prints a little more human readable

**Comment by eggins** [comment]
@Reaver01 appreciate it mate - I was gowing through and doing it all - just currently working on something else important for work.

Ill be back on this iin an hr or so :)

**Comment by Reaver01** [comment]
I am about to head home, so I will delve into everything a little deeper when I am at my desktop.

**Pull request merged**
