### PR TITLE
Fix #5051

### LINKED ISSUE #5051: [Issue] donot_evolve_list not obeyed
### Expected Behavior
In my config.json, i have mentioned not to evolve dratini. So the bot should not evolve dratini.

### Actual Behavior
bot evolved dratini.

### Output when issue occurred
[2016-09-01 05:34:16] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Dratini [IV 0.91] [CP 552] [2 candies] [+1000 xp]
[2016-09-01 05:34:37] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Geodude [IV 0.6] [CP 589] [63 candies] [+500 xp]
[2016-09-01 05:35:06] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Geodude [IV 0.89] [CP 583] [39 candies] [+500 xp]
[2016-09-01 05:35:34] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Tentacool [IV 0.53] [CP 605] [1 candies] [+500 xp]
[2016-09-01 05:36:07] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Bellsprout [IV 0.93] [CP 627] [63 candies] [+500 xp]
[2016-09-01 05:36:30] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Bellsprout [IV 0.73] [CP 597] [39 candies] [+500 xp]
[2016-09-01 05:37:05] [EvolvePokemon] [INFO] [pokemon_evolved] Evolved Machop [IV 0.62] [CP 779] [60 candies] [+500 xp]

### Steps to Reproduce
Use latest master bot with latest config.json

### Other Information
OS: 
Win 10
Branch: 
Master
Git Commit: 
42d670a411b4f8dc9a6206dd10a88cc51744026d
Python Version: 
2.3.6

### PR DESCRIPTION
**Pull request by DeXtroTip**
## Short Description:
Haven't tested it but being the problem missing an uppercase letter (dratini -> Dratini), this should fix it, since it makes all pokemon names strings lowercase before compare and test.

## Fixes/Resolves/Closes (please use correct syntax):
- Fixes #5051

### CODE REVIEW

**Comment by Jasperrr91** [comment]
You might wanna add lower to the evolve/do_not_evolve list as well, since users may input with or without caps.

**Comment by DeXtroTip** [comment]
@Jasperrr91 Yep, that's already on lines 31 and 34

**Comment by Jasperrr91** [comment]
@DeXtroTip Oh yea, I wasn't looking properly! Coffee must have worn out 🤓

**Comment by solderzzc** [comment]
👍

**Pull request merged**
