### PR TITLE
Keep by best hp max

### LINKED ISSUE #3958: Keep heaviest pokemon
### Edited by moderator:
Submitting a request to have an option in the config to keep pokemon by their stats.
Example: Recycle pokemon by size.

***
#### Original Post:

Hi,

Is there a way to keep pokemons based on their weight or size instead of only iv or cp ?

Thanks

### PR DESCRIPTION
**Pull request by supercourgette**
## Short Description:

Add the possibility to keep pokemon by best max hp. I believe the IV is already dependent of the hp (and therefore hp max). therefore I'm not quite sure of the utility of this commit... Yet, since it was requested, I did it.

## Fixes/Resolves/Closes (please use correct syntax):
- Resolve #3958 ?

### CODE REVIEW

**Comment by supercourgette** [comment]
Not sure why there is my old commit on the update wiki...

**Comment by Foulwerp** [comment]
Can we use a list of criteria to keep based so the user can pick keep stats from most to least importance. Instead of adding a new method for each one. What if I find moveset.defense_perfection, cp, then iv the order I want them in.

For example.

```"Ekans": { "keep_best": "defensive_moveset_dps,cp,iv"}```

Instead of forcing players to choose one of the few keep bests they can define their own, on what they think is best?

**Comment by k4n30** [comment]
+1 to @Foulwerp 's idea, makes it more customisable and prevents the incoming xx number of feature requests

**Comment by supercourgette** [comment]
You right, I'll have a look at it.

**Comment by supercourgette** [comment]
I did the changes, but I didn't have time to test them a lot though. It seems to work, but I only tried for "moveset.defense_perfection, hp_max" and not for the other (my bot don't have a lot of pokemons...). 

I removed what I did for keep_best_hp_max, so if people used it in their configuration, it will not work anymore.

And I'm not sure why there is the "Merge remote-tracking branch 'upstream/dev' into dev" here... :/

**Comment by solderzzc** [comment]
This is really good, just could you please also look into the pokemon_optimizer.py? 
This is not applied to pokemon_optimizer.py.

**Comment by supercourgette** [comment]
Probably answer #4084

**Comment by supercourgette** [comment]
@solderzzc I'll have a look at it. pokemon_optimizer is a bit more confusing though, I will need some time to understand it.

**Pull request merged**
