### PR TITLE
Bulktransfer Fix

### PR DESCRIPTION
**Pull request by walaoaaa1234**

### CODE REVIEW

**Comment by pogarek** [comment]
let's try

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
merged #5988

**Comment by pogarek** [comment]
better, but one of my bots just crashed:
```
Traceback (most recent call last):
  File "pokecli.py", line 865, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "e:\Poke\PokemonGo-Bot\pokemongo_bot\__init__.py", line 785, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "e:\Poke\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_optimizer.py", line 243, in work
    self.apply_optimization(transfer_all, evolve_all, upgrade_all, xp_all)
  File "e:\Poke\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_optimizer.py", line 682, in apply_optimization
    self.evolve_pokemon(pokemon)
  File "e:\Poke\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_optimizer.py", line 784, in evolve_pokemon
    candy.consume(pokemon.evolution_cost - candy_awarded)
  File "e:\Poke\PokemonGo-Bot\pokemongo_bot\inventory.py", line 762, in consume
    raise Exception('Tried to consume more {} candy than you have'.format(self.type))
Exception: Tried to consume more Pidgey candy than you have
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "E:\Poke\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 67, in main_thread_terminated
    if not self._timed_queue_join(initial_timeout):
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 98, in _timed_queue_join
    queue.all_tasks_done.acquire()
AttributeError: 'Queue' object has no attribute 'all_tasks_done'
[2017-03-31 20:16:33] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "E:\Poke\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "E:\Poke\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Poke\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "E:\Poke\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "E:\Poke\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "E:\Poke\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "E:\Poke\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "E:\Poke\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "E:\Poke\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "E:\Poke\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "E:\Poke\Python27\lib\httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-03-31 20:16:33] [sentry.errors.uncaught] [ERROR] [u'Exception: Tried to consume more Pidgey candy than you have', u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 206, in main', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 785, in tick', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\pokemon_optimizer.py", line 243, in work', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\pokemon_optimizer.py", line 682, in apply_optimization', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\pokemon_optimizer.py", line 784, in evolve_pokemon', u'  File "e:\\Poke\\PokemonGo-Bot\\pokemongo_bot\\inventory.py", line 762, in consume']
Error in sys.exitfunc:
[2017-03-31 20:16:33] [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'Queue' object has no attribute 'all_tasks_done'", u'  File "E:\\Poke\\Python27\\lib\\atexit.py", line 24, in _run_exitfuncs', u'  File "E:\\Poke\\Python27\\lib\\site-packages\\raven\\transport\\threaded.py", line 67, in main_thread_terminated', u'  File "E:\\Poke\\Python27\\lib\\site-packages\\raven\\transport\\threaded.py", line 98, in _timed_queue_join']
Traceback (most recent call last):
  File "E:\Poke\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 67, in main_thread_terminated
    if not self._timed_queue_join(initial_timeout):
  File "E:\Poke\Python27\lib\site-packages\raven\transport\threaded.py", line 98, in _timed_queue_join
    queue.all_tasks_done.acquire()
AttributeError: 'Queue' object has no attribute 'all_tasks_done'
```

**Comment by Jcolomar** [comment]
For me doesnt work. Dont release at 245/250 like before

**Comment by Jcolomar** [comment]
rules2

**Pull request merged**
