### PR TITLE
Fix transfer, if some of release_below_iv/ivcp/cp missed and logic is…

### PR DESCRIPTION
**Pull request by sohje**
## Short Description:
Transfer wasn't working on config like:
```js
    "release": {
      "any": {"release_below_cp": 1700, "release_below_iv": 0.95, "logic": "and"}
    },
```
## Fixes/Resolves/Closes (please use correct syntax):
- possible #5507

### CODE REVIEW

**Comment by Anakin5** [comment]
It looks like
`release_below_cp: 0`
will release all Pokemon !

**Comment by sohje** [comment]
I think its already in example config already.
```js
"any": {"release_below_cp": 0, "release_below_iv": 0, "release_below_ivcp": 0, "logic": "or"},
```
Btw, code in PR working fine on all my bots.

**Comment by Anakin5** [comment]
Can you put that config on your bots and run it ?
```
"release": {
    "any": {}
},
```

**Comment by sohje** [comment]
It will release everything.

**Comment by Anakin5** [comment]
Yes, and same for
```
"release": {
    "any": {"release_below_cp": 0}
},
```

I don't think such configs should release anything at all.

**Comment by sohje** [comment]
You are talking about hardcoded values and release logic upon unconfigured configs. Am i right?

**Comment by Anakin5** [comment]
I don't know what is an unconfigured config, but my examples are real. What do you suggest to put in the config if we don't want to release anything ?

**Comment by sohje** [comment]
```js
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": false,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      }
```

**Comment by Anakin5** [comment]
So by default, the task transfer all Pokemon. Do we agree that is not the behavior we want ?

**Comment by sohje** [comment]
Hmm, seems tree_config_builder already take care of enabled option.

**Comment by Anakin5** [comment]
Of course I mean if it is enabled. If the task is not there or disable, I guess it is not transferring anything.
But if it is enabled, the configuration in the config example, an empty configuration or a spelling mistake in the config file will release all Pokemon.

Can we agree that without any rule define, the behavior should be to not transfer anything ?

**Comment by sohje** [comment]
I think we should disable transfering only on:
```js
"release": {
    "any": {}
}
```
and transfer taks is enabled.
Otherwise its upon user who configured config. I mean, if "any" dict contains something we will proceed with base transfer logic.

**Comment by Anakin5** [comment]
If config is like that, it will also transfer everything:
```
"release": {
    "any": {"release_below_cp": 20, "release_below_iv": 0.1, "logic": "or"}
},
```

**Comment by sohje** [comment]
@Anakin5 i updated comment above.

**Comment by Anakin5** [comment]
Well, if you want an insight, that is the same issue for the catch pokemon logic.
When `logic` is `and`, the default value of each release parameter should be `True`.
When `logic` is `or`, the default value of each release parameter should be `False`.

It is to make sure that any parameter not present in the configuration will not change the result.
Trying to code anything with the same default values for both logic is going to break one of the two.

**Comment by xiatianyu** [comment]
This PR should hopefully fix #5480 (which is not fixed by PR #5499, albeit being closed).
As I mentioned in #5480, Pokémon transfer was still working on 3ff99ca058691dde9e0df4ea3af093e80f73d6a6, but no longer worked on 7947c7f7a19e1dc27d5feb4b284470498dcfdb73, so any changes made between these two commits might be the actual culprit.

Running `git log --pretty=format:"%h %ad : %s"` shows the commits in beween:
…
7947c7f `Fri Sep 16 00:35:03 2016 -0700 : Hotfix for transfer_pokemon.py`
ce7a7ec `Fri Sep 16 00:29:15 2016 -0700 : Merge pull request #5472 from PokemonGoF/dev`
7d68e7d `Fri Sep 16 00:05:18 2016 -0700 : Format links (#5470)`
0edbed4 `Thu Sep 15 22:52:39 2016 -0700 : Added PR tutorial in readme (#5463)`
3ff99ca `Fri Sep 16 00:40:20 2016 -0400 : Yet another fix`
…

Here are the rules I am using:
```
"release": {
      "any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "and"},
      "Pidgey": {"keep_best_iv": 35},
      "Weedle": {"keep_best_iv": 20},
      "Caterpie": {"keep_best_iv": 15},
      …
}
```
The first rule `"any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "and"}` is not taking effect.

**Comment by Gobberwart** [comment]
Unless I've misunderstood the change, I'm not sure this really fixes anything, at least not for different logic.

Example1: `"any": {"release_below_cp": 0, "logic": "or"}`

Pokemon CP/IV/NCP = 20/0.3/0.5 should not be released, but...

release_results['cp'] = False (not release_cp or pokemon.cp < release_cp)
release_results['iv'] = True (not release_iv)
release_results['ncp'] = True (not release_ncp)

False or True or True = True

Example2: `"any": {"release_below_cp": 0, "logic": "and"}`

release_results['cp'] = False (not release_cp or pokemon.cp < release_cp)
release_results['iv'] = True (not release_iv)
release_results['ncp'] = True (not release_ncp)

False and True and True = False 

So Example1 (or) is incorrect, Example2 (and) is correct.

**Comment by Gobberwart** [comment]
How about:

```
    release_results = {}
if (cp_iv_logic == 'and'):
    release_results['cp'] = not release_cp or pokemon.cp < release_cp
    release_results['iv'] = not release_iv or pokemon.iv < release_iv
    release_results['ivcp'] = not release_ivcp or pokemon.ivcp < release_ivcp
else:
    release_results['cp'] = release_cp and pokemon.cp < release_cp
    release_results['iv'] = release_iv and pokemon.iv < release_iv
    release_results['ivcp'] = release_ivcp and pokemon.ivcp < release_ivcp
```

**Comment by sohje** [comment]
@Gobberwart Read PR's short description again. Transfering doesnt work if "release_below_ivcp" missed. We've invented new config option "release_below_ivcp" and didnt provide correct logic for already configured confs w/o this opt.

**Comment by Gobberwart** [comment]
I read the description, but your fix is not a complete fix. You are breaking "or" logic to fix "and" logic, which is still not really fix.

The previous (current) version works great for "or" logic, it just doesn't work for "and" logic. This PR as it currently stands will reverse that fault, but not fix properly.

My suggestion will fix "and" without breaking "or" in the process.

**Comment by Gobberwart** [comment]
It will also not lead to situations such as that noted by @Anakin5 where "release_below_cp": 0 with "or" logic would release everything. That definitely should not happen, but will happen if this PR is merged as-is.

**Comment by Gobberwart** [comment]
Testing shows there's still an issue with something like:

`"any": {"release_below_cp": 0, "logic": "and"}` 

This will release everything because the "release_below_cp": 0 counts as false. Your logic converts this to True, and all missing conditions also True.

Need to find something which will 1) use something other than boolean, since boolean False == 0, and 2) count anything non-existent as True.

**Comment by Gobberwart** [comment]
This should do it??

```
        release_results = {}
        if (cp_iv_logic == 'and'):
            release_results['cp'] = (release_config.get('release_below_cp', -1) != 0) and (not release_cp or pokemon.cp < release_cp)
            release_results['iv'] = (release_config.get('release_below_iv', -1) != 0) and (not release_iv or pokemon.iv < release_iv)
            release_results['ivcp'] = (release_config.get('release_below_ivcp', -1) != 0) and (not release_ivcp or pokemon.ivcp < release_ivcp)
        else:
            release_results['cp'] = release_cp and pokemon.cp < release_cp
            release_results['iv'] = release_iv and pokemon.iv < release_iv
            release_results['ivcp'] = release_ivcp and pokemon.ivcp < release_ivcp
```

**Comment by Gobberwart** [comment]
@sohje, what do you think?

**Comment by fglx** [comment]
Hi. Same problem occurs with "vips".

`"any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" }`
always evaluates to true.

**Comment by davidspeijer** [comment]
Any news on this as my pokebag is full :)

**Comment by LazGit** [comment]
i need it too ^

**Comment by Gobberwart** [comment]
I'm not sure where @sohje is. I've created a new PR with the extended fix and will merge shortly. Leaving this open in case @sohje wants to do something else with it.

**Comment by Gobberwart** [comment]
PR #5575 merged.

**Comment by Gobberwart** [comment]
4 days since last comment from @sohje and fix already implemented in another PR. Closing.

**Pull request closed without merging**
