### PR TITLE
Make SpinFort spin even when bag is full

### PR DESCRIPTION
**Pull request by clavat**
Short Description: 
Spin fort reward XP
Fixes:
- #2180 

Remove space check before spinning.
Spin fort still usefull because it rewars XP (#2180)

### CODE REVIEW

**Comment by CapCap** [comment]
Can you have this be a config option?

**Comment by TheSavior** [comment]
Yeah, this needs to be a configuration option.

**Comment by pokecunt** [comment]
download

**Comment by clavat** [comment]
I guess someone can do this in a better way than me.
I'm not familiar with Python, so i can't do a great job !

**Pull request closed without merging**
