### PR TITLE
refactor log handler

### PR DESCRIPTION
**Pull request by rawgni**
## Short Description:

refactor logging handler code.
log handler shouldn't need to have access to the whole bot, but only needed config

### CODE REVIEW

**Comment by solderzzc** [comment]
> This branch has conflicts that must be resolved

**Comment by rawgni** [comment]
@solderzzc fixed

**Comment by rawgni** [comment]
@solderzzc any problem with this ?

**Comment by solderzzc** [comment]
No, I don't think there's any, just have time to go through code...

**Comment by solderzzc** [comment]
👍

**Pull request merged**
