### PR TITLE
Updated requirements.txt to pogoapi/dev and pokemon 2nd generation an…

### PR DESCRIPTION
**Pull request by Jcolomar**
…d auth.json.example, fix bag, moveset and buddy candies

# Please Note - You may remove this section before opening your PR
We receive lots of PRs and it is hard to give proper review to PRs. Please make it easy on us by following these guidelines:

## Fixes/Resolves/Closes (please use correct syntax):
-Updated requirements.txt to pogoapi/dev and pokemon 2nd generation an…  …
…d auth.json.example, fix bag, moveset and buddy candies.

With this changes, bot is ready to work with new api-server-hash, so u need to buy a key from https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer.

Thx to pogarek for help. 

-

### CODE REVIEW

**Comment by heldertb** [comment]
Why is this closed? :o thank you for the updated pokemon.json tho

**Comment by Jcolomar** [comment]
No devs interested in this project since 0.45. This bot is amazing, pogarek fix a lot of issues and bot works again with last api, but u must buy a key license.

**Comment by heldertb** [comment]
@Jcolomar sad, someone should fork it and integrate all the PR's in there which should become the main repo. There's always an interest from people who like to contribute

**Comment by Jcolomar** [comment]
@heldertb see https://github.com/pogarek/PokemonGo-Bot/tree/dev

**Pull request closed without merging**
