### PR TITLE
[Move_to_map_pokemon] Add an option to move towards near forts before Pokemon

### PR DESCRIPTION
**Pull request by Napator**
Short Description:

Add some improvements to move_to_map_pokemon mode :

- option to go towards a pokemon through a fort
- the percentage of extra distance is a parameter in the config file
- add a constant to mark a pokemon a "encountered" before reaching the it's exact position

PS : sorry for my english and if the code is not "clean", i'm kind a beginner in program writing

### CODE REVIEW

**Comment by k4n30** [comment]
@Napator please update https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md too

**Comment by Napator** [comment]
Updated !

**Comment by solderzzc** [comment]
need solve the conflict..........

**Comment by Napator** [comment]
I updated my branch and see any conflict. Is it OK now ? If not, which conflict are you talking about ?

**Comment by solderzzc** [comment]
yes. the conflict was fixed.

**Pull request merged**
