### PR TITLE
Update the bot when starting the server

### PR DESCRIPTION
**Pull request by nivong**
## Short Description:
I think it's a good idea that people will be forced to always update to the latest github version. Just to get them not banned for example and help the noobs out.

### CODE REVIEW

**Comment by devn0ll** [comment]
@nivong do you wan to put `pip install -r requirements.txt` in there too ? To make shure that if new requieremts come out that is save too ?

**Comment by nivong** [comment]
ah yea forgot about that, will it also be usefull to put in
`pip install -r requirements.txt --upgrade` after?

**Comment by BreezeLo** [comment]
That's never a good idea, if you want to update your project automatically you could use a cron job on your own set up

**Comment by simonsmh** [comment]
no it's not a good idea if dev is broken. close it and find a better way.

**Comment by danielsdian** [comment]
If the user installed the Master version, it will update it, right? even if dev is broken, the idea is for the users to run the Master version?

**Comment by 03t02** [comment]
If I want to update, I prefer to do it myself, because sometime that some modification that I don't want to update. And the role of `run.sh` is not to update the repo.

**Comment by simonsmh** [comment]
Do you really want to notice the user that they have an update?
First git fetch
Then if git log = git log origin/dev(or master(how to check it automatically?))
Echo something like you have an update blablabla.
This is much better than force update.

**Comment by MZorzy** [comment]
And what about config.json modifications ?

**Comment by danielsdian** [comment]
Why shouldnt the average user be automatically updated? Cant we make it so that if you are using the Master branch you get the update and if you are in the dev branch you dont and need to do it manually?

**Comment by devn0ll** [comment]
@danielsdian sounds good to me. I think on dev its alwyas better to update manualy

**Comment by BreezeLo** [comment]
+1 @danielsdian

**Comment by douglascamata** [comment]
Not a good idea, imho. What if I find a good commit and want to stick with it no matter what?

**Comment by nivong** [comment]
Maybe change it that it only updates the master branche and that we add a configuration option to disable it.

**Comment by simonsmh** [comment]
We should make it automatically. Does anyone knows how to check branch is on master or dev?

**Comment by jaymaree92** [comment]
git branch -m - would be better I think

**Comment by simonsmh** [comment]
Git branch -vv|grep "* master"
I am going to fix all things about it and open a new pr tomorrow.(I'm in China)

**Comment by nivong** [comment]
thanks closing this one. Thanks @simonsmh

**Pull request closed without merging**
