### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by devn0ll**
Changed the linux Section and the Ubuntu example, for easyer access
(if anyone now how to make a code block collapsable feel free)

### CODE REVIEW

**Comment by nivong** [comment]
if you can adopt this for the mac and windows too i would suggest go for it. (also delete the small linux bit it's not needed 2...

**Comment by devn0ll** [comment]
I'll get right to it when I am home (windows and Mac I can't promise but I'll try)

**Comment by devn0ll** [comment]
@nivong done will check on windows and mac in the next 24 h

**Comment by devn0ll** [comment]
but like i said i'll make a new pr for that

**Comment by nivong** [comment]
Please do it in 1

**Comment by devn0ll** [comment]
ok i'll add here later

**Comment by devn0ll** [comment]
that should open it again right :D ?

**Comment by nivong** [comment]
@solderzzc didn't read Haha

**Comment by nivong** [comment]
Please reference this pr too please

**Comment by devn0ll** [comment]
@solderzzc can't i just copy the hole linux thing and replace it with `apt-get` with `brew` ? that should work shouldn't it :D

**Comment by solderzzc** [comment]
... we already have the installation in wiki for Mac, right? @devn0ll

**Comment by solderzzc** [comment]
The pre-requirement is linked to the original repo:
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/installation.md#requirements-click-each-one-for-install-guide

**Comment by devn0ll** [comment]
@solderzzc but not as detailed as i made the Linux installation...
i can just leave it be like it is but @nivong asked if could make it so for mac too

**Comment by solderzzc** [comment]
We can merge this for now :)

**Comment by devn0ll** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/3763
edited Mac section

**Pull request merged**
