### PR TITLE
Live config update

### PR DESCRIPTION
**Pull request by alexyaoyang**
## Fixes/Resolves/Closes (please use correct syntax):
- #3588
- Allows 2 modes:
1. Normal live update for entire config file
screenshot 2016-08-25 at 2 47 35 pm
2. Quick update for tasks only (without relogin)
screenshot 2016-08-25 at 2 46 14 pm
- Defaults to disable, users have to enable explicitly (and hopefully read the doc to understand the differences between the modes)
- Cross platform compatible

### CODE REVIEW

**Comment by sohje** [comment]
@alexyaoyang Seems good ;]

**Comment by solderzzc** [comment]
Rerun CI.

**Comment by solderzzc** [comment]
Wow, really, a live change happen :)

**Comment by alexyaoyang** [comment]
@sohje Thank you! :) @solderzzc Yes, I found it quite convenient for tweaking config 👍

**Pull request merged**
