### PR TITLE
update readme to pull submodules

### PR DESCRIPTION
**Pull request by AlixBa**
Short Description: 
With the change of /web to submodule, we need to init & update.

Fixes:
- IOError: [Errno 2] No such file or directory: 'web/index.html'

### CODE REVIEW

**Comment by 3mph4515** [comment]
@AlixBa I've got an error with that

`
fatal: destination path 'web' already exists and is not an empty directory.
fatal: clone of 'https://github.com/OpenPoGo/OpenPoGoWeb.git' into submodule path 'web' failed`

**Comment by AlixBa** [comment]
mmm. It works fine on OS X. Which OS are you using?

**Comment by 3mph4515** [comment]
@AlixBa Also using OSX, fixed by removing web folder and trying again.

**Comment by solderzzc** [comment]
The instruction is insane needed!!!!!!

**Pull request merged**
