### PR TITLE
Crvfts patch 1

### PR DESCRIPTION
**Pull request by crvfts**
Summary: 
Appears to fix bot getting stuck and not moving to fort and bot moving back and forth between forts but never getting to either.

Resolves:
#6099 #6104 #6065

### CODE REVIEW

**Comment by MerlionRock** [comment]
👍

**Comment by ChiefM3** [comment]
Wow thanks for the fix. I should definitely test this.

**Comment by MerlionRock** [comment]
I don't think it's fixed....  It make it worst.... I am reverting it back on my own project and see

**Comment by MerlionRock** [comment]
I think need to revert, this commit causes the bot behave incorrectly and no longer visit gyms.

**Comment by Plecoholic** [comment]
it is not because of this change ...
if you look on the gym objects returned from cell parsing they all have atribute "closed".

**Pull request merged**
