### PR TITLE
catching every single pokemon nearby

### PR DESCRIPTION
**Pull request by douglascamata**

### CODE REVIEW

**Comment by z4ppy** [comment]
I mean pop isn't need here ;)

**Comment by douglascamata** [comment]
@z4ppy you're right. I'll remove.

**Comment by TheSavior** [comment]
This may not be necessary anymore with the improvements that we have just made. It would be valuable to re-evaluate how much improvement we get and if it is worth the issues we would have for not following the way the ticks have worked previously. We would also run into issues with our bag getting full inside the loop.

**Comment by TheSavior** [comment]
Yeah, I updated these to properly return control to the tick, so we will spin all the forts before moving to the next task in the list. I'll go ahead and close both PRs then.

**Pull request closed without merging**
