### PR TITLE
Add and Remove pokemon from the inventory cache when catch, release and evolve

### PR DESCRIPTION
**Pull request by achretien**
The catch / released pokemon are updated in the inventory cache

### CODE REVIEW

**Comment by joaodragao** [comment]
@achretien awesome! 👍

**Comment by joaodragao** [comment]
I think we should focus on refactoring the whole code (unity and clean code), fixing bugs, and preparing for proper release version. Don't add more features! Keep it for next version.

**Comment by douglascamata** [comment]
@achretien is this rdy to merge?

**Comment by achretien** [comment]
Yes it is. I have my main account ban so I will slow the dev a little bit :)

**Comment by douglascamata** [comment]
👍

**Pull request merged**
