### PR TITLE
Decrease number of messages from MoveToFort worker

### PR DESCRIPTION
**Pull request by cmezh**
Overwrite previous event line (only moving_to_fort and moving_to_lured_fort events).

### CODE REVIEW

**Comment by Gobberwart** [comment]
I actually like having this info, so I know the bot's actually doing something at times when nothing else is happening.

**Comment by cmezh** [comment]
@Gobberwart If you take look at timestamp and wait 0.5-2 seconds you can see that it's working ;)
Also I've changed in my config "distance_unit" to "m" instead of "km", so now messages are not the same.

**Comment by Gobberwart** [comment]
@cmezh OK, that's kinda cool actually (I misunderstood your intention). Any chance of putting this in follow_path and follow_spiral as well?

**Comment by cmezh** [comment]
@Gobberwart Yep, why not? But first this idea and its implementation must be approved by devs.

**Comment by Gobberwart** [comment]
Looking forward to seeing the end result of this.

**Comment by mjmadsen** [comment]
@Gobberwart @cmezh Love it. When we expand, can we add to config to set frequency? Maybe ever X events we print, or by distance, etc. Maybe just an enable/disable - sometimes I like to see each for testing walker changes.

**Comment by cmezh** [comment]
If we go this way, I think, enable/disable is enough. Maybe I will
implement this.
Currently you can disable this feature if you set ```debug``` option in
config to true. But in this case you will also get other debugging
messages, not only from MoveToFort.

26 авг. 2016 г. 21:56 пользователь "Matt J Madsen" <notifications@github.com>
написал:

**Comment by mjmadsen** [comment]
Working on a PR, should be up shortly.

**Comment by cmezh** [comment]
@mjmadsen Nice! Sorry, I forgot that you are dev and started explaining simple things 8)

**Comment by mjmadsen** [comment]
config attribute isn't passed to the event manager, or I'm missing something. Might take me a bit longer than I expected.

**Comment by mjmadsen** [comment]
@cmezh Check out #4780 - I need to do some minor things before it can be merged.

**Comment by Gobberwart** [comment]
Looking good! I've only tested with MoveToFort but I'm really liking it. Nice work @cmezh and @mjmadsen

**Pull request merged**
