### PR TITLE
Improve and update pokemon.json

### PR DESCRIPTION
**Pull request by amal**
## Short Description:

Improve and update pokemon.json

1. Unminify for simplier updates and usage
2. [Add family id to "Next Evolution Requirements"](https://github.com/PokemonGoF/PokemonGo-Bot/pull/2462/commits/c2c6e600b88fe427b0ac0d215c5cf39b5d952ce8) (by @achretien from #2462). It can help when doing maths with candies for evolution.
3. [Add missing Previous evolution(s)](https://github.com/PokemonGoF/PokemonGo-Bot/pull/2462/commits/b01bcec55a26b2b9183488d61e0ada935cf4e0c3) (by @achretien from #2462)
4. Add BaseAttack, BaseDefense, BaseStamina, CaptureRate, FleeRate, Fast/Special Attack(s)

## Explanation:

With this changes we can add calculation of **moveset perfection**, **cp perfection** ([more accurate then simple iv perfection](https://github.com/jabbink/PokemonGoBot/issues/469)) and many others (**best tiers calculation**, **attack/defense dps**, etc..)

It will allow to significantly improve logic in many places like catching, evolving & releasing pokemons.

I'll add mentioned calculations in this next pool request, when this will be merged.

## Additional info:

This pull includes and complements #2462

### CODE REVIEW

**Comment by TheSavior** [comment]
This is great. How did you generate this file?

**Comment by amal** [comment]
@TheSavior added data is from this table:
[https://docs.google.com/spreadsheets/u/1/d/1I0Kt_QblThH2rf7vdZOC2L1Nuf7Y1xx68j_KYwfcpXc](https://docs.google.com/spreadsheets/u/1/d/1I0Kt_QblThH2rf7vdZOC2L1Nuf7Y1xx68j_KYwfcpXc/htmlview?sle=true)

**Comment by amal** [comment]
Next PR:  #3336 Fast & charged attacks data

**Comment by amal** [comment]
Next PR: #3455  Better inventory: attacks & movesets, IV CP perfection, pokemon level, etc..

**Pull request merged**
