### PR TITLE
Update pgoapi to a newer version

### PR DESCRIPTION
**Pull request by terbolous**
Short Description: 
Updates the pgoapi in requirements.txt

Fixes:
Hopefully it fixes these issues:
- #3181
- #3098
- #2874
and possibly more, I haven't checked them all, but it should fix those that ends with this after a certain time:

`File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 176, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)`

Needs testing/verification. I am running now, but it does take about an
hour to trigger.

### CODE REVIEW

**Comment by cmezh** [comment]
Works for me without any exceptions.

**Comment by brantje** [comment]
Running here, will report back after an hour (or so).

**Comment by licklake** [comment]
Please check if this is causing #3261

**Comment by solderzzc** [comment]
I've been running on a2755eb42dfe49e359798d2f4defefc97fb8163d overnight. Not introduced issue.

**Comment by solderzzc** [comment]
👍

**Comment by icecubeice** [comment]
2016-08-10 21:36:36,072 [pgoapi.pgoapi] [ERROR] Request for new Access Token failed! Logged out...
2016-08-10 21:36:36,596 [       cli] [INFO]
2016-08-10 21:36:36,596 [       cli] [INFO] Ran for 2:28:32
2016-08-10 21:36:36,596 [       cli] [INFO] Total XP Earned: 58640  Average: 23687.20/h
2016-08-10 21:36:36,596 [       cli] [INFO] Travelled 6.22km
2016-08-10 21:36:36,596 [       cli] [INFO] Visited 395 stops
2016-08-10 21:36:36,596 [       cli] [INFO] Encountered 111 pokemon, 109 caught, 224 released, 18 evolved, 5 never seen before
2016-08-10 21:36:36,598 [       cli] [INFO] Threw 123 pokeballs
2016-08-10 21:36:36,598 [       cli] [INFO] Earned 17203 Stardust
2016-08-10 21:36:36,598 [       cli] [INFO]
2016-08-10 21:36:36,598 [       cli] [INFO] Highest CP Pokemon: Pinsir [CP: 1074] [IV: 15/9/15] Potential: 0.87
2016-08-10 21:36:36,598 [       cli] [INFO] Most Perfect Pokemon: Pinsir [CP: 346] [IV: 14/15/13] Potential: 0.93
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 107, in main
    formmated='Log logged in, reconnecting in {:s}'.format(wait_time)
ValueError: Unknown format code 's' for object of type 'int'

this is what happened, although it did increase the time to 2 hours but problem still persists

**Comment by cmezh** [comment]
You can fix it locally by replacing "{:s}" with "{:d}" in file pokecli.py,
line 107. I think someone will make PR with this fix, I can't do this right
now.

10 авг. 2016 г. 20:42 пользователь "icecubeice" <notifications@github.com>
написал:

**Comment by icecubeice** [comment]
ok ill try it

**Comment by cmezh** [comment]
@icecubeice it was already fixed two days ago #3045. Update your copy.

**Pull request merged**
