### PR TITLE
decouple datastore from the bot

### PR DESCRIPTION
**Pull request by rawgni**
## Short Description:

The Datastore is being initialized multiple times, resulting in multiple duplicate migrations.

## Fixes/Resolves/Closes (please use correct syntax):
- Initialize the Datastore once, migrate once, and done with it.
- Pass the datastore connection to the bot.
- Easier to mock datastore since it's no longer initialized inside PokemonGoBot()

### CODE REVIEW

**Comment by BreezeRo** [comment]
Excellent work right here brother, please update this branch with the latest changes from dev so we can merge

**Comment by rawgni** [comment]
@BreezeRo should be updated now

**Comment by solderzzc** [comment]
Since the DB expert approval, we can have this merged.

**Comment by MZorzy** [comment]
alt_min default 500
alt_max default 1000
alt default 8 ?

please set null and force chek exist on a config file

**Pull request merged**
