### PR TITLE
Config/encrypt fix

### PR DESCRIPTION
**Pull request by heihachi**
## Short Description:
Corrected the config files from my last PR
## Fixes (provide links to github issues if you can):
- Encrypt location will actually get pulled from configs now.

### CODE REVIEW

**Comment by hklcf** [comment]
:+1:

**Comment by hklcf** [comment]
@heihachi one more place
https://github.com/PokemonGoF/PokemonGo-Bot/search?utf8=%E2%9C%93&q=libencrypt_location&type=Code

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/__init__.py#L673
change "libencrypt_location" to "encrypt_location"

**Comment by heihachi** [comment]
@hklcf thanks its fixed now should have done a code search :P

**Comment by TheSavior** [comment]
:+1:

**Pull request merged**
