### PR TITLE
Update CP nerf/buff 0,47.1

### PR DESCRIPTION
**Pull request by MZorzy**
data changed due 0.47.1 CP nerf/buff
thx to @tihiniko

### CODE REVIEW

**Comment by nachi9211** [comment]
This may not be working, I personally found it to work earlier, but clearly had made some mistake. Sorry ^^

**Comment by MZorzy** [comment]
can't see why don't work. suggestion ?

**Comment by ChaosMarc** [comment]
there are 2 unit tests that test for specific values found in pokemon which fail due to the new values.
you need to update the following tests:
`======================================================================
ERROR: test_nickname_generation (tests.nickname_test.NicknamePokemonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PokemonGoF/PokemonGo-Bot/tests/nickname_test.py", line 83, in setUp
    "cp": 653, "nickname": "Golb", "id": 13632861873471324}),
  File "/home/travis/build/PokemonGoF/PokemonGo-Bot/pokemongo_bot/inventory.py", line 991, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
======================================================================
FAIL: test_pokemons (tests.inventory_test.InventoryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PokemonGoF/PokemonGo-Bot/tests/inventory_test.py", line 44, in test_pokemons
    assert 54 <= pokemon.base_defense <= 242
AssertionError
----------------------------------------------------------------------`

**Comment by MZorzy** [comment]
ah ok, now BaseDefense hight is 323, 
ok try to change tests/inventory_test.py

**Comment by ChaosMarc** [comment]
did you test locally? or do you just push untested? please don't do that? I guess you missed the minimum value. please try the following values (I cannot test myself atm):
assert 29 <= pokemon.base_attack <= 330
assert 44 <= pokemon.base_defense <= 323

**Comment by MZorzy** [comment]
push untested. can't underdstsnd what /test do.
pokemon.json must changed as 1st commit

**Pull request closed without merging**
