### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arlber**
Short Description: 

Fixes:
- 
- 
- 

For Windows virtualenv creates a batch file to modify the shell prompt in the Scripts folder

### CODE REVIEW

**Comment by maestroi** [comment]
For dev it needs to be cerified that it only needed for windows that linux still needs the other comment, also needs clarification

**Comment by NamPNQ** [comment]
@maestroi:
@arlber is correct, follow tut in [virtualenv doc](https://virtualenv.pypa.io/en/stable/userguide/)

**Comment by arlber** [comment]
@maestroi you are correct, I went back and made another commit clarifying the development section. It may make sense to change the development section to say something along the lines of "same procedure as above but change 'master' to 'branch'" to reduce the amount of text

**Comment by maestroi** [comment]
@arlber Sounds good now

**Comment by arlber** [comment]
Installation instructions removed from the file and moved to the wiki.

**Pull request closed without merging**
