### PR TITLE
Heartbeat decoupled from tasks.

### PR DESCRIPTION
**Pull request by sohje**
## Short Description:
Heartbeats decoupled from tasks. Heartbeat coupled to bot main instance, separate main hb logic from any tasks.
## Fixes/Resolves/Closes (please use correct syntax):
- Need some additional tests, works for me (evolved 40 pokemons, heartbeats is ok)
- No need #5237

### CODE REVIEW

**Comment by solderzzc** [comment]
Need a ignore heartbeat flag, since sniper will change location but should not send heartbeat since the location changed. correct me if I'm wrong.

**Comment by sohje** [comment]
@solderzzc Ops, sure! Add a flag to bot instance:
```python
self.hb_locked = False
```

**Comment by Anakin5** [comment]
Is there any location info in the heartbeat ?

**Comment by solderzzc** [comment]
@Anakin5 every api request include auth info, including device_info/location/sensor data.

**Comment by Anakin5** [comment]
ok. Also the heartbeat function update the timeout_fort list. Do we plan to move that somewhere else ? maybe in the tick ?

**Comment by rawgni** [comment]
any idea what other api is being chained inside the heartbeat call ?
#4605

**Comment by solderzzc** [comment]
👍 
Merge at the time, I believe the get_map_obj is in the heartbeat call as well.

**Pull request merged**
