### PR TITLE
Wander

### LINKED ISSUE #5416: loitering
hi there.
i have an understanding issue. read the docs and tried a lot but I don't get it.
I have a point-path file with loitering points. So far everything works. The bot walks to the points and loiters at some stops for 0s and at some for 500s (as specified in the file). So far so good.

my  initial standard tasks are set like in the standard config and are all beeing executed when in loitering mode. But I can not get the MovetoFort-Task after the FollowPath-Task to Work.
`tasks: ... --> spinFort --> FollowPath --> FollowSpiral --> MovetoFort`

can someone post a working task-list for me, please?

### LINKED ISSUE #5488: Loitering does not seem to work properly
### Expected Behavior

Run the bot, go to the next point as in my path file, then, while loitering, move to forts, spin the pokestop and catch pokemons.

### Actual Behavior

only while is following a path spin the pokestops, while is loitering it does nothing.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/HDWecKDg

### Output when issue occurred

http://pastebin.com/2fY2XXBC
in the line 40 and 426 start to loiter.

### Steps to Reproduce

./run.sh

### Other Information
OS: Ubuntu 16.04
 
Branch: master
 
Git Commit: a8ee31256d412413b107cce81b62059634e8c802
 
Python Version: Python 2.7.12
 
Any other relevant files/configs (eg: path files) 

path file
[
	{"location": "40.7814675, -73.9741015, 33", "loiter": 300},
  {"location": "40.7795502, -73.9632225, 46", "loiter": 300},
  {"location": "40.7739931, -73.9665484, 23", "loiter": 300},
  {"location": "40.7741881, -73.9707756, 25", "loiter": 300},
  {"location": "40.7757805, -73.9717841, 26", "loiter": 300},
  {"location": "40.7772429, -73.9712047, 29", "loiter": 300},
  {"location": "40.7678016, -73.9717411, 18", "loiter": 300},
  {"location": "40.7663878, -73.9732003, 21", "loiter": 300},
  {"location": "40.7647626, -73.9732003, 32", "loiter": 300},
  {"location": "40.7653802, -73.9750671, 26", "loiter": 300},
  {"location": "40.7665015, -73.9748954, 14", "loiter": 300},
  {"location": "40.7762842, -73.9740157, 32", "loiter": 300}
]

### PR DESCRIPTION
**Pull request by janpascal**
## Short Description:
Restores the behaviour of the `loiter` field in the path.json for `FollowPath`.
Renames `loiter` to `wander` to avoid future misunderstandings.

## Fixes/Resolves/Closes (please use correct syntax):
Fixes #5416
Fixes #5488

### CODE REVIEW

**Comment by alexyaoyang** [comment]
@janpascal Thanks for fixing the wander function! I believe the MoveToFort task was also changed similarly previously. Do you think we should change it back too?

**Comment by mudmud2k** [comment]
I think it's better to let loitering be like it is and just add a wandering/wander/wanderlust/stroll option...

It's just one config element more,... further we could add it also in the track.json file, when it should just wander or loiter (stroll/dawdle)

**Comment by alexyaoyang** [comment]
@mudmud2k After this PR is merged, you can still do a stand-still loiter with the wander feature, just don't have any move task below FollowPath 👍

**Comment by janpascal** [comment]
@alexyaoyang: Probably, but I'm not familiar with the `MoveToFort` task. I can imagine that the changes you refer to may cause the bot to get blocked, if the following `FollowSpiral` task (in the default config) doesn't get a chance to take the bot away in case it gets stuck just following pokestops.

@mudmud2k, @alexyaoyang: If enough people are interested, I can add a loiter option (in the new sense of the option). But let's get this PR merged first.

**Comment by alexyaoyang** [comment]
👍 Ah I see, so wander now applies only for FollowPath. I think that is a good idea.

Agree, let's get this merged first.

**Pull request merged**
