### PR TITLE
Fix #2442 - should_retry_throttle isn't defined

### LINKED ISSUE #2442: should_throttle_retry crash
Everything working fine, bot is walking then crashes to this. Happen multiple times so far.  Everything is up-to-date.

```
Traceback (most recent call last):
  File "pokecli.py", line 445, in <module>
    main()
  File "pokecli.py", line 71, in main
    bot.tick()
  File "C:\Trainers\PokemonGo-Bot01\pokemongo_bot\__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Trainers\PokemonGo-Bot01\pokemongo_bot\cell_workers\incubate_eggs.py", line 41, in work
    self._apply_incubators()
  File "C:\Trainers\PokemonGo-Bot01\pokemongo_bot\cell_workers\incubate_eggs.py", line 52, in _apply_incubators
    pokemon_id=egg["id"]
  File "c:\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 84, in function
    return request.call()
  File "C:\Trainers\PokemonGo-Bot01\pokemongo_bot\api_wrapper.py", line 112, in call
    if should_throttle_retry:
UnboundLocalError: local variable 'should_throttle_retry' referenced before assignment
```

### PR DESCRIPTION
**Pull request by DayBr3ak**
__Short Description__:

Variables weren't correctly defined

__Fixes__:
- #2442

__Culprit__:
- #2407

### CODE REVIEW

**Comment by JSchwerberg** [comment]
Don't blame #2407 -- I only renamed your variable from #2357! :tongue: 

But seriously, good catch.  Can't believe we both missed that. :-|

**Comment by dexxer** [comment]
Why even bother having those variables? Makes the code more confusing IMO...

Just put the contents of the 'if' blocks inside the except clauses, since they both just continue anyways

**Comment by sciyoshi** [comment]
Note that #2407 also has a typo: `unexpected_reponse_retry` (note `reponse` vs `response`)

**Comment by migolo** [comment]
Hi, can you please fix Line 120 of that file, there is a typo, should be unexpected_re**s**ponse_retry, currently we have unexpected_reponse_retry

**Comment by CapCap** [comment]
please fix typo and rebase, I will pull when ready

**Comment by DayBr3ak** [comment]
@JSchwerberg there was no errors before your PR :)
The typo is fixed

**Pull request merged**
