### PR TITLE
Update TransferPokemon to use new Inventory Class

### PR DESCRIPTION
**Pull request by achretien**
Short Description: 

Use the new Inventory Class for Transfer Pokemon task

### CODE REVIEW

**Comment by TheSavior** [comment]
This looks good to me, @douglascamata can you review too please?

:+1:

**Comment by douglascamata** [comment]
@TheSavior seems ok. @achretien did you test it very well? This is a critical task.

**Comment by achretien** [comment]
I did but feel free to ask more testers on Slack.

**Comment by douglascamata** [comment]
@achretien we need a dry mode to test, otherwise ppl will be afraid, lol

**Comment by achretien** [comment]
Should I not release pokemon if test mode enable for exemple ?

**Comment by douglascamata** [comment]
@achretien I think that's great for testing such a critical feature.

**Comment by achretien** [comment]
added the test mode

**Comment by douglascamata** [comment]
👍 

LGTM

**Pull request merged**
