### PR TITLE
Move SleepSchedule from workers to main bot instance

### PR DESCRIPTION
**Pull request by cmezh**
...and some whitespace cleaning.
This prevents logging in to account before bot goes sleep if bot is launched at sleep time.
And also in my opinion SleepSchedule is not a regular task and it's better to put it into bot directly.

### CODE REVIEW

**Comment by solderzzc** [comment]
CI build failed :(

**Comment by cmezh** [comment]
@solderzzc Fixed and tested :)

**Comment by solderzzc** [comment]
Can we add console log to tell user the format of conf changed when they have the schedule sleep task configured ? Or, another dev broken help wave will come.

**Comment by cmezh** [comment]
@solderzzc Done.

**Comment by solderzzc** [comment]
@cmezh  Thanks a lot.

**Comment by kenkclam** [comment]
How should the config looks like now?

In the example, SleepSchedule is still under tasks?

https://github.com/PokemonGoF/PokemonGo-Bot/blob/ae314b666a1eb71de8872289ef3a298af09e4637/configs/config.json.example

**Comment by cmezh** [comment]
@kenkclam It looks like my examples changes were overwritten by soneones PR.
See example here: https://github.com/cmezh/PokemonGo-Bot/blob/03361efd5305bd78be0aebaafd463d5a11fd7628/configs/config.json.example

**Pull request merged**
