### PR TITLE
Fix merge conflicts that caused bugs

### PR DESCRIPTION
**Pull request by Nihisil**
This related with latest Allow to keep stronger pokemon PR. 

My bad, didn't test it properly. Weaker pokemon didn't transfer, but I fixed it.

### CODE REVIEW

**Comment by douglascamata** [comment]
Tested?

**Comment by Nihisil** [comment]
@douglascamata Yep, this one was tested. Current version in dev branch doesn't release pokemon actually

**Comment by douglascamata** [comment]
👍

**Comment by Nihisil** [comment]
@douglascamata I think you can believe to me and merge it :) Because soon it will be conflicts again, because of refactoring. I'm tired to solve them.

**Comment by TheSavior** [comment]
:+1: 

Dev branch actually does release pokemon, It requires `"release_pokemon": true,` to be in your config.json

**Comment by Nihisil** [comment]
@TheSavior I told about my code :) It has a feature to release a weaker pokemon. But it didn't work properly, because of some missed lines. After this PR code will work fine :)

**Pull request merged**
