### PR TITLE
Proper logging & minor refactoring

### PR DESCRIPTION
**Pull request by berend**
I started cleaning up a bit.

If you like this, I can continue. I will try to simplify the code and make it more readable.

### CODE REVIEW

**Comment by berend** [comment]
basically all print are now removed. If we want to change the logging prefix to something fancy, we can do so at one central point (like there was on some print statements `[-]` or `[!]`

**Comment by douglascamata** [comment]
@berend you mind rebasing your work with mine here https://github.com/PokemonGoF/PokemonGo-Bot/pull/84? I did a much bigger refactoring with code reorganisation and more stuff.

**Comment by berend** [comment]
on it

**Comment by berend** [comment]
hm, rebasing look like redoing it, since you also split files. I ll wait until you merge, and go on from there.

**Comment by berend** [comment]
closing this one in favor of https://github.com/PokemonGoF/PokemonGo-Bot/pull/91

**Pull request closed without merging**
