### PR TITLE
Huge clean-up: PEP8, sort imports, remove deprecated and unused imports

### PR DESCRIPTION
**Pull request by asnelzin**
I think there is something more, but this is only the beginning. Just could not watch code without tears of blood.

### CODE REVIEW

**Comment by douglascamata** [comment]
@asnelzin you have merge conflicts.

**Comment by asnelzin** [comment]
@douglascamata fixed.

**Comment by douglascamata** [comment]
@TheSavior check this!

**Comment by TheSavior** [comment]
:+1

**Pull request merged**
