### PR TITLE
This Will Make Logging Work at WebUI

### PR DESCRIPTION
**Pull request by oralunal**
I updated the WebUI to. These settings make the webui logging work ;)

### CODE REVIEW

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
CI failed :)

**Comment by oralunal** [comment]
I forgot a commo

**Comment by mjmadsen** [comment]
Could you please add to the other config files and update configuration_files.md?

**Comment by solderzzc** [comment]
@CI, nice work

**Comment by oralunal** [comment]
I'm newbie at git, I'm gonna make a new PR

**Pull request closed without merging**
