### PR TITLE
[config] new tasks in example files

### PR DESCRIPTION
**Pull request by mmnsgo**
UpdateTitleStats: see https://github.com/PokemonGoF/PokemonGo-Bot/pokemongo_bot/cell_workers/update_title_stats.py for more info

```
      {
        "type": "UpdateTitleStats",
        "config": {
            "min_interval": 10,
            "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
            "terminal_log": true,
            "terminal_title": true
        }
      }
```

SleepSchedule: see https://github.com/PokemonGoF/PokemonGo-Bot/pokemongo_bot/cell_workers/sleep_schedule.py for more info

```
      {
        "type": "SleepSchedule",
        "config": {
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      }
```

### CODE REVIEW

**Comment by Moonlight-Angel** [comment]
I just created PR https://github.com/PokemonGoF/PokemonGo-Bot/pull/3467.
If it gets merged before yours, please update the worker title in the config files.
If yours gets merged before mine, I'll take care of it.

👍

**Comment by mmnsgo** [comment]
will do! thanks.

**Comment by mmnsgo** [comment]
requires #3467

**Comment by TheSavior** [comment]
One challenge we have related to this is that most people just copy and paste the example config into their config and expect the bot to run as expected. So I'd be concerned putting things in here that will have an unexpected effect when run. 

For example, we at one point had nickname pokemon in the example config. We got tons of complaints about that really quickly. Perhaps it makes more sense to create a markdown file in the docs folder that contains the task configuration if our intention was to have every task in the config.json

**Comment by achretien** [comment]
Maybe adding them as disabled tasks #3417

**Comment by mmnsgo** [comment]
@achretien good point, done

**Comment by k4n30** [comment]
:+1:

**Comment by TheSavior** [comment]
This seems fine. We should really figure out how to merge all of these files.

:+1:

**Comment by k4n30** [comment]
+1 to the mergiing the example files with disabled tasks

**Pull request merged**
