### PR TITLE
Captcha Solving

### PR DESCRIPTION
**Pull request by MerlionRock**
2Captcha Solving by iksteen. Taken from his fork at https://github.com/iksteen/PokemonGo-Bot/commit/1d03382e02c29e3941557aa4eab8da6d07e5cafe

To enable 2Captcha, add "2captcha_token": "YOUR 2CAPTCHA TOKEN HERE" into auth.json

Manual Solving using Chrome Driver: https://sites.google.com/a/chromium.org/chromedriver/

Chrome driver must be placed in root dir of the bot.

Please test and let me know if it work. Comment with your operating system and error message.

### CODE REVIEW

**Comment by pogarek** [comment]
What in case if user doesn't want to resolve captcha and just want to have warning ?

**Comment by MerlionRock** [comment]
@pogarek Noted, will add task into config.
```
 "type": "SolveCaptcha",
        "config": {
            "enabled": false
          }
```

**Comment by MerlionRock** [comment]
..... Why I always have problem loading from config....

**Comment by Jcolomar** [comment]
Can i merge?

**Comment by MerlionRock** [comment]
No harm merging? I'll add in the config to disable captcha solving later while people test if it work? I need people to test on other os platform

**Comment by MerlionRock** [comment]
Can someone test and merge if good?

I need a PC user to test the manual captcha solving

**Comment by Jcolomar** [comment]
Merged #6050

**Pull request merged**
