### PR TITLE
Move_to_map_pokemon improved

### PR DESCRIPTION
**Pull request by sohje**
## Short Description:
Some preparations before full refactoring
## Fixes/Resolves/Closes (please use correct syntax):
- cleanup
- redudant code removed
- pep8

### CODE REVIEW

**Comment by mjmadsen** [comment]
Thank you @sohje!

**Comment by YvesHenri** [comment]
Seems good. Talked to him on slack about some small changes.

**Comment by mjmadsen** [comment]
:+1: 

We agree to push?

**Comment by sohje** [comment]
Merge then)

**Comment by YvesHenri** [comment]
I do.

**Pull request merged**
