### PR TITLE
Better handling of config.json

### PR DESCRIPTION
**Pull request by NorthIsUp**
Short Description: 
Do a better job of reading in the config.json file that uses features of argparse that are basically for this reason.

Fixes:
- several small bugs around argument parsing

### CODE REVIEW

**Comment by douglascamata** [comment]
We do not add features to master anymore.

**Comment by NorthIsUp** [comment]
@douglascamata I can't find the instructions for contributing. Can you help me out here with a little more info on how to get a PR accepted?

**Comment by CapCap** [comment]
@NorthIsUp please use the dev branch for changes/pr :-)

**Comment by surfaace** [comment]
please create PR to dev branch

**Pull request closed without merging**
