### PR TITLE
Add metrics logging and output on close

### PR DESCRIPTION
**Pull request by bstpierr**
Output looks like the following:

[17:10:07] Exiting PokemonGo Bot
[17:10:07]
[17:10:07] Ran for 0:00:20
[17:10:07] Total XP Earned: 210  Averaging: 36534.47/h
[17:10:07] Travelled 0.01km
[17:10:07] Visited 0 stops
[17:10:07] Encountered 1 pokemon, 1 caught, 0 released, 0 evolved, 0 never seen before
[17:10:07] Threw 1 pokeball
[17:10:07] Earned 100 Stardust
[17:10:07]
[17:10:07] Highest CP Pokemon: Nidoran M [CP: 75] [IV: 1/10/5] Potential: 0.36
[17:10:07] Most Perfect Pokemon: Nidoran M [CP: 75] [IV: 1/10/5] Potential: 0.36

### CODE REVIEW

**Comment by douglascamata** [comment]
Do you mind extracting your report logic into an specific class that becomes an attribute of the bot main class? It would be great help for when we implement behaviour tree. Thanks!

**Comment by bstpierr** [comment]
Sure. I was thinking of doing it The Right Way™ initially (the way you suggest), but I got lazy and just hacked it in this way to see my stats. I'll refactor it out and update the PR when it's ready for prime time.

**Comment by douglascamata** [comment]
@bstpierr great! Mention me here or at slack when u finish.

**Comment by bstpierr** [comment]
@douglascamata All ready for your review when you have the chance!

**Comment by douglascamata** [comment]
I already approved. Need one more to merge.

**Comment by solderzzc** [comment]
👍

**Pull request merged**
