### PR TITLE
Added utf8 compatibility and fixes wrong distance estimator

### LINKED ISSUE #96: not spinning forts with non ascii char in names
or smthing like that. 

Raising UnicodeEncodeError here
File "D:\pokemonbot\cell_workers\seen_fort_worker.py", line 38, in work
  print('Now at Pokestop: ' + fort_details['name'] + ' - Spinning...')

works fine when `fort_details['name']` removed

### PR DESCRIPTION
**Pull request by tstumm**
Fixes #96

### CODE REVIEW

**Comment by tstumm** [comment]
Also fixes #52 since ae4d842

**Comment by eggins** [comment]
Appreciate this commit!

**Comment by tstumm** [comment]
Please do not forget to close the corresponding issues :)

**Comment by eggins** [comment]
Just did @tstumm  :)

**Comment by douglascamata** [comment]
@tstumm @PokemonGoF `pgoapi` is an external package and its folder is going to be removed in favor of only importing as a dependency from setup.py. Fixes to `pgoapi` should be done in https://github.com/tejado/pgoapi and we should not add code to `pgoapi` like this.

**Comment by tstumm** [comment]
It's actually not a fix in pgoapi since I added the code for walking by myself. I just moved my code to utilities.

**Pull request merged**
