### PR TITLE
Added option to prioritize the best balls

### PR DESCRIPTION
**Pull request by aleskr**
Short Description: 
Added the option to use Anyball in the config of what to keep. If there is more pokeballs(of all types combined) than specified by the config to keep the worst balls will be recycled first.

Usage:
Remove all Pokeball filters and add Anyball and the number of balls you want to keep in total.

Fixes:
- #2166

### CODE REVIEW

**Comment by amal** [comment]
Brilliant! Please do the same for potions.

**Comment by aleskr** [comment]
I was considering rewriting it and doing the same for potions and revives, and just throwing away the rest. I really don't se any reason for keeping "Pokeball" "Greatball" and so on...

**Comment by MrCarlosJr** [comment]
Necessary use any ball to for capture pokemon.

**Comment by Evanito** [comment]
For some reason current code doesn't use ultraballs when out of poke and great balls

**Comment by aleskr** [comment]
@Evanito @MrCarlosJr This has nothing to do with capturing, this is for recycling as stated in the description...

**Comment by mjmadsen** [comment]
Love this. @aleskr any progress on this lately?

**Pull request closed without merging**
