### PR TITLE
Export to file

### PR DESCRIPTION
**Pull request by omeryagmurlu**
## Short Description:
Adds a worker to export some useful information, currently only csv format.

## Fixes:
- https://github.com/PokemonGoF/PokemonGo-Bot/issues/3387

### CODE REVIEW

**Comment by Nihisil** [comment]
@TheSavior what do you think. Should this PR be merged to the dev, or maybe better to keep this feature as separate plugin?

**Comment by TheSavior** [comment]
I think this is a great example of something that should be a plugin. At least to start. If we find this is very popular and wants to be a built in task, we can reconsider later.

@omeryagmurlu Feel free to follow the documentation for creating plugins. https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/plugins.md

**Comment by omeryagmurlu** [comment]
Ok, will make this a plugin.

Is there a way for plugins to have events? I registered the event in PokemonGoBot class, which I can't do with a plugin.

**Comment by TheSavior** [comment]
What do you need to emit that event? Is it just to write to the console?

@douglascamata Do you have any thoughts on how plugins should handle this? I imagine theoretically at least, tasks could register there events in initialize using:

```
self.bot.event_manager.register_event('file_exported')
```

**Comment by douglascamata** [comment]
This task and this plugin aren't really necessary. One can enable websocket and remote control and create a simple script that dumps the necessary data every now and then.

**Pull request closed without merging**
