### PR TITLE
Captcha, POGOProtos and PogoAPI Check

### PR DESCRIPTION
**Pull request by MerlionRock**
Added a simple captcha check. Manual captcha solving is planned. WILL NOT add 2captcha service.

Also checking the version of POGOProtos to alert user of a possible PogoAPI changes. Can't think of a better solution as I can't find anyway to get versioning from PogoAPI.

Changes to PogoAPI check using float instead of matching against strings. In the event that PogoAPI is ahead of official Niantic API, the bot still can run.

### CODE REVIEW

**Comment by solderzzc** [comment]
👍

**Comment by snooter** [comment]
Lack of 2Captcha is really disappointing.

**Comment by MerlionRock** [comment]
@snooter The original contributors here are not keen and they don't really approve 3rd party  services. Unless they change their stand, this will not change.

However, if someone else is interested, they can always code them in and submit as a PR and it is up to the reviewers to approve.

**Comment by solderzzc** [comment]
@MerlionRock  It's welcome to have captcha service integration since it always depends on user to enable or not.

**Comment by MerlionRock** [comment]
@solderzzc haha~ If you say so.

I'll find some time to look at it. I'm just treating this as a hobby. Not coding for at least 15 years, just don't want to loose a skill that I once good at. LOL

**Pull request merged**
