### PR TITLE
incubate using infinite first, then breakable

### PR DESCRIPTION
**Pull request by rawgni**
## Short Description:

use infinite incubator first, then breakable.
correctly identify the type of incubators

## Fixes/Resolves/Closes (please use correct syntax):
- #4835 
-
-

### CODE REVIEW

**Comment by mjmadsen** [comment]
:+1:

**Comment by mjmadsen** [comment]
Can you do a rebase. Just merged another.

**Comment by rawgni** [comment]
@mjmadsen should be done

**Comment by mjmadsen** [comment]
:+1:

**Comment by mjmadsen** [comment]
Thanks @rawgni

**Comment by Anakin5** [comment]
The egg task is still not using/updating the inventory. This cause other tasks to have a wrong count of Pokemon in the bag.

**Pull request merged**
