### PR TITLE
Fix #5232

### LINKED ISSUE #5232: Issue ([Errno 54] Connection reset by peer) with PokemonOptimizer task
### Expected Behavior
The evolve process continue without any issue. 

### Actual Behavior
Evolve process returns an Error ([Errno 54] Connection reset by peer) every few evolve. Please see the logs: http://pastebin.com/1HU82FM3
Same thing happens during transfer:
http://pastebin.com/Xmfbb086

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/LjBKMwhC

### Output when issue occurred

http://pastebin.com/1HU82FM3
http://pastebin.com/Xmfbb086

### Steps to Reproduce
Use the task PokemonOptimizer to transfer or evolve.

### Other Information
OS: 
Mac OS X 10.11.6
Branch: 
dev
Git Commit: 
f0df954ee0e79c1dbfd3be76324b73b36988915b
Python Version: 
2.7
Any other relevant files/configs (eg: path files)

### PR DESCRIPTION
**Pull request by Anakin5**
Fix Connection reset by peer issue when evolving

### CODE REVIEW

**Comment by sohje** [comment]
This is sockets issue, not heartbeat.
I have this issue when ws server enabled.

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
> This branch has conflicts that must be resolved

**Comment by Anakin5** [comment]
I delete, no need

**Pull request closed without merging**
