### PR TITLE
Update README to have IRC channel instead of Slack 

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by douglascamata** [comment]
??????

**Comment by MaxLeiter** [comment]
We should use IRC instead of slack. See #318

**Comment by douglascamata** [comment]
@MaxLeiter not everyone agreed to IRC channel yet. So this MR should wait.

**Comment by MaxLeiter** [comment]
Doesn't need to be merged immediately. Not everyone will agree, but plenty of people can't access slack at the moment due to invite limitations.

**Pull request closed without merging**
