### PR TITLE
Added a configuration option "path_startmode" (conflict merge #2489)

### PR DESCRIPTION
**Pull request by JaapMoolenaar**
_I recreated the fork/repo for easy merging_

_Python is most definitely not my main programming language, however, I thought this was a nice addition to the path walker nonetheless._

Short Description: 
Updates the FollowPath walker to allow a "path_startmode" configuration option. Setting it to "first" mimics the current behavior: move to the first point in the list and walk through them from there. Setting it to the "new" value of "closest" will try to find the closest point to the bots position and first move there before continuing along the other point in the path.

I also added a log message to see which point the bot is walking to (so one can tell it's still walking).

In future updates I imagine having an option to continue to the "next" point in the path using some kind of persisted storage (If it still exists, since path files can change).

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for recreating this. It looks like your build is failing on travis.

@douglascamata Can you review this when you get a chance, it is 👍 from me

**Comment by JaapMoolenaar** [comment]
Yeah, it seemed I PR-ed too quickly. It seems ok now!

**Comment by douglascamata** [comment]
@JaapMoolenaar please change `path_startmode` to `path_start_mode`, other than this LGTM.

**Comment by AcorpBG** [comment]
I belive we are not using logger anymore

**Comment by JaapMoolenaar** [comment]
See https://github.com/PokemonGoF/PokemonGo-Bot/pull/3270/commits/9ac270d8117a79fcb9f8c04bf741a1f15f64a3b2 ;-)

**Comment by douglascamata** [comment]
@JaapMoolenaar there are still useless logs in this PR. They are not really necessary and should be removed, imho.

**Comment by JaapMoolenaar** [comment]
I hope it is up to your standards now mister.
I don't have any more dev time now, so this is it for today ;-)

**Comment by douglascamata** [comment]
@JaapMoolenaar don't goooo, there are merge conflicts :(

**Comment by dogrocker** [comment]
@JaapMoolenaar If use `path_start_mode` the `"location": "SOME_LOCATION", in main config is not necessary right ?

**Pull request merged**
