### PR TITLE
added sniping lured pokemon

### PR DESCRIPTION
**Pull request by JohanJu**
Short Description: 
It needs testing and refactoring

### CODE REVIEW

**Comment by mhdasding** [comment]
you duplicate a lot of the logic. i would refactor this so the lured pokemon just get added in the get_pokemon_from_map so all the other logic like priority sorting etc isn't duplicated

**Comment by JohanJu** [comment]
I know, I will probably do it when I got time and a better understanding of the latest code. Just thought a version that only appends and don't change current functionality would be good for testing purposes.

**Comment by hero16** [comment]
i'll go take a test on this one too if it could be of use

**Comment by JohanJu** [comment]
I think that it needs something  that stops it from going to a place it just went to without permaban that stop.

**Comment by mhdasding** [comment]
i'll prepare a PR to your fork with some refactor work done

**Comment by JohanJu** [comment]
Added a check for duplicated sniping. 
The logic is based on the assumption that two Pokemon would not disappear on the same millisecond.

**Comment by mhdasding** [comment]
@JohanJu you got a PR ;)
https://github.com/JohanJu/PokemonGo-Bot/pull/1

**Comment by mhdasding** [comment]
We have merge conflicts with the current dev, please merge with it ;)

**Comment by mhdasding** [comment]
damn i feel like Niantic is finally doing something against snipes, i casually get softbanned 😦

**Comment by JohanJu** [comment]
I haven't got softbanned yet, but I got softbaned when restarting the bot as it will teleport to orgin.
I have added you as collaborator can you fix it? I have to go now and I can't see directly what will work.
```
<<<<<<< HEAD
    def _teleport_back(self):
        """Teleports trainer back to their last position."""
        last_position = self.bot.position[0:2]
=======
    def _teleport_back(self, last_position):
        """Teleports trainer back to their last position."""
>>>>>>> 7cc524ed80a918170efcd782829ed6a94e2c4674
        self.emit_event(
            'move_to_map_pokemon_teleport_back',
            formatted=('Teleporting back to previous location ({last_lat}, '
                       '{last_lon})'),
            data={'last_lat': last_position[0], 'last_lon': last_position[1]}
        )
<<<<<<< HEAD
        self.bot.api.set_position(last_position[0], last_position[1], 0)
=======
>>>>>>> 7cc524ed80a918170efcd782829ed6a94e2c4674
```

**Comment by mhdasding** [comment]
sure

**Comment by JohanJu** [comment]
We probably shoulden't merge this. Too many softbans

**Comment by mhdasding** [comment]
nah i think they fixed sniping server side, multiple issues popped up regarding this. this PR is still valuable because it can walk to lured pokemon

**Comment by TheSavior** [comment]
Is this PR still valuable? Sorry it has taken so long to look at it.

**Pull request closed without merging**
