### PR TITLE
Python 3 Compatibility

### PR DESCRIPTION
**Pull request by JSchwerberg**
Short Description: 
Uses a combination of future/past, builtins, and six to achieve full Python 2 and 3 cross-compatibility.

### CODE REVIEW

**Comment by douglascamata** [comment]
@JSchwerberg bot is back up... can you solve merge conflicts, man? :D

**Comment by JSchwerberg** [comment]
@douglascamata We're good, but unfortunately, `pgoapi` is no longer py3 compatible.  I'll have to take a look and see if I can get a PR approved over there.

**Comment by k4n30** [comment]
@JSchwerberg this merge is severly outdated. How do you want to proceed?

**Comment by JSchwerberg** [comment]
@k4n30 Please see my comment above re: pgoapi.  And frankly, after getting this merge up to date three times, getting the merge conflicts resolved, and then having to redo it for some major push, I'm not rushing to get this done yet again; especially if it means figuring out why pgoapi is broken now.

I will close this issue, and rebase from dev if I decide to reapproach this.

**Pull request closed without merging**
