### PR TITLE
Allow to customize quality of pokeball throws

### PR DESCRIPTION
**Pull request by Likael**
**_WARNING:_**
The  code below is safe to use.
However, I tried to test further the possibilities of the field _normalized_hit_position_, and, coincidence or not, couldn't log again with my account any more for 1 hour immediately after sending a weird value. If you want to proceed and modify _normalized_hit_position_ to test randomization, be careful.

**Short Description:** 
The code allows to modify the frequency of the various throw possibilities.
For example, with the following setting : 
"catch_throw_parameters": {
	  "excellent_rate": 4,
	  "great_rate": 10,
	  "nice_rate": 4,
	  "normal_rate": 2,
	  "spin_success_rate" : 0.6,
	}
The bot would have 4 chances out of  20 (4+10+4+2) to land an _Excellent_ throw.
In the sample config, those value add up to 1 to look like percentage, but the user is free to set the values to what speaks most to him/her.
The _spin_success_rate_ is a percentage of landing a successful spin. In the example above, the bot has 60% chance of landing a spin that will generate the bonus exp. 

**More information about the _normalized_hit_position_ :** 
The code below should work safely as it doesn't contain the further tests i have tried, however my paranoid nature would ask for people to test with account they don't care about for 1 day before merging it. I will do so myself tomorrow too. Since the (unban?) I have been testing the code below, and got no further problem.
The value of 0 for _normalized_hit_position_  is safe, as it was what we were sending before I correct the API call.
The value of 1.0 is also safe, as we used it forever.
I didn't test any values between 0 et 1.
Values above 1 seems to be what could have caused the potential temporary ban.
The last case don't happen with this code, as the value is set either to 0 or 1.

**Fixes:**
- #2250

### CODE REVIEW

**Comment by pokecunt** [comment]
download

**Comment by douglascamata** [comment]
@Likael please check how to put all the settings you add properly inside another key in the setup. The websocket settings are a good example.

**Comment by Likael** [comment]
@douglascamata I need your help here, I must be missing something. I can't find the websocket settings (other than the key _websocket_server_).
I packed all the settings under the key _catch_throw_parameters_. The key itself is at the base of the config, mainly because : 
- I couldn't put it in a task, as this config is used by an undeclared worker, instanced by both _CatchVisiblePokemon_ and _CatchLuredPokemon_.
- I did not wanted to put it in the _Catch_ key, as it is used a list of pokemons with a default _any_ and additional keys there could be confusing.

I will be happy look at the websocket settings if you can guide me to it, and revise the settings to make it look more like it.

**Comment by douglascamata** [comment]
@Likael this config:

```
add_config(
        parser,
        load,
        short_flag="-ws",
        long_flag="--websocket.server_url",
        help="Connect to websocket server at given url",
        default=False
    )
```

Automatically translates to a variable named `websocket_server_url`, which in the JSON configuration will be used like this:

```
"websocket": {
    "server_url": "my websocekt url"
}
```

This way you don't need any `.get` call or to mess with dicts. (:

**Comment by RedViper9** [comment]
This is great! Can't wait.

Would it be possible to randomize these parameters such that Excellent throws are made 15-20% of the time, for example?

**Comment by Likael** [comment]
@douglascamata Excellent! I must have missed it. I am on it.
@RedViper9 That's exactly what it will used too :) Defining your own odds for throw quality to be used.

**Comment by Likael** [comment]
OK rebase went wrong. Will fix that tomorrow.

**Comment by Likael** [comment]
Closing pull request to reopen a new clean one

**Pull request closed without merging**
