### PR TITLE
Make PokemonGo-Bot Significantly Better

### PR DESCRIPTION
**Pull request by nickhudkins**
Short Description: 
It makes it better

Fixes:
- deletes everything and tells players to go outside.
- ensures people get fresh air.
- doesn't cheat.

### CODE REVIEW

**Comment by datwheat** [comment]
What if they live in China? Not much fresh air there :P

**Comment by marcshilling** [comment]
Been waiting for this feature! Please merge!

**Comment by douglascamata** [comment]
Closed because people have the freedom to do whatever they want.

**Comment by srg2k5** [comment]
But no, if you don't do it his way, you are obviously doing it wrong.  His way is better, he made that point clear.

**Comment by phrojoe** [comment]
Would you consider reopening this PR? There's a lot of good changes here you might be able to cherry pick.

**Pull request closed without merging**
