### PR TITLE
Revert "Removing duplicated release logic from catching pokemon"

### PR DESCRIPTION
**Pull request by surfaace**
Reverts PokemonGoF/PokemonGo-Bot#1160

Reverted because without this pokemon isnt released if having evolve_captured : false.
until seperate release_pokemon_worker is done code needs to be in

### CODE REVIEW

**Comment by douglascamata** [comment]
@surfaace There is the `InitialReleaseWorker` that can be updated and renamed to `ReleaseWorker`

**Comment by douglascamata** [comment]
I don't think reverting was a good idea. Improving `InitialReleaseWorker` is.

**Comment by surfaace** [comment]
until InitialReleaseWorker is fixed, we should be able to transfer away pokemons based on filter when catched, else we causes us a 'bug'

**Comment by douglascamata** [comment]
@surfaace so why not fix the bug instead of reverting a good refactor?

**Comment by surfaace** [comment]
it wasnt a bug before you removed the code :) modifying workers now

**Pull request merged**
