### PR TITLE
Stepper fix

### PR DESCRIPTION
**Pull request by Phil9l**
Fixes:
- Using `os.path.join` instead of `/` in file paths,
- Handling location files opening with `try`

### CODE REVIEW

**Comment by douglascamata** [comment]
LGTM

**Comment by solderzzc** [comment]
@douglascamata you up Lmao.

**Comment by douglascamata** [comment]
@solderzzc lol, I'm excited to work.... LET'S WWWWOOOORK!

**Comment by douglascamata** [comment]
DLGTMA (doesn't look good to my anymore)

**Comment by Phil9l** [comment]
@douglascamata,why doesn't?

**Comment by douglascamata** [comment]
@Phil9l because you have a merge conflict with `dev` branch. You need to `git pull origin dev` and fix the conflicts.

**Comment by Phil9l** [comment]
@douglascamata, updated. No conflicts now.

**Comment by douglascamata** [comment]
@solderzzc please review again, now it definitely LGTM.

**Comment by douglascamata** [comment]
@Phil9l fuck the police, man, I'm merging you.

**Pull request merged**
