### PR TITLE
Egg Incubation - IV fix and UnboundLocalError fix

### PR DESCRIPTION
**Pull request by reddivision**
Short Description: 
Some small fixes to incubate eggs worker for egg hatching, as well as egg hatching detection
Fixes:
- IVs out of order compared to webui - they now match A/D/S format (added calculated decimal value as well for consistency)
Sample of new output with cp %
- mitigation for pokemon_data sometimes not initialized due to bad `_check_inventory` call
- custom log message and early return for conditions where hatched pokemon not received from api or identified
- added temp lists to check inventory call to mitigate incubator list duplication seen for some users

### CODE REVIEW

**Comment by Nihisil** [comment]
This changes fixed an issue. At least for me it is hatching eggs again.

**Comment by reddivision** [comment]
renamed for better visibility (hopefully) to prevent more duplicate PRs

**Comment by knobunc** [comment]
Works well for me when applied on 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

**Comment by douglascamata** [comment]
@reddivision please fix conflicts so I can merge.

**Comment by douglascamata** [comment]
👍

**Comment by TheSavior** [comment]
:+1:

**Pull request merged**
