### PR TITLE
Merge dev to master

### PR DESCRIPTION
**Pull request by pogarek**
@solderzzc If I/we shouldn't do the marge to master, let me/us know. In the meantime - trying.

### CODE REVIEW

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
All clear. Test passed, approved by comment and in pullapprove, but button is disabled :-) So @solderzzc , it awaits for you :)

**Comment by solderzzc** [comment]
Anyone in the team comment a 👍  will green the button :)

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
@pogarek you can 'Merge the pull request' for now :)

**Comment by pogarek** [comment]
@solderzzc thanks for explanation and approval. 
However the Merge button is still gray for me :-)

**Comment by solderzzc** [comment]
。。。。

**Comment by solderzzc** [comment]
@pogarek  I just checked the settings and modified, the next button will be green then...

**Comment by pogarek** [comment]
thanks a lot!

**Comment by solderzzc** [comment]
you are welcome :)

**Pull request merged**
