### PR TITLE
[README] Setting up a simple webserver

### PR DESCRIPTION
**Pull request by s1x**
Short Description:  Added description of setting up a simple webserver

### CODE REVIEW

**Comment by jtdroste** [comment]
q_q

that removed my name from the contributors section.  Anyway, I think this will be better off in the wiki - maybe called "Advanced Installation" or something

**Comment by ferbeb** [comment]
Just what I was looking for when I randomly clicked on this pull request. Certainly would not have found it in the wiki.

**Comment by aditardy** [comment]
i start my webserver end change web directory but not see anyting just  option OAN and zoom
run multiple id on bot ... this posible to show on map .. ? or bug ..?

**Comment by s1x** [comment]
@aditardy Thats releated to the map feature of this bot, not to the webserver itself. Check your .json for the correct username.

**Comment by aditardy** [comment]
@s1x  thanks !   <3

**Comment by haykuro** [comment]
FYI, nginx is one of many ways to setup a webserver..

Could even just do `python -m SimpleHTTPServer 8000` and it will run a server on port 8000.

**Comment by s1x** [comment]
@haykuro Totally true!

**Comment by solderzzc** [comment]
I'm confusing why this commit has no conflict, it was 12hrs ago !@!

**Pull request merged**
