### PR TITLE
fixing loop in spin fort task (need to update forts timeout list)

### PR DESCRIPTION
**Pull request by douglascamata**

### CODE REVIEW

**Comment by TheSavior** [comment]
:+1:

**Comment by solderzzc** [comment]
👍

**Comment by BriceSD** [comment]
@douglascamata Sometimes bot got stuck an go back and forth between 2 forts. Commenting these lines make it works, uncommenting them breaks it again.
Tping far away solve the issue.

**Comment by douglascamata** [comment]
@BriceSD it's probably a configuration problem. I use latest dev all the time, 24/7, and it works pretty well.

**Comment by BriceSD** [comment]
@douglascamata See #3514

**Pull request merged**
