### PR TITLE
Telegram fix

### PR DESCRIPTION
**Pull request by javajohnHub**
a couple of tweaks to get telegram working correctly

### CODE REVIEW

**Comment by javajohnHub** [comment]
Sorry.

**Comment by javajohnHub** [comment]
Should the default events be disabled and only allow subscriptions. Right now it auto displays a few events.

**Comment by solderzzc** [comment]
I like to have default event to send, manually sub cause much effort which I don't like to use.

**Comment by javajohnHub** [comment]
Fixes #5396

**Comment by solderzzc** [comment]
👍

**Pull request merged**
