### PR TITLE
Clarify the usage part to launch the bot

### LINKED ISSUE #972: sorry but I can't use it easily on my mac
how can I run the Bot on my mac ?
after install , I don't find the way to startup

### PR DESCRIPTION
**Pull request by tspoke**
Hi,

Just a quick fix to the readme to clarify the usage of the Bot.

Fix #972 #998

### CODE REVIEW

**Comment by VictorChen** [comment]
I think there's a run script now?

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/run.sh

**Comment by surfaace** [comment]
if config should be defined it should be with -cf or --config-file

Update your PR and we can merge it

**Comment by tspoke** [comment]
PR updated.
I didn't see the run.sh file, sorry for that. I added the run.sh too.

**Comment by solderzzc** [comment]
Sure, thanks @surfaace @tspoke

**Pull request merged**
