### PR TITLE
pokemon catcher interface for https://github.com/AHAAAAAAA/PokemonGo-Map

### PR DESCRIPTION
**Pull request by GNSPS**
**Short Description:**

This PR has a whole new worker to interface with https://github.com/AHAAAAAAA/PokemonGo-Map and go after rare pokemons (specified in the configs by id) found in the map.

When it is working it stops the move_to_fort worker because the pokemons have a limited lifetime and the bot cannot run the other worker simultaneously.

_Fixes_:
- No fixes, just a new  feature

### CODE REVIEW

**Comment by GNSPS** [comment]
Fixing the conflicts which I didn't notice but broke it all!

**Comment by DayBr3ak** [comment]
Don't merge, rebase

**Comment by Anakin5** [comment]
max_travel_time  seems to be seconds. So the needed_speed is in distance_unit / seconds.
So I guess 30 cannot be the default value.

**Comment by Anakin5** [comment]
Also, I think such mechanism should check pokemon cp / iv to make sure we don't run for a pokemon that we are going to release.

**Comment by GNSPS** [comment]
Yes, you're right!

30 m/s was what I was using in the tests which is 108 km/h it is a bit fast but on the other hand really rare pokemons tend to spawn far away if you let the task define the needed speed you take ages to reach the desired pokemon and cannot move to forts at the same time.

So it's kind of a difficult choice!

**Comment by GNSPS** [comment]
Nice point! Going to add that when I can.

For now let's assume you'll only use this for VIP pokemons in your config!

**Comment by Anakin5** [comment]
We could configure the minimum and maximum speed.
Bot would try to reach the pokemon at the necessary speed to catch it (with a buffer for capture). If that speed is less than the minimum in config, use the minimum. If that speed is greater than the maximum, consider you cannot reach that pokemon in time.

**Comment by GNSPS** [comment]
That is exactly what is happening the speed in the config is the minimum speed. The maximum is the 120 km/h which is tested by the pokemongo-webspoof guys!

But no harm in making the max configurable too! 😄

**Comment by Anakin5** [comment]
On detail is that we do not check the speed in get_nearest_pokemon. So we  might return an encounter that is not reachable. That would be good to filter out all encounter not reachable at max speed.

**Comment by GNSPS** [comment]
Right! important point!
Better than filter out one for each run of the worker

**Comment by douglascamata** [comment]
@GNSPS please, also use a task config, like the `IncubateEgg` task does. We do not add config like that anymore, it's being deprecated.

**Comment by nikhil-pandey** [comment]
Is this ~same to #1992 ?

**Comment by Anakin5** [comment]
There is other pull requests to take into account:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1992
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1887

**Comment by GNSPS** [comment]
I thought about #1992 but that way you can't connect to an external server and this way you can

**Comment by douglascamata** [comment]
@GNSPS you redid the whole work just to be able to connect to an external server? This is easy to implement there.

**Comment by douglascamata** [comment]
@GNSPS also, tasks don't store state in `self.bot`, they store state in themselves now.

**Comment by GNSPS** [comment]
No! I didn't see #1992, I was just saying I thought of that method and it wasn't as effective!

Gonçalo

----------
Sent from my mobile,
please excuse brevity & typos

**Comment by mhdasding** [comment]
@GNSPS it's the same, i forgot to update the description to reflect the change that it now parses the spawns from /raw_data of PokemonGo-Map ;)

**Comment by GNSPS** [comment]
Ok! ;)

Closing this now!

**Pull request closed without merging**
