### PR TITLE
change the access to the response hash

### PR DESCRIPTION
**Pull request by sebyx07**
The api from pokemon go changed, but the data from the GET_INVENTORY is gone

### CODE REVIEW

**Comment by solderzzc** [comment]
I'm not quite sure what this for..

**Comment by solderzzc** [comment]
👍

**Comment by TheSavior** [comment]
I don't understand. If this stuff was changed, wouldn't we all see the broken behavior? Mine prints my account creation time on startup implying this is a non issue.

**Comment by solderzzc** [comment]
From my side, the print has error.
Should we try to protect both working?
I'm using PTC account.

**Comment by solderzzc** [comment]
`
[2016-07-24 18:16:29] 
Traceback (most recent call last):
  File "pokecli.py", line 222, in <module>
    main()
  File "pokecli.py", line 208, in main
    bot.start()
  File "/Users/simba/Projects/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self._setup_api()
  File "/Users/simba/Projects/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 153, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
`

**Comment by TheSavior** [comment]
I'm using PTC too. We should get more input from people on slack. I'd be worried that we fix this for a few people and break this for many.

**Comment by solderzzc** [comment]
@sebyx07  Could you changed to support both format, I guess the servers will not change at the same time.

**Comment by solderzzc** [comment]
It caused by existing  pgoapi
`
rm -rf pgoapi/
`

**Comment by solderzzc** [comment]
It caused by switching from main branch without rm pgoapi.

 rm -rf pgoapi/ 
Solved my issue, please reopen if still an issue.
Let me close here.

**Pull request closed without merging**
