### PR TITLE
Resolve issue #4227 - MoveToMapPokemon stop catching when VIP

### PR DESCRIPTION
**Pull request by sohje**
## Fixes/Resolves/Closes (please use correct syntax):
- #4227 
- When using move_to_map_pokemon if vip pokemon around, go to that pokemon, skip all forts and appeared pokemons.

p.s. works fine for me already for 5h (3 bots)

### CODE REVIEW

**Comment by BreezeRo** [comment]
Looks good to me, anyone else?

**Comment by solderzzc** [comment]
Yes, this is good.

**Comment by solderzzc** [comment]
:

**Comment by solderzzc** [comment]
👍

**Comment by thereyrey** [comment]
Yaay great! Thanks!

**Pull request merged**
