### PR TITLE
Update pokemon_catch_worker.py

### PR DESCRIPTION
**Pull request by ravenstar**
Short Description: 
A variable was removed in one of the previous commits. This PR re-adds the missing variable.

Fixes:
- Fixed missing variable.

### CODE REVIEW

**Comment by ibarria0** [comment]
A bug indeed but PR is incoming which fixes this and adds some logic to the pokemon transfer

**Comment by rkodali22** [comment]
This is the exact same change as Pull #254

**Comment by douglascamata** [comment]
list is empty, btw

**Comment by ravenstar** [comment]
Sorry, didn't realise this was a duplicate PR.
Closed, will await resolution of PR #254

**Pull request closed without merging**
