### PR TITLE
Wrong character used.

### PR DESCRIPTION
**Pull request by LuckyMe4Evers**
## Short Description:
Wrong character used.
## Fixes/Resolves/Closes (please use correct syntax):
- Changed ) to }

### CODE REVIEW

**Comment by LuckyMe4Evers** [comment]
Can this be merged asap ? Ppl having problems with login if they use the configurator !

**Comment by LuckyMe4Evers** [comment]
@mjmadsen can you reopen this and merge it? One was for dev and one was for master. Can't see for what this 
one was because i'm on mobile.

**Comment by LuckyMe4Evers** [comment]
This one is for dev

**Comment by mjmadsen** [comment]
Doh.

**Comment by mjmadsen** [comment]
:+1:

**Pull request merged**
