### PR TITLE
[dev] Fetch altitude with geocoder

### LINKED ISSUE #2762: Use the latitude and longitude to get the altitude from Google
look is time to remove zero 'altitude' here&there and check position

exemple: step_walkwe.py line 41 set alt to zero ?
other

https://github.com/PokemonGoF/PokemonGo-Bot/search?utf8=%E2%9C%93&q=position
and set alt in config?

### PR DESCRIPTION
**Pull request by mjmadsen**
Not ready to merge. Please take a look and give some notes. 

Closes #2762

### CODE REVIEW

**Comment by net8q** [comment]
I'd suggest adding randomness/GPS noise and caching requests for an area

**Comment by solderzzc** [comment]
Agreed with @net8q , if no Google API configured or out of quota, should use randomness GPS noise.

**Comment by solderzzc** [comment]
@mjmadsen  Will you submit the Geo code later?

**Comment by mjmadsen** [comment]
Yeah, I have a few bits I need to figure out. Any recommendations are welcomed.

**Comment by solderzzc** [comment]
At least we can have random first.
Geocoder is advantage setup depends on the Google map api. 
Both are much better than a Zero.

**Pull request closed without merging**
