### PR TITLE
Merge pull request #1 from PokemonGoF/dev

### PR DESCRIPTION
**Pull request by vixxxx**

### CODE REVIEW

**Comment by MerlionRock** [comment]
Can explain what is this?

**Comment by Jcolomar** [comment]
@vixxxx if u dont explain what is this pr we will close it

**Comment by MerlionRock** [comment]
PR closed.
(No reason given because no description given)

I'm trying to have a sense of humour....

**Comment by MerlionRock** [comment]
PR closed.
(No reason given because no description given)

I'm trying to have a sense of humour....

**Pull request closed without merging**
