### PR TITLE
Legal Information Updates / Master Branch

### PR DESCRIPTION
**Pull request by GitPupper**
#4002

### CODE REVIEW

**Comment by douglascamata** [comment]
👍

**Comment by BriceSD** [comment]
Shouldn’t you make a PR in dev rather than master ? Should’ve deleted this one and keep #4035 imo

**Comment by douglascamata** [comment]
@BriceSD but should we really merge dev into master right now?

**Comment by BriceSD** [comment]
@douglascamata  Already one opened. Got some issues because master is ahead dev. Merging this into master will make things worst #3988

**Comment by GitPupper** [comment]
Alright. I'll implement this into the other readmes of the other Repositories so we don't get our asses sued.

**Pull request closed without merging**
