### PR TITLE
Fix walking speed as suggested in #1586

### PR DESCRIPTION
**Pull request by klingan**
Short Description: Fixes the slow speed of walking if evolve is turned on
Fixes:
-  Walking is at normal speed again instead of crawling

### CODE REVIEW

**Comment by douglascamata** [comment]
@klingan what consequences does patch has to `EvolveAllWorker`? I don't want to read that code, it's a complete mess and should be rewritten.

**Comment by mrseeker** [comment]
That it won't run constantly, only once (during game tick 0). If this setting is kept to True, it will keep itself running (and causing a huge lag).

**Comment by douglascamata** [comment]
I'm inclined to no accept this. Because `evolve_all` can also be configured to evolve only certain pokemon and should also work if there's no lucky egg available....

**Comment by douglascamata** [comment]
Also this worker shouldn't release pokemon... Oh, what a mess.

**Comment by bigkraig** [comment]
not sure if its related, but checking on lucky eggs all of the time seems to be spamming my log

[15:47:50] No lucky eggs... skipping evolve!
[15:47:56] Moving towards fort 3e39a69af6e9439cb48dbfa1db080ca1.16, 0.16km left
[15:48:00] No lucky eggs... skipping evolve!
[15:48:06] Spinning ...
[15:48:06] Loot: 
[15:48:06] 50 xp
[15:48:07] - 3x Pokeball (Total: 103)
[15:48:07] PokeStop on cooldown. Time left: 5 minutes, 28 seconds
[15:48:09] Moving towards fort 3e39a69af6e9439cb48dbfa1db080ca1.16, 0.14km left
[15:48:13] No lucky eggs... skipping evolve!
[15:48:14] -- Recycled 3x Pokeball (keeps only 100 maximum) 
[15:48:20] Moving towards fort 3e39a69af6e9439cb48dbfa1db080ca1.16, 0.13km left
[15:48:24] No lucky eggs... skipping evolve!
[15:48:30] Moving towards fort 3e39a69af6e9439cb48dbfa1db080ca1.16, 0.11km left
[15:48:34] No lucky eggs... skipping evolve!
[15:48:40] Moving towards fort 3e39a69af6e9439cb48dbfa1db080ca1.16, 0.09km left
[15:48:45] No lucky eggs... skipping evolve!
[15:48:51] Moving towards fort 3e39a69af6e9439cb48dbfa1db080ca1.16, 0.08km left
[15:48:55] No lucky eggs... skipping evolve!

**Comment by douglascamata** [comment]
WHO WANTS TO REFACTOR WHOLE EVOLVE LOGIC?!

**Comment by BobbyWibowo** [comment]
Ah. That explains why my bot wouldn't move for minutes..

**Comment by mrseeker** [comment]
Fixed with pull #1774

**Pull request closed without merging**
