### PR TITLE
Better enforce rules about Pokemons to retain.

### PR DESCRIPTION
**Pull request by giomasce**
Rules about maximum CP and IV to transfer Pokemons are applied
also when keeping the best ones.

### CODE REVIEW

**Comment by douglascamata** [comment]
@giomasce did you test?

**Comment by giomasce** [comment]
I am using this change right now (three parallel bots) and it appears to work. It does what I expect it to do.

**Comment by douglascamata** [comment]
👍

**Comment by solderzzc** [comment]
👍

**Comment by matrix14** [comment]
Can you explain how to use it? 

I want to have all pokemons above 500 CP, but when I have pokemon under 500CP i want to keep best.
Is it possible?

**Comment by giomasce** [comment]
@matrix14 Yes, that is how it is meant to be used.I have this release rule:

    "any": {"release_below_cp": 400, "release_below_iv": 0.8, "logic": "or", "keep_best_iv": 2},

It means: always keep the best two Pokemons by IV. Release the others, but only if they are below 400 CP or 0.8 IV.

**Comment by mzygmunt** [comment]
@giomasce I think the logic of this feature should be:
Release all Pokes if they are below 400 CP or 0.8 IV and keep only 2 by IV from the rest.

**Comment by valerian** [comment]
@mzygmunt @giomasce 
The problem is that it's hard to interpret by simply reading the rule if you don't know how it's supposed to work in detail, and that's why I was told that such a feature wouldn't be done yet.
And then it was done anyway, and with a bug :/

**Comment by mzygmunt** [comment]
@valerian Those features are important for account with 25 levels or above, when we want to catch a lot of good Pokes while XP'ing. I know that, the features might be difficult to be done without config complication, but I think, is worth spending it for bot progress.

**Comment by bixuanzju** [comment]
@mzygmunt Reading from [here](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/transfer_pokemon.py#L17), @matrix14 is right about interpreting the logic: when you have both ""release_below_x" and "keep_best_x", the bot filters the best pokemons to keep, and then for the rest, apply the logic of "release_below_x" to decide the set of pokemons to release.

**Pull request merged**
