### PR TITLE
Merge Dev to Master

### PR DESCRIPTION
**Pull request by MerlionRock**
Changes since last master merge:

- Fixes login issues
- Added Enable option to Followpath
- Deploying of lures.  Add "use_lure": true to "SpinFort" task to enable it
- 2Captcha Solving
- Manual Captcha Solving
- Mobster, hunt family members of VIPs
- Trash Hunting, hunt down trash Pokemon

### CODE REVIEW

**Comment by MerlionRock** [comment]
Do you all want to merge this?

**Comment by davidakachaos** [comment]
Sure? 😄

**Comment by MerlionRock** [comment]
If recent changes are okay, merge it. Recent changes useful :)

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
I will wait for the travis, then merge it.

**Pull request merged**
