### PR TITLE
Fix issue -if not working properly #517

### PR DESCRIPTION
**Pull request by budi-khoirudin**
Short Description: 
Fixing bugs issue, change list type to str

### CODE REVIEW

**Comment by solderzzc** [comment]
Need modify README.me together please.

**Comment by budi-khoirudin** [comment]
@solderzzc  Done , i have been modify README.md and config.json.example

**Comment by solderzzc** [comment]
conflict need to be fixed...

**Comment by budi-khoirudin** [comment]
@solderzzc  Done, the conflict has been fixed

**Comment by solderzzc** [comment]
We need more +1 since this is interface changed.

**Comment by budi-khoirudin** [comment]
@solderzzc  what you mean, need more +1 ? i don't understand?

**Comment by solderzzc** [comment]
Since the command line changed, we need more users to be notified. I know this is a good patch, but please join our slack, to notify users first, if they have +1 on this thread, that mean they are notified. 
This is what I mean.
Our code is being stable, so the interface changes need to be very careful.

**Comment by budi-khoirudin** [comment]
@solderzzc  okay, i'm already join to slack in channel #general , so what i must do next? i ask for +1 , but no one notice .

**Comment by solderzzc** [comment]
ok, let me merge your code. Thanks. Since the document is very good.

**Comment by solderzzc** [comment]
Another conflicts... sorry about that.

**Comment by budi-khoirudin** [comment]
@solderzzc  Done, fix the conflict

**Pull request merged**
