### PR TITLE
Update to sniper fixname method

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:

-Fixed issue where bot may crash if name == None supplied to fixname()
-Added Nidoran M/F

## Fixes/Resolves/Closes (please use correct syntax):

-#5652

### CODE REVIEW

**Comment by Anakin5** [comment]
If you need something more generic to fix names, there is https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/pokemon_optimizer.py#L314

**Comment by Gobberwart** [comment]
Nice @Anakin5... I'll try that and see if it works better.

**Comment by Gobberwart** [comment]
@Anakin5 Doesn't work so well...

Unknown Pokemon name [%s]. Assuming it is [%s] mr-mime Grimer

I'm going to stick with fixname, but add closest_name as a backup just in case we haven't explicitly defined something.

Result:

Unknown Pokemon name mr. mime. Assuming it is Mr. Mime

**Comment by Anakin5** [comment]
Yes the match works better when using lowercase for all names. Not sure about Nidoran Unicode though.

**Comment by Gobberwart** [comment]
I haven't seen it myself, but another user tested them and it works.

**Comment by Gobberwart** [comment]
Ditching this as commits have gotten out-of-hand (git problem?). Will resubmit.

**Pull request closed without merging**
