### PR TITLE
Use Incense worker

### PR DESCRIPTION
**Pull request by davidakachaos**
## Short Description:
I saw a PR a while back (PR #3755) by bmorrise but it was closed, not
sure why (except for some comments)
I'm new at python programming, so I hope I've adjusted the code in this
version well enough.

This will make the bot use the Incense in the bag when it's available.
No pause, no interval, when you have it, use it.

### CODE REVIEW

**Comment by solderzzc** [comment]
@davidakachaos Let's merge for testing.

**Comment by solderzzc** [comment]
👍

**Comment by davidakachaos** [comment]
I will!

**Comment by solderzzc** [comment]
👍 
let's merge for testing.

**Comment by acurioustale** [comment]
Any way to check if incense is already running, before trying to use another?

**Pull request merged**
