### PR TITLE
Adding an Anyball item to the release config

### PR DESCRIPTION
**Pull request by Breakster**
Short Description: 
An extra item type is added: "Anyball". This allow a 'keep' amount of anyball. When the total amount of balls exceeds this number, firstly pokeballs will be removed, then greatballs, and so on. (Also see issue #2070)

Fixes:
- 
- 
-

### CODE REVIEW

**Comment by douglascamata** [comment]
👍 

@TheSavior have a look at this. LGTM,

**Comment by klingan** [comment]
This would certainly minimalize the issue where you stop moving to forts if your limits arent reached yet but your bag is full nevertheless.

**Comment by TheSavior** [comment]
👍

**Comment by klingan** [comment]
So what happened to this? 

pokemongo_bot.tree_config_builder.ConfigException: item Anyball does not exist, spelling mistake? (check for valid item names in data/items.json)

**Comment by Breakster** [comment]
So this one was reverted because there was an error when the key was not present. How to proceed? I still think it's a good feature. Also, it can be extended for potions and heals.

**Comment by TheSavior** [comment]
@Breakster, yeah, a new PR would be great fixing it in a way that doesn't break other things would be great. See the comments on the revert: https://github.com/PokemonGoF/PokemonGo-Bot/pull/2166

**Comment by Breakster** [comment]
I'm on it!

**Pull request merged**
