### PR TITLE
Use higher balls if you do not have lower ones.

### PR DESCRIPTION
**Pull request by giomasce**
At my level I tend to receive often greatballs and use often pokeballs.
So I run out of pokeballs and accumulate a lot of great balls, which I
never use. This changes fixes the problem.

### CODE REVIEW

**Comment by brantje** [comment]
:+1:

**Comment by neox387** [comment]
Something not right here I think ? keeps throwing great balls when I have 0 pokeballs & 0 greatballs but do have some ultra balls.

**Comment by giomasce** [comment]
You're right. Should be fixed now, although I have poke balls now, so I cannot test.

**Comment by giomasce** [comment]
However there is another PR that seems to be doing this thing better.

**Comment by Foxy1990** [comment]
is working fine for me

```
if balls_stock[1] > 0:
                                # print 'use Poke Ball'
                                pokeball = 1

                            if cp > 300 or balls_stock[1] == 0 and balls_stock[2] > 0:
                                # print 'use Great Ball'
                                pokeball = 2

                            if cp > 700 or balls_stock[2] == 0 and balls_stock[3] > 0:
                                # print 'use Utra Ball'
                                pokeball = 3
```

**Comment by solderzzc** [comment]
cleaning up the pull-request folder, please reopen when you done the rebase.

**Pull request closed without merging**
