### PR TITLE
Fix for FileIO slowing bot performance.This puts the map writing into…

### PR DESCRIPTION
**Pull request by ajurna**
Short Description: Makes the large writing of map data happen in an outside thread

Fixes:
Slow map traveling speed.

### CODE REVIEW

**Comment by AcorpBG** [comment]
Testing the change right now. Will report in a bit.

**Comment by AcorpBG** [comment]
Can confirm this is huge increase for me
Before:
2016-08-08 20:09:28,742 [       cli] [INFO] Ran for 2:58:46
2016-08-08 20:09:28,742 [       cli] [INFO] Total XP Earned: 20020  Average: 6719.28/h
After:
2016-08-08 20:58:42,381 [       cli] [INFO] Ran for 0:26:41
2016-08-08 20:58:42,382 [       cli] [INFO] Total XP Earned: 8890  Average: 19987.96/h

Exactly the same config

**Comment by Kassadd** [comment]
>Can confirm this is huge increase for me
Before:
2016-08-08 20:09:28,742 [ cli] [INFO] Ran for 2:58:46
2016-08-08 20:09:28,742 [ cli] [INFO] Total XP Earned: 20020 Average: 6719.28/h
After:
2016-08-08 20:58:42,381 [ cli] [INFO] Ran for 0:26:41
2016-08-08 20:58:42,382 [ cli] [INFO] Total XP Earned: 8890 Average: 19987.96/h

+1, running Raspberry Pi 1B in a SDCard

**Comment by solderzzc** [comment]
Thanks for all your response and test and the PR.

**Comment by solderzzc** [comment]
👍

**Comment by tvpman** [comment]
2016-08-08 14:39:51,873 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'Namespace' object has no attribute 'encrypt_location'", u'  File "pokecli.py", line 502, in <module>', u'  File "pokecli.py", line 133, in main']

HELP?

**Comment by ajurna** [comment]
that error is unrelated to my change. just try again and it should work

**Comment by davidson-git** [comment]
Followed 2811 and 3056 here.  Are any changes to the configs required?  Doesn't look like it from the commit, but I still seem to be moving very slowly, 40 min to move a block at walk = 5.02

**Comment by ajurna** [comment]
This should decrease the time between ticks. this is only really an issue if you have fileio problems.
it doesnt really effect the walk speed. you coiuld try upping that.

**Pull request merged**
