### PR TITLE
Fix config.json.pokemons.example release config

### PR DESCRIPTION
**Pull request by alvarogzp**
Properties in the json were `release_under_cp` and `release_under_iv`, but code is searching for `release_below_cp` and `release_below_iv`, so this was not working if used by users.

### CODE REVIEW

**Comment by alvarogzp** [comment]
Modified also evolve_all_worker to use `release_below_cp` and `release_below_iv` too.

There are no more places where `release_under_cp` and `release_under_iv` are used.

**Comment by alvarogzp** [comment]
Same with cp_iv_logic to logic, as seen in #947

**Comment by douglascamata** [comment]
Looks good to me.

**Comment by solderzzc** [comment]
Thanks.

**Pull request merged**
