### PR TITLE
Reduce API calls

### LINKED ISSUE #4754: Decoupling and refactoring
Our task order is currently static. Some of our tasks need to be performed on a state change. My thoughts that turn into ramblings:

- We should always try to collect level up rewards on exp change
- We should always check for badge responses (on each heartbeat?)
- Our API requests should be detached from bot decisions (store what we want locally, but only send recent when a response is required)
- Move emit calls to centralized place (store emit requests from each task). Allows for easier configuration, decouples task config from log config. 
- Move delay times and sleep features to centralized place. Same as above, we repeat too many (similar kinds of) waits and make our config entirely too long. 
- Too many parts of code that are trying to accomplish the same thing. Between catch_pokemon, pokemon_catch_worker, map_move_to_pokemon we repeat much of the code. Plus map_move_to_pokemon changes position and initiates capture attempts (and checks balls). All capture attempts should be force through our catch_pokemon task first (with refactor to implement order logic of map_move_to_pokemon). pokemon_catch_work should be the only one checking balls of them. 

I'll stop for now. My idea is, some files do too much that other files should and some files just too much in general.

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:
Some refactoring and updates to reduce api calls and json file writes/reads. 

Metrics and UpdateWebInventory now use cached inventory instead of api call (except "player_data" in metrics, which still needs a call at this stage.

GET_INVENTORY api call performed during heartbeat instead of during other class methods.

Removed some redundant code

## Fixes/Resolves/Closes (please use correct syntax):
- Partially fixes #4754
- Improves on changes made in #4877

### CODE REVIEW

**Comment by duttonw** [comment]
@Gobberwart  You may want to rebase your work to be above current dev branch so that it does not include extra commits not related to your changes.

**Comment by Gobberwart** [comment]
@duttonw I've tried that and it claims to be rebased but those commits still show up. Any suggestions (sorry, new to git)

**Comment by Gobberwart** [comment]
I'm told I can ignore all those commits, since the files changed is correct. I'll look into it after this PR is done.

**Comment by duttonw** [comment]
@Gobberwart maybe for future reference. on what i've found

if its too hard then just create a new branch from dev say named reduce_api_calls then rebase your previous branch onto it.

git stash push
git checkout dev
git checkout -b reduce_api_calls
git diff reduce_api_calls...dev-playerdata <!-- this shows what actual difference there are, if there is more than your changes sadly you may need to manually diff.
git rebase dev dev-playerdata

hopefully thats only placed the commits it needs on top of dev and removed all of the merges but do diff post rebase to see if the only changes from dev is what you really want to change.

if you are uncomfortable with the rebase option since you have done alot of merges already, and if you have meld or pycharm or other diffing program around you could copy dev-playerdata files only (not the .git) then diff on top of reduce_api_calls. This is from days past with svn or other versioning where you want to see what acually changed before you are ready to commit.

git checkout dev-playerdata
cp -rf pokemongo_bot ../dev-playerdata-old
git checkout reduce_api_calls
meld ../dev-playerdata-old pokemongo_bot <!-- do your merges on the files you touched
git add ${file list}
git commit ${i did x y z}
git push gobberwart reduce_api_calls
rm -rf  ../dev-playerdata-old
create pull request with fresh clean branch.

next time you create a branch and its out of date with dev instead of just doing git pull origin dev
to git pull --rebase origin dev

this will take your previous commits and place them on top of the head of dev just like you did your work on the least checkout and no one else committed yet.

http://gitready.com/advanced/2009/02/11/pull-with-rebase.html

**Comment by Gobberwart** [comment]
@duttonw Thanks for that, I'll do that with my next one.

**Comment by mjmadsen** [comment]
@Gobberwart can you merge dev. Just pushed a few other that look like they edited similar files.

**Comment by Gobberwart** [comment]
@mjmadsen Done, mate.

**Comment by mjmadsen** [comment]
:+1:

**Pull request merged**
