### PR TITLE
Introducing HealPokemon

### PR DESCRIPTION
**Pull request by davidakachaos**
HealPokemon will try to use the potions and revives to heal and revive your Pokemon
This does so without any filtering. Usefull when you get home from a raid and dont want
to heal/rivive all the Pokemon yourself. This will try to do so as effectently as possible.

### CODE REVIEW

**Comment by goedzo** [comment]
Did you make a typo in the config sample?

+### Sample configuration
+[[back to top](#table-of-contents)]
+```json
+{
+    "type": "BadPokemon",
+    "config": {
+        "enabled": true,
+        "heal": true,
+        "revive": true
+    }
+}

Shouldn't it say, HealPokemon?

**Comment by davidakachaos** [comment]
Haha, oops. Will fix that...

Op 17 jul. 2017 19:33 schreef "goedzo" <notifications@github.com>:

**Comment by goedzo** [comment]
This code crashes when reviving:
Traceback (most recent call last):
  File "pokecli.py", line 885, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 830, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/heal_pokemon.py", line 66, in work
    self._revive_pokemon(pokemon)
  File "/usr/src/app/pokemongo_bot/cell_workers/heal_pokemon.py", line 101, in _revive_pokemon
    'name': pokemon.name
  File "/usr/src/app/pokemongo_bot/base_task.py", line 43, in emit_event
    data=data
  File "/usr/src/app/pokemongo_bot/event_manager.py", line 56, in emit
    raise EventNotRegisteredException("Event %s not registered..." % event)
pokemongo_bot.event_manager.EventNotRegisteredException: Event revived_pokemon not registered...

**Comment by goedzo** [comment]
Note: fixed all issues in: https://github.com/PokemonGoF/PokemonGo-Bot/pull/6090

**Comment by MerlionRock** [comment]
@goedzo thanks.

**Comment by MerlionRock** [comment]
@goedzo You fixed the issue, but you didn't touch the documentation right?
@davidakachaos Should also add the new config into config.json.example

**Comment by MerlionRock** [comment]
Also, after I healed with one potion, it failed to use a second one. It gives somethings like:

```
[2017-07-18 11:16:47] [MainThread] [HealPokemon] [INFO] Healing 4 pokemon
[2017-07-18 11:16:59] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 26 left.
[2017-07-18 11:17:01] [MainThread] [HealPokemon] [INFO] Healing Dragonite (57 -> 257/114).
[2017-07-18 11:17:05] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 25 left.
[2017-07-18 11:17:07] [MainThread] [HealPokemon] [INFO] Can't use this to heal the Dragonite
[2017-07-18 11:17:07] [MainThread] [HealPokemon] [INFO] Failed with potion 103. Trying next.
[2017-07-18 11:17:17] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 25 left.
[2017-07-18 11:17:19] [MainThread] [HealPokemon] [INFO] Healing Blissey (179 -> 379/358).
[2017-07-18 11:17:21] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 24 left.
[2017-07-18 11:17:24] [MainThread] [HealPokemon] [INFO] Can't use this to heal the Blissey
[2017-07-18 11:17:24] [MainThread] [HealPokemon] [INFO] Failed with potion 103. Trying next.
[2017-07-18 11:17:32] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 24 left.
[2017-07-18 11:17:34] [MainThread] [HealPokemon] [INFO] Healing Lapras (87 -> 287/174).
[2017-07-18 11:17:38] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 23 left.
[2017-07-18 11:17:40] [MainThread] [HealPokemon] [INFO] Can't use this to heal the Lapras
[2017-07-18 11:17:40] [MainThread] [HealPokemon] [INFO] Failed with potion 103. Trying next.
[2017-07-18 11:17:49] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 23 left.
[2017-07-18 11:17:51] [MainThread] [HealPokemon] [INFO] Healing Lapras (83 -> 283/167).
[2017-07-18 11:17:55] [MainThread] [HealPokemon] [INFO] Healing with a HYper potion we have 22 left.
[2017-07-18 11:17:57] [MainThread] [HealPokemon] [INFO] Can't use this to heal the Lapras
[2017-07-18 11:17:57] [MainThread] [HealPokemon] [INFO] Failed with potion 103. Trying next.
[2017-07-18 11:17:57] [MainThread] [HealPokemon] [INFO] Done healing/reviving pokemon

```
I see your coding, there's a sleep(2). I'll let you know if I get better result if set it to sleep longer.

**Pull request merged**
