### PR TITLE
Revert "Optimizer fix"

### PR DESCRIPTION
**Pull request by pogarek**
Reverts PokemonGoF/PokemonGo-Bot#6006

### CODE REVIEW

**Comment by pogarek** [comment]
reverting because it was set to master and I've missed it...

**Comment by pogarek** [comment]
merging #6009 ..

**Comment by davidakachaos** [comment]
My bad; I thought i had it set to dev. Thanks for solving :smile:

**Comment by pogarek** [comment]
np. just create a new one  :)

**Comment by davidakachaos** [comment]
@pogarek done 😄 see #6011

**Pull request merged**
