### PR TITLE
improve ball type decision maker

### PR DESCRIPTION
**Pull request by earthchie**
Now if you ran out of pokeballs it will use Great balls instead. If ran out both - use Ultra balls.

### CODE REVIEW

**Comment by solderzzc** [comment]
I want to this commit be merged :)

**Comment by douglascamata** [comment]
shouldn't we wait for Gary's version?

**Comment by solderzzc** [comment]
the merge of Gary should be very simple, there're two commits on this line mean users need it heavily.
since https://github.com/PokemonGoF/PokemonGo-Bot/pull/319
is easily and with a keep 20 in stock, we should merge #319

**Comment by solderzzc** [comment]
Thanks for the PR, let's close for now.

**Pull request closed without merging**
