### PR TITLE
if cp is lower, transfer only caught pokemon

### PR DESCRIPTION
**Pull request by techedlaksh**
This changes will not transfer pokemon from the bag as some people have mentioned that they need this feature. In future, pokemon from bag will transfer too unless its only 1 left of its own type.

### CODE REVIEW

**Comment by PokemonGoF** [comment]
Hmm, do we really need this ? @techedlaksh

**Comment by techedlaksh** [comment]
Right now it only deletes the pokemon we just caught, if its cp is lower but i was gonna change this to removing all duplicates (leaving one) lower than the set cp.

**Comment by tonz134** [comment]
I'm actually using it since i don't want the bot to delete my pokemon in the bag.

**Comment by PokemonGoF** [comment]
OK, then we need another place to drop many pokemon in bag.

**Comment by PokemonGoF** [comment]
Thanks for your vote  and pull request :)

**Pull request merged**
