### PR TITLE
User Friendly Api warning (Dev)

### PR DESCRIPTION
**Pull request by goedzo**
This gives the user a choice to continue running an older API version without upgrading.

### CODE REVIEW

**Comment by Jcolomar** [comment]
"check_niantic_api": true

We got already a 'warning' about api changes

**Comment by goedzo** [comment]
This is not about Niantic api but the python pgo api. Everytime pgoapi updates, master branch stops working. This allows it to continue.

**Comment by Jcolomar** [comment]
Understood

**Comment by MerlionRock** [comment]
Last API change has been merged to master. So no need to repeat. Let this merge to Dev and eventually @solderzzc will merge this to master. I'll rename this and merge it. The other one I'll close it.

**Comment by MerlionRock** [comment]
👍

**Comment by solderzzc** [comment]
got it

**Pull request merged**
