### PR TITLE
Update README to mention IRC

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by jtdroste** [comment]
Parts of this was merged in #493 - are we adding the readme FAQ twice now?

**Comment by MaxLeiter** [comment]
Ah, apologies, got ahead of myself with commits lol, fixing

**Comment by MaxLeiter** [comment]
I'm not sure why the branch is acting weird; no harm in merging though, the previous change will just be overwritten

**Comment by solderzzc** [comment]
let's close this one and start a new one, is that ok?

**Pull request merged**
