### PR TITLE
stop catching pokemon if we do not have pokeballs

### PR DESCRIPTION
**Pull request by rawgni**
## Short Description:
check the number of pokeballs in inventory before trying to catch pokemon.

## Fixes/Resolves/Closes (please use correct syntax):
- #4062 
-
-

### CODE REVIEW

**Comment by umbreon222** [comment]
Duplicate of my PR [#4000](https://github.com/PokemonGoF/PokemonGo-Bot/pull/4000)

**Comment by umbreon222** [comment]
Plus this solution only works when catching lured pokemon...

**Comment by rawgni** [comment]
not entirely. This PR stop the CatchLuredPokemon and CatchVisiblePokemon to be called.

**Comment by solderzzc** [comment]
When the account leveling up and recycled all low level balls, should it use the Ultraball if > Number ?

**Comment by umbreon222** [comment]
You're stopping the pokemon catching too low in the call chain. You should check for no pokeballs **before** you move to them and try to catch them.

**Comment by rawgni** [comment]
@solderzzc sorry, but i don't understand your question.

@umbreon222 you mean too high in the call chain ? There are two tasks (**CatchPokemon** and **MoveToMapPokemon**) that leads to the execution of **PokemonCatchWorker**. I guess I miss one of them, ie. **MoveToMapPokemon**

The reason for implementing the stop at **CatchPokemon** is to prevent the bot from wasting cycle on checking on pokemons in the vicinity.

**Comment by umbreon222** [comment]
@rawgni, Unless you could make it only emit once, you shouldn't emit a message saying there are no usable balls every time the catch worker is told to work because that would still cause spamming. Also, it seems to me that your PR is more efficient than mine was(checking higher in call chain) and if that's truly the case then my PR should be reverted and yours be merged instead.

**Comment by Quantra** [comment]
LGTM

Can you import `ITEM_POKEBALL` etc from somewhere?  Variables in all caps should be global constants ie they are set once and never change.  I'd expect them to be defined in a single location already.

**Comment by umbreon222** [comment]
@Quantra, pokemongo_bot/item_list.py?

**Comment by Quantra** [comment]
@umbreon222 yes =]

**Comment by solderzzc** [comment]
@rawgni Here's my situation, there's new configuration to keep Pokemon Ball, if configured to 100 mean PokeBall+Great+Ultra (Master ?)  <= 100, so when the level is low, you got much PokeBall, but when you are above level 20 or better, you will have 100 Ultra Balls.
In this case, no normal pokemons captured.

**Comment by rawgni** [comment]
@solderzzc the PR actually does let you attempt to capture the pokemon as long as the number of poke balls in your inventory is > 0 (not counting master). 

The only config I see regarding this issue is _min_ultraball_to_keep_ . There check for it in **PokemonCatchWorker** task will be the one stopping you to catch if the condition match.

**Comment by solderzzc** [comment]
Got it, thanks a lot.

**Comment by ipenpen** [comment]
I update today, and still have this bug.
Open this issue again pls.

bug

**Pull request merged**
