### PR TITLE
[Feature] added locale support for NicknamePokemon

### PR DESCRIPTION
**Pull request by mhdasding**
added config option "locale" for NicknamePokemon task
added locale jsons under /data/locales
beautyfied pokemon.json

### CODE REVIEW

**Comment by beranPro** [comment]
+1

**Comment by raincw** [comment]
This is great!

**Comment by Nihisil** [comment]
@mhdasding can you, please, merge latest dev to your PR?

**Comment by mhdasding** [comment]
@Nihisil done, but damn 8 days after PR finally a response \o/

**Comment by Nihisil** [comment]
@mhdasding thank you

**Comment by Nihisil** [comment]
👍

**Comment by Nihisil** [comment]
@TheSavior can you, please, review it and merge if everything is ok?

**Comment by TheSavior** [comment]
Those files have a lot more than 150 Pokemon...

:+1:

**Comment by vdubus** [comment]
An update on the documentation would be need for this functionality.
Yet, it seems that the documentation on the NicknamePokemon task isn’t really up to date for more than just this functionality.

**Pull request merged**
