### PR TITLE
Fix diglett moveset

### LINKED ISSUE #4309: Unexpected moveset [Mud Slap, Mud Bomb] for #50 Diglett

### LINKED ISSUE #4314: Unexpected moveset [Mud Slap, Dig] for #50 Diglett
2016-08-20 00:27:14,043 [   Pokemon] [ERROR] Unexpected moveset [Mud Slap, Dig] for #50 Diglett, please update info in pokemon.json and create issue/PR

OS: Win64, v10.0.10586
Branch: Master

### LINKED ISSUE #4321: Unexpected moveset, please update info in pokemon.json and create issue/PR
### Output when issue occurred
`016-08-20 12:48:43,272 [   Pokemon] [ERROR] Unexpected moveset [Tackle, Power Gem] for #121 Starmie, please update info in pokemon.json and create issue/PR`
`2016-08-20 12:49:06,460 [   Pokemon] [ERROR] Unexpected moveset [Water Gun, Psychic] for #121 Starmie, please update info in pokemon.json and create issue/PR`

### PR DESCRIPTION
**Pull request by bruno-kenji**
Added Mud Slap to Diglett moveset. Not sure if it still holds all the old moves though.
At least this would get rid of the "Unexpected moveset" spam.

Also, the web api data needs to be updated as well...

Fixes #4314, fixes #4321, fixes #4309

### CODE REVIEW

**Comment by bruno-kenji** [comment]
No idea why it says the config.json.example file was changed

**Comment by k4n30** [comment]
@bruno-kenji do you mind recreating this PR as it's including files that should be changed.

Can you also please review #4321 & #4309 as you have listed them as being fixed but there have been additional comments since you created the PR

**Comment by bruno-kenji** [comment]
@k4n30 of course, I'll create a new PR

**Comment by k4n30** [comment]
@bruno-kenji - Going to maintain this as well #4323

**Pull request merged**
