### PR TITLE
Send bot through Tor

### PR DESCRIPTION
**Pull request by mcrowson**
All of the bot's API requests go through tor. Use by specifying this as the docker-compose file.

docker-compose -f docker-compose_tor.yml up -d

### CODE REVIEW

**Comment by solderzzc** [comment]
Crazy ...

**Comment by solderzzc** [comment]
A user manual should be there, right?

**Comment by mcrowson** [comment]
Should I add it to the installation#docker instructions?

**Comment by solderzzc** [comment]
hmm, kinds of. Let me merge it for now.

**Comment by newjanson** [comment]
I get ImportError: No module named ipaddress

**Comment by mcrowson** [comment]
@newjanson Where are you seeing this? The two added containers both run without issue for me. All we're doing is setting them up so that the requests library behind the API sees the environment variables for the proxy.

http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by newjanson** [comment]
@mcrowson I get it after doing docker-compose -f docker-compose_tor.yml up -d

**Comment by mcrowson** [comment]
Does the command work fine with the current docker-compose file?

**Comment by newjanson** [comment]
@mcrowson nope, sorry

**Comment by newjanson** [comment]
So I'm getting
`ERROR: In file './docker-compose_tor.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options`

Here is my docker version:
`Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
`
And here is docker-compose --version

`docker-compose version 1.5.2, build unknown`

**Pull request merged**
