### PR TITLE
check_niantic_api logic change

### PR DESCRIPTION
**Pull request by MerlionRock**
Now check api uses version number returned from PGoAPI rather than comparing to Bossland endpoint.

### CODE REVIEW

**Comment by goedzo** [comment]
This commit does not work and causes the following error when building the container:
>AttributeError: class PGoApi has no attribute 'get_api_version'

Seems that the PGoApi is not updated in Dev branch yet.

**Comment by MerlionRock** [comment]
@goedzo how do you usually do update? Is it possible to rebuild the container? Just update to latest Pgoapi. Else you are running older API and risk ban.

**Comment by nimsnims** [comment]
Hi merlion. I use the command from the documeation:
>docker build --build-arg BUILD_BRANCH=dev -t pokemongo-bot .

This does not update the pgoapi, so that should be fixed too. I suspect that pgoapi update is stil in Dev branch, and container just gets release branch. But tbh i dont know how to update pgoapi in a container so please let me know how i can do that.

**Comment by nimsnims** [comment]
Ps. Nimsnims & goedzo are both my github accounts.

**Comment by MerlionRock** [comment]
@Nimsnims let me ask around in discord

**Comment by MerlionRock** [comment]
@nimsnims refer to https://github.com/PokemonGoF/PokemonGo-Bot/issues/6075 and see last reply. See if that helps. If anymore questions, ask in that thread.

**Comment by goedzo** [comment]
For Reference I will also post this here:

It seems that a lot of extra containers are also build in the process, so with above input I was able to find that

>    docker images -q

Gives all the containers. So I removed them all with the

>    docker rmi [image_id]

After this it seems to rebuild everything, including the pgo api.

Within the build process this seems to me the relevant line:

>    Collecting pgoapi from git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi (from -r requirements.txt (line 4))
>    Cloning https://github.com/pogodevorg/pgoapi.git (to develop) to /tmp/pip-build-Rwwo7j/pgoapi

And now it seems to work correctly! So thank you for the help. I think the documentation on how to properly rebuild the container, should be added :)

This commit is actually perfect!

**Pull request merged**
