### PR TITLE
SQLite backend for bot/plugin use

### PR DESCRIPTION
**Pull request by cwild**
## Provide SQL backend for bot

Some things would be better stored in a database. Successful login attempts perhaps (as the example in this first commit).
Longer term, a Pokemon capture log could be stored.

**Wanting to gather collective thoughts on this. Feedback very welcome**

### CODE REVIEW

**Comment by TheSavior** [comment]
@douglascamata Please review and provide thoughts based on your socket server and logging context.

**Comment by BreezeLo** [comment]
got catch limit / pokestop limit logic ready here, waiting for when this is approved, looks good to me.

**Comment by cwild** [comment]
Are people happy with how this was implemented? I was looking for feedback to see if it would be suitable.

**Comment by Gurzeh** [comment]
@BreezeLo hi man. Do you know the limit number of Pokestop / day?

**Pull request merged**
