### PR TITLE
Cleanup social_handler.py

### PR DESCRIPTION
**Pull request by sohje**
## Short Description:
Social_handler cleanup
## Fixes/Resolves/Closes (please use correct syntax):
- pep8
- cleanup
- readability

### CODE REVIEW

**Comment by Gobberwart** [comment]
Why removed "need connect" and "connect again" debug messages?

**Comment by sohje** [comment]
Cause it doesnt bring any clue whats happening. This PR is first step to refactor classes and methods.

**Comment by Gobberwart** [comment]
It certainly does bring a clue to what's happening... if the bot is constantly trying to reconnect, it can help to identify a connection issue.

Also, would like to see debug messages use self.bot.config.debug

`if DEBUG_ON or self.bot.config.debug:

And of course use the logger to display messages.

**Comment by Gobberwart** [comment]
Refer to #5216 why these connect messages are useful

**Comment by sohje** [comment]
We can always check file history ;)

**Comment by sohje** [comment]
If we enable printing via self.bot.config.debug there will be a lot of stuff by api requests, response etc. So i left DEBUG_ON module global var.

**Comment by Gobberwart** [comment]
Agree, but both are needed, so that debug messages are printed either if DEBUG_ON == True, OR config.debug == True. Both should work.

In fact, probably easiest to just add:

`if self.bot.config.debug: DEBUG_ON = True`

to init section of each class

**Comment by Gobberwart** [comment]
Anyway, for now please at least add connect messages back because they are actually helpful in some situations.

**Comment by Gobberwart** [comment]
Thanks. Approved.

**Comment by sohje** [comment]
Ok, thanks. Merge then.

**Pull request merged**
