### PR TITLE
Dev merge to master

### PR DESCRIPTION
**Pull request by solderzzc**
Dev merge to master

### CODE REVIEW

**Comment by MerlionRock** [comment]
👍

**Comment by davidakachaos** [comment]
Looks great 👍

**Comment by solderzzc** [comment]
why the status of pull approve was not changed.

**Comment by solderzzc** [comment]
@davidakachaos maybe you can set it on this [link](https://pullapprove.com/PokemonGoF/PokemonGo-Bot/pull-request/6076/reviews/)   
screen shot 2017-07-12 at 3 43 13 pm

**Comment by davidakachaos** [comment]
No such an option for me:
schermafbeelding 2017-07-13 om 00 45 25
@solderzzc maybe pull-approve doesn't want me to approve things yet?

**Comment by solderzzc** [comment]
@davidakachaos Did you login with github auth?

**Comment by davidakachaos** [comment]
Yes I did, I also see myself on the member list

**Comment by davidakachaos** [comment]
Let's try this again 👍

**Comment by davidakachaos** [comment]
👍

**Comment by solderzzc** [comment]
haha, nice :) finally

**Comment by davidakachaos** [comment]
schermafbeelding 2017-07-13 om 00 51 26
So all checks have passed now 😄

**Pull request merged**
