### PR TITLE
Replaced fort with pokestop in logger

### PR DESCRIPTION
**Pull request by Jasperrr91**
Short Description: 
Replaced fort with pokestop in logger

Fixes:
- Replaced fort with pokestop in logger

### CODE REVIEW

**Comment by maestroi** [comment]
:+1: @douglascamata  push :horse_racing:

**Comment by Evanito** [comment]
I don't understand why it is forts in the first place, explanation?

**Comment by douglascamata** [comment]
Name in the API responses from servers.

**Comment by Jasperrr91** [comment]
@Evanito in the API, both Gyms and Pokestops are named Forts. But we only use the Pokestops so that name is a better fit.

**Comment by douglascamata** [comment]
Closed because events.

**Pull request closed without merging**
