### PR TITLE
Handle Github Download Zip Format

### PR DESCRIPTION
**Pull request by TheSavior**
To test:

1. pull this branch
2. Put this in your config.json, replacing the tasks you currently have:
```
    "plugins": [
      "TheSavior/test-pgo-plugin#2d54eddde33061be9b329efae0cfb9bd58842655"
    ],
    "tasks": [
      {
        "type": "test-pgo-plugin.PrintText"
      }
    ],
```
3. Check that your console looks like this:
```
2016-08-08 10:33:55,360 [PokemonGoBot] [INFO] 
2016-08-08 10:34:01,156 [PokemonGoBot] [INFO] [bot_start] Starting bot...
PrintText!
PrintText!
PrintText!
PrintText!
PrintText!
PrintText!
PrintText!
PrintText!
...
```

### CODE REVIEW

**Comment by solderzzc** [comment]
Can we put the core(PGOAPI) part into plugin, then it's a just open source automation framework.

**Comment by TheSavior** [comment]
Plugins are only for tasks, like this:

```
    "plugins": [
      "TheSavior/test-pgo-plugin#master"
    ],
    "tasks": [
      {
        "type": "test-pgo-plugin.PrintText"
      }
    ],
```

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
screen shot 2016-08-08 at 10 58 05 am
Amazing happen everyday.

**Comment by mmnsgo** [comment]
is there any check in place to prevent a plugin from accessing user/pwd?

**Comment by TheSavior** [comment]
We don't have any way currently to sandbox tasks.  Any tasks in the core can access that information right now, and any plugins have the same access. For the time being, using plugins will be at user's risk.

We would happily accept suggestions for how we can sandbox the tasks from information they shouldn't be able to access.

**Comment by douglascamata** [comment]
👍

**Pull request merged**
