### PR TITLE
Fix for clash between CLI and JSON args

### PR DESCRIPTION
**Pull request by douglascamata**
The CLI parameter parser now uses JSON-loaded parameters as first
fallback to missing parameters. The second fallback to missing
parameters are the default values previously used.

This is the perfect handling for making CLI args override JSON
configuration only for provided args. Non-provided args that are not
found in are set to the default value we think most users are going to
like.

td;dr: arguments priority now is correctly set as:

1. CLI arguments
2. JSON arguments
3. hardcoded default arguments

### CODE REVIEW

**Comment by surfaace** [comment]
:+1: 
if ci is happy, i'm also happy

**Comment by douglascamata** [comment]
@surfaace please test, lol

**Comment by solderzzc** [comment]
👍 
nice

**Comment by douglascamata** [comment]
DO NOT merge yet. People are testing.

**Comment by TheSavior** [comment]
👍

**Comment by solderzzc** [comment]
Nice to see the standardize of arguments.
👍

**Comment by TheSavior** [comment]
👍

**Comment by codybaldwin** [comment]
I have tested this commit and it appears to now behave as desired.  Configs missing from config.json are required in command line.  Command line args override config.json parameters.

**Pull request merged**
