### PR TITLE
added separate config

### PR DESCRIPTION
**Pull request by rawgni**
## Fixes/Resolves/Closes (please use correct syntax):
- #4781 
-
-

### CODE REVIEW

**Comment by solderzzc** [comment]
You sure you want to change as this way? Many support ticket will be opened.
How about add a auth in current main config file to point to the auth.conf? This will keep current config file working without changes.

**Comment by rawgni** [comment]
@solderzzc i believe the current config will still work without a problem, ie. only using config.json instead of having auth.json and config.json.

It basically loads auth.json and then update it with whatever is in config.json. If there is nothing in auth.json then you get whatever is in config.json

**Comment by solderzzc** [comment]
@rawgni  Yes, I just understood your code. Thanks a lot.

**Comment by MZorzy** [comment]
Why not move *example to an subdir like ./configs/example
And let user have only real configs files under ./configs ?

Auth.json with fixed data
Some config.json
Location.json with preferred cities (need to add altitude)

**Pull request merged**
