### PR TITLE
Workaround Empty Forts

### PR DESCRIPTION
**Pull request by loklam**
Short Description: Sometimes, the API return empty forts. This causes move_to_fort fail. To workaround this, return prev forts, if API return empty forts.

Fixes:
- 
- 
-

### CODE REVIEW

**Comment by Sammy-L** [comment]
I've tested this code. It works very well. Niantic changed the search respond rate to about 4s since last patch. So the fort scan nearly always return empty result. Saving the old result does help for situations while server refuse to give response.

**Comment by kloz8879** [comment]
I Have also tested this and it works great! Thank you.
2016-08-01_07h15_08

**Comment by z4ppy** [comment]
Work for me !

**Comment by loklam** [comment]
This has been fixed at https://github.com/PokemonGoF/PokemonGo-Bot/pull/2269

**Pull request closed without merging**
