### PR TITLE
Add IRC to README

### PR DESCRIPTION
**Pull request by MaxLeiter**
Someone on the Slack side should now implement the Slack-IRC bridge: https://github.com/ekmartin/slack-irc

### CODE REVIEW

**Comment by solderzzc** [comment]
IRC will expose all our users' info, including ours. So that's not good.

**Comment by MaxLeiter** [comment]
They can use the web chat I linked

**Comment by solderzzc** [comment]
IRC will expose all our users' info, including ours. So that's not good.
Please let our development team focus on the big thing first, any issue can be log in issue list, so we won't miss anything.
Let me close the related topics/MR at the time, will reopen when we have time.

**Comment by MaxLeiter** [comment]
At least setup the Slack-IRC bot...

**Comment by MaxLeiter** [comment]
How is it harmful to have an additional link to IRC along with slack? Plenty of projects have IRC channels and don't worry about "exposing users info" (just an IP...)

**Comment by haykuro** [comment]
There are contributors unable to communicate with the rest of the group.

Let's make chat as available as possible, communication / collaboration is key.

I understand issue / pull request is great, but can help if there's some active engagement between those writing code for the bot.

**Pull request closed without merging**
