### PR TITLE
Mqtt web ui

### PR DESCRIPTION
**Pull request by solderzzc**
# MQTT Web UI   -- Working branch, don't merge it.
## Why need it, isn't Socket.IO good enough?

well, it's complex for multiple instance
## is that safe to send data to public mqtt broker

E2E encryption will keep your data safe

### CODE REVIEW

**Comment by rawgni** [comment]
@solderzzc isn't mqtt too overkill for the web ui?

**Comment by solderzzc** [comment]
@rawgni  I don't have better idea than MQTT for multiple instance running locally. Socket.io is complex to handle. And a MQTT broker is very lightweight.

**Comment by rawgni** [comment]
@solderzzc hm.. but, is it safe to run multiple bot locally ? what happened if the public broker "broke" ? would it be possible to have private broker?

**Comment by BreezeRo** [comment]
That is actually the goal at it's core @rawgni, to have the public create their own broker, and establish "trusted brokers" within the botting community that people could add into a config list to pull data from.

**Comment by solderzzc** [comment]
@BreezeRo I have something to do before merge. The channel need to be configurable, E2E encrypt is best to have to protect private data if there's any.
And good morning :)

**Comment by douglascamata** [comment]
SocketIO-capable web server is very lightweight too, because it runs on Flask. If someone thinks it's not lightweight, he can implement a server with the same features in any other language he wants that has a SocketIO library for web servers, like C or Golang. SocketIO is a very common library used for this type of communication. I don't see any reason to use MQTT over SocketIO. In fact, from what I see MQTT seems like a layer on top of websocket, while SocketIO just provides a compatible interface between servers/clients (correctly choosing websocket or long polling based on client/server). 

It's not complex for multiple instance of the bot. It routes different account stuff to websocket events with the account email in it. It's easy to support and very leightweight on the server too, because it's not broadcasting events from all accounts to all clients, which is totally uncessary and very costy.

**Comment by solderzzc** [comment]
@douglascamata Route is exactly what MQTT broker does, so that's easier?

**Comment by Gobberwart** [comment]
Is this still required? I removed the "Approved" label, since it's not actually approved. Wondering if it should just be closed as abandoned?

**Pull request closed without merging**
