### PR TITLE
Change MoveToFort text to not send 2 lines and have a more humanreadable

### PR DESCRIPTION
**Pull request by heihachi**
Short Description: 
Changed the way MoveToFort was outputting.

### CODE REVIEW

**Comment by Nihisil** [comment]
I have heard that guys want to remove `[x] ` from all logs, so maybe you need to do it too. Don't know it is actual information or not, someone from the team can confirm it.

**Comment by heihachi** [comment]
@Nihisil changed the text and thanks for the heads up!

[Example of what output looks like](http://pastebin.com/raw/B5b7qedZ)

**Comment by TheSavior** [comment]
Merge conflicts

**Comment by TheSavior** [comment]
I think this can be done with a smaller change

**Comment by heihachi** [comment]
@TheSavior i probably could just didnt want to remove output that was already there.

**Comment by TheSavior** [comment]
How about this instead? https://github.com/PokemonGoF/PokemonGo-Bot/pull/1566

**Pull request closed without merging**
