### PR TITLE
Evolve only if evolvable candidates no less than a certain number.

### PR DESCRIPTION
**Pull request by coderplay**
Evolve only if evolvable candidates no less than a certain number.

Previously, when user configured use_lucky_egg as true, the bot will use
lucky egg even evolvale candidates is zero. That's kinda of
waste. Meanwhile, if user didn't configured use_lucky_egg, the bot will
try to evolve after sort by cp&iv, but sometimes no good potential
pokemon in that batch, it's better delay the evolution after a
while. By adding a config item evovle_num_min can cope above two
problems. The bot evolves only if evolvable candidates no less than a
certain number.

1. Evolve only if evolvable candidates no less than a certain number.

2. Dragoniar's configuration is abnormal in pokemon.json, which lack of
"Previous evolution(s)" attribute, while the other middle-tier pokemon
has.

### CODE REVIEW

**Comment by coderplay** [comment]
Messed up with https://github.com/PokemonGoF/PokemonGo-Bot/pull/2421, create a new one

**Comment by TheSavior** [comment]
:+1:

**Comment by solderzzc** [comment]
> This branch has conflicts that must be resolved

**Comment by TheSavior** [comment]
Looks like this PR has a bad merge

**Comment by solderzzc** [comment]
Oh no, the merge is mess. better to recreate a branch for PR. 
Rebased command used ?

**Comment by solderzzc** [comment]
close since no  activity in 5 days/

**Pull request closed without merging**
