### PR TITLE
Increased time outs to not getting banned

### PR DESCRIPTION
**Pull request by nivong**
Changed the times out we should also add a random time out to the envolve time #TODO
(this CAN be merged)

### CODE REVIEW

**Comment by Anakin5** [comment]
It is way too much I think. It does not take 10 seconds to make one transfer. By hand and without rushing, you are at one every 3 seconds.
Time for evolve is the same as transfer plus the animation time. It is not 35 seconds.

**Comment by mjmadsen** [comment]
Would prefer this be merged to dev first.

@Anakin5 is correct, IMO. I could see 3-6 as a more reasonable default value.

**Comment by Calcyfer** [comment]
Just did a quick test using the app based on 10 evolves and transfers : 
Evolve : 22 - 26 seconds
Transfer : 2 - 5 seconds

**Comment by k4n30** [comment]
Please create PR against dev

**Pull request closed without merging**
