### PR TITLE
Disable hunting when no more balls

### PR DESCRIPTION
**Pull request by davidakachaos**
## Short Description:
When the bot isn't catching Pokemon because a lack of balls, don't hunt for Pokemon.

## Fixes/Resolves/Closes (please use correct syntax):
- Nothing, small enhancement

### CODE REVIEW

**Comment by MerlionRock** [comment]
I thought there's already such function?

in config, add

`      {
        "type": "CatchLimiter",
        "config": {
          "enabled": true,
          "min_balls": 30,
          "duration": 15
        }
      },`

**Comment by davidakachaos** [comment]
Yes this function works great :smile: But the Pokemon Hunter will still move toward a Pokemon of interest and starts searching for it, while we won't catch it (because the CatchLimiter is active)

This PR makes the Pokemon Hunter stop searching for or moving toward a Pokemon when we don't catch Pokemon. Thus the bot will keep moving toward Pokestops instead of needlessly searching for Pokemon.

I hope this makes this PR a bit clearer

**Comment by Jcolomar** [comment]
Asap devs log they merge all changes

**Comment by solderzzc** [comment]
👍

**Pull request merged**
