### PR TITLE
Adding Shiny attribute to Pokemon

### PR DESCRIPTION
**Pull request by davidakachaos**
See #5975 

Adding attribute "Shiny" to pokemons.

### CODE REVIEW

**Comment by pogarek** [comment]
Thanks for the PR
You would need to fix tests as well... 
You can run tests at any time:
`  python -m unittest discover -v -p "*_test.py"

if you need help with that , step by to discord. :)

**Comment by pogarek** [comment]
by fixing test I mean, modify code of tests so it matches actual results that tests results right now

**Comment by davidakachaos** [comment]
I'll look into that! Thanks for the pointer!

Op 27 mrt. 2017 13:21 schreef "pogarek" <notifications@github.com>:

**Comment by MerlionRock** [comment]
@davidakachaos Did you miss out the shiny variable in pokemon_vip_caught and pokemon_caught event?

**Comment by davidakachaos** [comment]
@pogarek fixed the tests 😄

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
merged #5979

**Pull request merged**
