### PR TITLE
Added string format to step_walker

### PR DESCRIPTION
**Pull request by guitared**
## Short Description:
Added string format for location in step_walker.py

### CODE REVIEW

**Comment by TheSavior** [comment]
I don't think this is the right fix. This should only be printed out in debug mode, but it is getting printed even when not in debug mode. @douglascamata how do we fix this?

**Comment by ryanb93** [comment]
@TheSavior I think this is because of the coloured_logging_handler using sys.stdout.write and the 'level' parameter being passed through isn't being used at all.

**Comment by douglascamata** [comment]
The coloured logging handler should be fixed to use the logging module correctly as the normal logging handler uses.

**Comment by douglascamata** [comment]
#3637 will fix this properly by fixing the coloured log handler implementation.

**Pull request closed without merging**
