### PR TITLE
Fix for linux not loading encrypt.so

### PR DESCRIPTION
**Pull request by fermuch**
Short Description: 
Linux users weren't able to load `encrypt.so`. I added the absolute path and now it's working.
Also, "formatted" was mispelled in some places as "formmated".

### CODE REVIEW

**Comment by solderzzc** [comment]
Please submit to the dev branch. we need platform related code since the fix will not work on win, right?

**Comment by fermuch** [comment]
the fix won't work on windows, since (I think) windows expects a .dll file. We should add a check before running to see if `encrypt.so` is present on *NIX and `encrypt.dll` on win.

Gonna work on that tomorrow.

**Comment by solderzzc** [comment]
Sure, thanks a lot, we can wait for :)

**Comment by louisgv** [comment]
Seems like this is needed on Linux, however where would you obtain the `encrypt.so` file?

**Comment by louisgv** [comment]
Digging around and found this.

#2645

**Comment by louisgv** [comment]
Confirmed working on linux.

To build, download the archive from http://pgoapi.com/, extract, then:

```
cd src
make
cp libencrypt.so ../../PokemonGo-Bot/encrypt.so <- Relative path to your bot repo. 
```

Then do some pip upgrade.

**Comment by earthchie** [comment]
it works for me :) 

(I'm running bot on Win10's LinuxSubsystem)

**Comment by nburn42** [comment]
Also worked for me,
Thanks

**Comment by takenek** [comment]
Strange i still can`t run and got  error:
encrypt.so: cannot open shared object file: No such file or directory
but i copy encrypt.so to bot folder:
(PokemonGo-Bot) taken@taken:~/PokemonGo-Bot$ ls -al /home/taken/PokemonGo-Bot/ |grep encrypt.so
-rwxr-xr-x  1 taken taken 243896 sie  7 08:02 encrypt.so

**Comment by MikeDX** [comment]
Using the change to __init__.py:

+        encrypt_path = os.path.abspath("./encrypt.so")
+        self.api.activate_signature(encrypt_path)

Works great for me.


What are all the other changes in the file there for? I think they should be in different pull requests as they seem to have no relevance to this one.

**Comment by takenek** [comment]
Yep i just find this info...
Looks working good change to ./encrypt.so  :-)

**Comment by Aaronucci** [comment]
Takenek  What did you have to do.... change the init.py file?  I couldn't find that file

**Comment by imvikash00** [comment]
@takenek in config set "health_record": false 
This will prevent "RuntimeError: maximum recursion depth exceeded while calling a Python object" error.

**Comment by imvikash00** [comment]
@Aaronucci 
Get the pogoapi archive, extract and do make
then copy libencrypt.so to pokemongo-bot folder as encrypt.so
chaneg __init__.py in pokemongo-bot as mentioned by @MikeDX

**Comment by Aaronucci** [comment]
@imvikash00 Okay I made the change per the pull to init.py but still getting this: And I did pull the encrypt file and copy it to the root of the PokemonGo-Bot folder.   Which its' full path is just /PokemonGo-Bot

Would it be easier to use the suggestion nburn said and just pull the files with git, however not sure how to go about that other then git clone
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 126, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 212, in _build_main_request
    u6.unknown2.unknown1 = self._generate_signature(signature_proto)
  File "/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 236, in _generate_signature
    self._signature_lib.encrypt(signature_plain, len(signature_plain), iv, 32, None, ctypes.byref(output_size))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /PokemonGo-Bot/encrypt.so: undefined symbol: encrypt

**Comment by imvikash00** [comment]
@Aaronucci 
Here's wat is did
Using ubuntu
followed @louisgv steps except pip upgrade
Now encrpyt.so is in your PokemonGo-Bot folder
follow @MikeDX steps, modify __ init.py __ in ur PokemonGo-Bot/pokemongo_bot folder

**Comment by beranPro** [comment]
Works for me 

+1

**Comment by douglascamata** [comment]
This is hardcoded for Linux. Needs a better solution that works on Linux, Darwin and Windows at the same time.

**Comment by Aaronucci** [comment]
Figured it out.  Need to compile the encrypt.so for linux

**Comment by fermuch** [comment]
I made this branch really tired yesterday, and no dev should work without sleeping.
I'm working now on a new PR to handle the loading of `encrypt` better.

Please ignore this one.

**Comment by danielkohn** [comment]
If you're still having problems after putting the correct encrypt.so (or dll) into the directory, try this:

sudo pip uninstall -y certifi
sudo pip install certifi==2015.04.28

This will fix the error:
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Pull request closed without merging**
