### PR TITLE
Adapt code to new PGoApi Code

### PR DESCRIPTION
**Pull request by DayBr3ak**
New PGoApi changes are now compatible

### CODE REVIEW

**Comment by douglascamata** [comment]
from pylint:

```
FILE: /home/travis/build/PokemonGoF/PokemonGo-Bot/pokemongo_bot/api_wrapper.py
FAILED pylint inspection: E:  5, 0: Unable to import 'POGOProtos.Networking.Requests_pb2' (import-error)
```

**Comment by DayBr3ak** [comment]
Mhh working on it!

**Comment by DayBr3ak** [comment]
@douglascamata here you go

**Comment by douglascamata** [comment]
@TheSavior please, review this... it's awesome!

**Comment by DayBr3ak** [comment]
I need a bit of time though, I have a pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man comming up time to time

**Comment by douglascamata** [comment]
hahahahah... there's a settings for cache map object, set it to 5 seconds and should be ok.

**Comment by douglascamata** [comment]
`"map_object_cache_time": 5,`

**Comment by DayBr3ak** [comment]
No still coming up :(

**Comment by reddivision** [comment]
@DayBr3ak just catch the exception and retry the request, it usually goes through fine

**Comment by DayBr3ak** [comment]
@reddivision you mean in the ApiWrapper?

**Comment by reddivision** [comment]
@DayBr3ak you can report the error and retry... we (should) have a max retry count as well, so just raise an exception if you hit too many retries

**Comment by DayBr3ak** [comment]
I've just done that, what do you think? should I do that differently ? Is 5 sec sleep too much ?

**Comment by reddivision** [comment]
Sure, that works. While it's not really hurting anything, you don't need to have a sleep there because the top of the while loop has our own throttling code that will implement a two-second gap between any requests, so your "sleep" is already taken care of there.

**Comment by DayBr3ak** [comment]
True I should remove both sleeps

**Comment by DayBr3ak** [comment]
Actually this ThrottleSleep at the top of the while loop is only sleeping for the first try. If you have retries, it won't sleep

**Comment by douglascamata** [comment]
@DayBr3ak so, is it ready and tested? :D

**Comment by DayBr3ak** [comment]
I haven't tested all workers, but yes it's ready. Bot is running fine

**Comment by douglascamata** [comment]
@DayBr3ak please test as much as u can.

**Comment by DayBr3ak** [comment]
@douglascamata Relogging after a session expiration seems to be broken

**Comment by douglascamata** [comment]
@DayBr3ak ok... please ping me when you get the fix going. Looking forward to merge this ASAP, but we need safety.

**Comment by DayBr3ak** [comment]
@douglascamata it's fixed. You can merge :)

**Comment by JSchwerberg** [comment]
Looks like this has its own set of problems.

```
[15:33:44] Moving towards fort Unique Lights At Lemongrass, 0.11km left (attraction of lure 0.19km)
[15:33:45] Server is throttling, let's slow down a bit
[15:33:47] Server is throttling, let's slow down a bit
[15:33:51] Moving towards fort Unique Lights At Lemongrass, 0.10km left (attraction of lure 0.19km)
[15:33:52] Server is throttling, let's slow down a bit
[15:33:55] Server is throttling, let's slow down a bit
[15:33:58] Moving towards fort Unique Lights At Lemongrass, 0.09km left (attraction of lure 0.18km)
[15:33:59] Server is throttling, let's slow down a bit
[15:34:02] Server is throttling, let's slow down a bit
[15:34:05] Moving towards fort Unique Lights At Lemongrass, 0.08km left (attraction of lure 0.17km)
[15:34:06] Server is throttling, let's slow down a bit
[15:34:09] Server is throttling, let's slow down a bit
[15:34:12] Moving towards fort Unique Lights At Lemongrass, 0.07km left (attraction of lure 0.16km)
[15:34:14] Server is throttling, let's slow down a bit
[15:34:16] Server is throttling, let's slow down a bit
[15:34:19] Moving towards fort Unique Lights At Lemongrass, 0.07km left (attraction of lure 0.16km)
[15:34:21] Server is throttling, let's slow down a bit
[15:34:23] Server is throttling, let's slow down a bit
[15:34:26] Moving towards fort Unique Lights At Lemongrass, 0.06km left (attraction of lure 0.15km)
[15:34:27] Server is throttling, let's slow down a bit
[15:34:28] Server is throttling, let's slow down a bit
[15:34:32] Moving towards fort Unique Lights At Lemongrass, 0.05km left (attraction of lure 0.14km)
[15:34:33] Server is throttling, let's slow down a bit
[15:34:35] Server is throttling, let's slow down a bit
[15:34:39] Moving towards fort Unique Lights At Lemongrass, 0.04km left (attraction of lure 0.13km)
[15:34:40] Server is throttling, let's slow down a bit
[15:34:42] Server is throttling, let's slow down a bit
[15:34:43] Server is throttling, let's slow down a bit
```

**Comment by leanderjanssen** [comment]
Even with `"map_object_cache_time": 5,` I still get that log line a lot.

**Comment by DayBr3ak** [comment]
Can a admin comment that log line... I really should have deleted it.. that's just noise.

**Comment by douglascamata** [comment]
@DayBr3ak I will soon.

**Pull request merged**
