### PR TITLE
Catch KeyboardInterrupt on login attempt

### PR DESCRIPTION
**Pull request by monsty**
Short Description: 

Fixes:
- Catch KeyboardInterrupt on login attempt

### CODE REVIEW

**Comment by surfaace** [comment]
:+1: i was working at a simular and it almost looks the same

**Comment by MaxLeiter** [comment]
:+1: works for me, but resolve conflicts please

**Comment by gregtampa** [comment]
This branch has conflicts that must be resolved

**Comment by TheSavior** [comment]
We would still love to have this functionality. Unfortunately this PR is pretty behind where we are and has some merge conflicts. If you are interested in adding this to the bot as it is now, that would be greatly appreciated.

**Pull request closed without merging**
