### PR TITLE
fix setup.sh failing on macosx

### PR DESCRIPTION
**Pull request by rawgni**
## Short Description:

fix setup.sh script

## Fixes/Resolves/Closes (please use correct syntax):
- #4154

### CODE REVIEW

**Comment by simonsmh** [comment]
👍

**Comment by k4n30** [comment]
@rawgni merge conflicts

**Comment by rawgni** [comment]
@k4n30 still conflict ?

**Comment by k4n30** [comment]
Yep, update to latest dev and see if u can fix it

**Comment by rawgni** [comment]
@k4n30 let's hope this fix it

**Pull request merged**
