### PR TITLE
Value in the config files were not correctly set

### PR DESCRIPTION
**Pull request by DayBr3ak**
Short Description: 

every value matching a False ie (0, None, or False) were ignored. We only want the None value to be matched

### CODE REVIEW

**Comment by surfaace** [comment]
:+1:

**Comment by douglascamata** [comment]
:-1:

**Comment by douglascamata** [comment]
I'm fixing the whole config load, it was messy very error prone.

**Comment by DayBr3ak** [comment]
I close this pr then ?

**Pull request closed without merging**
