### PR TITLE
Removed incorrect call to jsonify_inventory

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:

Call to jsonify_inventory causes player_data to be lost from output.

### CODE REVIEW

**Comment by MartinTerp** [comment]
Hi @Gobberwart , me again! can you confirm that this is working? because for me, player_stats is still not in the inventory file

**Comment by Gobberwart** [comment]
@MartinTerp Working fine for me. Here's what I'm seeing in my inventory-username.json

[{"inventory_item_data": {"player_stats": {"pokemons_captured": 1561, "km_walked": 148.5740203857422, "level": 23, "big_magikarp_caught": 6, "experience": 456175, "pokemons_encountered": 1658, "pokeballs_thrown": 2709, "eggs_hatched": 46, "small_rattata_caught": 20, "unique_pokedex_entries": 80, "prev_level_xp": 335000, "evolutions": 11, "next_level_xp": 560000, "pokemon_caught_by_type": "AOgEC84DnwMbFPQBCw8M3AKAAREjAAUAHw==", "poke_stop_visits": 2908}}}

**Comment by Gobberwart** [comment]
Check both top and bottom of the file... seems to vary depending on what specific tasks run where.

Also check "Info" on web interface, see what appears there.

**Comment by Gobberwart** [comment]
Also note there may be a small delay updating, as the player stats only updates when UpdateLiveStats runs (to conserve api calls)

**Comment by MartinTerp** [comment]
@Gobberwart ah okay, didt think it was depended for the UpdateLiveStats, i belived that the stats was stored and calculated in the bot ( or maybe it was future plan for it ) but after enabled it, it worked :)

Thansk for your time.

**Comment by Gobberwart** [comment]
@MartinTerp It's definitely in the future plan, just hasn't happened yet. There are potentially lots of different places where things will need to be found and updated, so it'll be a somewhat lengthy process to track player_stats in the bot. Working on it.

**Pull request merged**
