### PR TITLE
If you have no other pokeballs, be wiling to use ultra balls

### PR DESCRIPTION
**Pull request by TheSavior**
Right now I have 0 pokeballs, 0 greatballs, and 60 ultra balls. The bot was refusing to catch anything because it only wanted to use ultraballs on VIPs. If we have no other balls, we should be willing to use ultra balls.

### CODE REVIEW

**Comment by h3k1ru** [comment]
Then eventually you will end up with 0 Ultraballs as well. If you came to 0 Pokeballs that's mean your pokestop/pokemon ratio is bad and need improve.

**Comment by Dwite** [comment]
I think this will use ultraball even if there are other pokeballs when Pokemon catch rate is very low, but I'm not 100% sure about it, maybe extend condition?

**Comment by TheSavior** [comment]
The lowest available pokeball is chosen with this logic:

```
current_ball = ITEM_POKEBALL		             current_ball = ITEM_POKEBALL
             while items_stock[current_ball] == 0 and current_ball < maximum_ball:		             while items_stock[current_ball] == 0 and current_ball < maximum_ball:
                 current_ball += 1
```

**Comment by Dwite** [comment]
Ok

**Comment by leanderjanssen** [comment]
Personally I would like this behaviour to be configurable through configuration.
I would like to save my ultraballs for my defined VIPs.

**Comment by AcorpBG** [comment]
I run my bot with this change since the catch was reworked. Yes it will use more ultraballs the best way to deal with this is to be able to set both max_ball_non_vip and ideal_catch_rate_before_throw_non_vip

**Comment by TheSavior** [comment]
The challenge for me is that I don't get very many low level pokeballs from pokestops anymore, so I'm completely out of pokeballs that it is willing to use, but it still tries to catch pokemon and complains that there are no available balls. While it is definitely important to save some to be able to catch VIPs, if it isn't willing to use ultraballs for regular pokemon, the bot essentially stops doing anything.

**Comment by achretien** [comment]
Agreed wit @TheSavior 

```
PokeBalls: 78 | GreatBalls: 0 | UltraBalls: 200
```

**Comment by Philipp59** [comment]
@TheSavior 
```
current_ball = ITEM_POKEBALL
while items_stock[current_ball] == 0 and current_ball < maximum_ball:
  current_ball += 1
```
will this also be a fix for  #3313 ?

**Comment by AcorpBG** [comment]
maximum_ball = ITEM_ULTRABALL
         ideal_catch_rate_before_throw = 0.9 if is_vip else 0.5
I'm running it like this right now after lvl 20 you get alot more great and ultra balls with this config I'm forcing it to use more great/ultra balls and berries and also it is way more effective in catching

**Comment by h3k1ru** [comment]
I think we should be able to specify minimum catch rate for every ball via config. And for berries too. Also berry must be thrown every catch attempt, not only first one, because it boost only one attempt.

**Comment by TheSavior** [comment]
I think the problems you guys are bringing up with configuring pokemon catching is valuable, but I'm not sure it is relevant to this PR. This PR simply allows us to catch pokemon when we still have balls left. Changing the logic of how we pick balls is something we should tackle separately.

**Comment by DimaVIII** [comment]
@TheSavior If you fix this can you please also investigate this two issues https://github.com/PokemonGoF/PokemonGo-Bot/issues/3271 & https://github.com/PokemonGoF/PokemonGo-Bot/issues/3287 they appear after the last changes as there been so many pokeball changes and it's damaging the bot. There are many infinity loops and so on. Thank you!

**Comment by TheSavior** [comment]
@douglascamata Please review

**Comment by licklake** [comment]
there should be an option to reserve (lets say 10 for e.g.) ultraballs for v.i.p pokemon only

**Comment by TheSavior** [comment]
It sounds like there is more logic that needs to go into this to satisfactorily cover everyone's use cases than I am willing to work on for this right now. In the short term I can modify my config to keep more low level pokeballs.

**Pull request closed without merging**
