### PR TITLE
Fixing issues in event fitlering (/events command in chat handler)

### PR DESCRIPTION
**Pull request by DBa2016**
## Short Description:
- fixes issues in filtering of /events
- fixes issues when calling /info and no visited pokestops or caught pokemons counts are available
- minor reformatting of subscriptions shown by telegram handler

### CODE REVIEW

**Comment by DBa2016** [comment]
Replaces #5536

**Comment by DBa2016** [comment]
They were probably hidden because they are never really raised?...

I don't know, to be honest, why they were discarded at all.

**Comment by javajohnHub** [comment]
I thought they were effecting startup and bogging...but i was wrong...@gobberwart fix is correct.

**Comment by Gobberwart** [comment]
Correct, removing events has no effect at all if they're not actually being generated, and no effect on startup in any case. Suggest just not removing any events (although we could perhaps look at why these events even exist and remove the from the bot if they're not used)

**Comment by DBa2016** [comment]
Okay, I removed the code discarding events in the list completely.

**Comment by DBa2016** [comment]
Come on guys...

**Pull request merged**
