### PR TITLE
Correct colored logging

### PR DESCRIPTION
**Pull request by extink**
## Short Description:
Previous colored logging did not use the python logging mechanism, so it ignored the debug configuration for event_handler logs. Also some log entries are added with the previous implementation of the colored logs.

## Fixes (provide links to github issues if you can):
- Debug configuration honored with colored logging
- No modifications or additions to log messages

## Todo
- Create a custom formatter to prettify the log output
- Make the log messages more consistent

### CODE REVIEW

**Comment by relomy** [comment]
Can you add magenta? And actual _white_? Not sure if `'white':  '\033[0m'` is the regular output color vs. the normal console "white."

``` python
'magenta':   '\033[95m',
'white':   '\033[97m',
```

**Comment by douglascamata** [comment]
AWESOME WORK! This is how the coloured log had to be since the beginning. 👏 

Is this ready to merge? Did you test it?

**Comment by extink** [comment]
I have tested it as much as I could. But nothing really specials is happening. Only some formatting characters are added to the formatted messages. I have tested it on Linux/macOS, but I am not able to test it on Windows. It should also work there though!

**Comment by douglascamata** [comment]
👍

**Comment by theolive** [comment]
I have merged your edits and tested on a Windows platform. I am getting this error when run:

> 2016-08-11 14:08:12,704 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-11 14:08:12,714 [       cli] [INFO] Configuration initialized
Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "C:\Program Files\Git\Pgobot\pokemongo_bot\metrics.py", line 81, in capture_stats
    request = self.bot.api.create_request()
AttributeError: 'PokemonGoBot' object has no attribute 'api'

**Comment by vanishing** [comment]
source bin/activate

**Pull request merged**
