### PR TITLE
[dev] Updated README.md to state bot status

### PR DESCRIPTION
**Pull request by mjmadsen**
Added bot status to top of README.md to limit issue posts.

### CODE REVIEW

**Comment by TheSavior** [comment]
Can you use the same message as this PR: https://github.com/PokemonGoF/PokemonGo-Bot/pull/2590

**Comment by mjmadsen** [comment]
Done.

**Comment by solderzzc** [comment]
👍

**Comment by bstpierr** [comment]
👍

**Comment by TheSavior** [comment]
:+1:

**Pull request merged**
