### PR TITLE
Refactor catch worker

### PR DESCRIPTION
**Pull request by pokepal**
This is a refactor of the catch worker to eliminate duplicate berry throwing and ball choosing code and make it more readable/extensible (less nesting, etc)

This should fix a few things like defaulting to first available ball instead of Pokeball (I had issues with throwing -1 pokeballs) and I believe it fixes some issues like:
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2505
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3036
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3092
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3107

### CODE REVIEW

**Comment by pokepal** [comment]
@douglascamata I made a couple changes to the events from https://github.com/PokemonGoF/PokemonGo-Bot/pull/2173, you had `pokemon_fled` as well as `pokemon_vanished` so I changed `pokemon_fled` to `pokemon_capture_failed`

I also added the pokeball name to catch rate related events

**Comment by nikhil-pandey** [comment]
Is it a cell worker? I think its more like Step Walker and should be moved to the parent directory. It will also remove dependency between workers.  #2487

**Comment by douglascamata** [comment]
Can you solve merge conflicts, please?

**Comment by pokepal** [comment]
@douglascamata done!

**Comment by douglascamata** [comment]
@pokepal did you test it? for how long?

**Comment by pokepal** [comment]
@douglascamata I ran it for about an hour before the API broke. I ran a separate config test to compare should capture/is vip logic on some sample data.

I haven't run it since the bot has been back up but don't anticipate problems.

**Comment by BriceSD** [comment]
@pokepal 
```
CATCH_STATUS_SUCCESS = 1
CATCH_STATUS_FAILED = 2
CATCH_STATUS_VANISHED = 3
```
Could you also add a message for status 5/7 of encounter please ? (Not catch this time)
Should be after create_encounter_api_call()
```	
enum Status {
		ENCOUNTER_ERROR = 0;
		ENCOUNTER_SUCCESS = 1;
		ENCOUNTER_NOT_FOUND = 2;
		ENCOUNTER_CLOSED = 3;
		ENCOUNTER_POKEMON_FLED = 4;
		ENCOUNTER_NOT_IN_RANGE = 5;
		ENCOUNTER_ALREADY_HAPPENED = 6;
		POKEMON_INVENTORY_FULL = 7;
	}
```

**Comment by pokepal** [comment]
@BriceSD I added the extra events for 5/7. I'm not sure about the other differences (using 3 "CLOSED" for vanished vs 4 "POKEMON_FLED") but the current status number checks are how they have been for a while and seemed to be working OK.

**Comment by pokepal** [comment]
@douglascamata have had it running all morning, works great for me!

**Comment by pokepal** [comment]
@BriceSD misunderstood your comment earlier, updated again and should be good to go

**Comment by BriceSD** [comment]
@pokepal thanks that's what I wanted! Having a message when Pokémon inventory is full should prevent issues like #3068

**Comment by douglascamata** [comment]
👍

**Comment by TheSavior** [comment]
@nikhil-pandey I agree, this class is definitely not a task and shouldn't be treated as one. We just haven't refactored it out into the parent folder. We would happily accept a PR that did that. 

👍

**Pull request merged**
