### PR TITLE
Added docs about the PokemonHunter

### PR DESCRIPTION
**Pull request by davidakachaos**
Added missing docs about the Pokemon Hunter

### CODE REVIEW

**Comment by davidakachaos** [comment]
@pogarek 😄

**Comment by pogarek** [comment]
👍

**Comment by pogarek** [comment]
merged #5941

**Comment by pogarek** [comment]
done. I need to read about hunter - not using it now. :)

**Comment by davidakachaos** [comment]
It's a kind of "poor mans sniper" 😉

**Comment by pogarek** [comment]
:-) it is supposed to replace another task ? or as additional one ?

**Comment by davidakachaos** [comment]
It's an additional one. I think it was created when the "nearby pokemon" were availible in the game. This task will use that data to look for Pokemon around the current location of the bot. Seems to work as a charm!

**Comment by pogarek** [comment]
I'll test it then. thanks

**Comment by MerlionRock** [comment]
Yup. Has been using it since day one when someone implemented it.

**Pull request merged**
