### PR TITLE
updated movesets

### PR DESCRIPTION
**Pull request by bruno-kenji**
Changed movesets according to [New Update](https://www.reddit.com/r/pokemongodev/comments/4ynq0k/was_game_master_updated_today/).

Not resolving #4323 since it contains useful info until dev is merged into master.

### CODE REVIEW

**Comment by mjmadsen** [comment]
Did you get all of these (from someone's diff):
Here is the complete list of what changed:
Jigglypuff play rough > dazzling dream
Digglet & Dugtrio mud shot > mud slap
graveler & golem mud shot > mud slap
Grimer acid > poising jab
muck acid > lick
Gengar: sludge wave > sludge bomb
Hitmonlee stomp > brick break
Koffing & Weezing removed acid
chansey psybeam > hyperbeam
staryu quick attack > tackle
gyarados removed: dragon breath
porygon quick attack > zen headbut
Omastar rock throw > mud shot
Mew: removed: moonblast hurricane > blizzard

**Comment by MZorzy** [comment]
miss the 1st one.

**Comment by bruno-kenji** [comment]
@mjmadsen Yes. Also, there is a move missing in your list:
Starmie: Psybeam > Psychic

**Comment by bruno-kenji** [comment]
@MZorzy It's there, please check the complete file if you may.

**Comment by MZorzy** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/4338/commits/9e2bce21d9c0c258831304a238e77a8f5e933bf0

Not see dazzling dream

**Pull request merged**
