### PR TITLE
Add PokemonGo bot version to docker image

### PR DESCRIPTION
**Pull request by walkerlee**
## Short Description:

add commit version when create docker image

related to #4884

### CODE REVIEW

**Comment by th3w4y** [comment]
@walkerlee something like this should be simpler:

LABEL BUILD_COMMIT $(curl -H "Accept: application/vnd.github.VERSION.sha" https://api.github.com/repos/$BUILD_REPO/commits/$BUILD_BRANCH)

**Comment by walkerlee** [comment]
@th3w4y yes, but how can we get docker label in docker container?

**Comment by th3w4y** [comment]
@walkerlee you are right cannot execute on LABEL

**Comment by BreezeRo** [comment]
Please merge latest dev changes into this branch first

**Comment by mjmadsen** [comment]
:+1:

**Comment by th3w4y** [comment]
@walkerlee I see you rebased 10c713c...c516a95 and now travis is passing? 
i had the same commit 10c713c NOT failing on my travis repo.. https://travis-ci.org/th3w4y/PokemonGo-Bot/builds/155958771

very strange...

**Comment by walkerlee** [comment]
@th3w4y yes, it's passed
I also test it on my local docker image (python -m unittest discover -v -p "*_test.py")
first test was failed but others were succeed

**Comment by mjmadsen** [comment]
:+1:

**Comment by walkerlee** [comment]
and now image size is 85.28 MB 👍 

```
⋊> ~/pgo on add-pokebot-version  docker images                                                                                                                                                                                       
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
walkerlee/pokemongo-bot   latest              1ebfb4bcdefe        38 minutes ago      85.28 MB
svlentink/pokemongo-bot   latest              9d4f4c4b52d3        About an hour ago   121.6 MB
```

**Comment by mjmadsen** [comment]
The out-of-date seems to apply to files that are not in the PR request, merging them in that case does not cause a conflict. If there are merge conflicts or CI failures are when we need to rebase. I think merge conflicts extend to attempting to merge to files that have been updated since the original PR file's last commit.

**Comment by th3w4y** [comment]
i tried to make it even smaller using PyInstaller on alpine (http://www.pyinstaller.org) managed to bring it down to 32MB (pokecli executable was 24MB ())..

but it was not functional... I would still have to try to figure out why it did not load the protobuff  correctly

**Comment by walkerlee** [comment]
@th3w4y maybe use python:2.7-alpine as base image is better
it's only update pokemongo-bot layers
what do you think?

**Comment by th3w4y** [comment]
@walkerlee for the current setup python:2.7-alpine is about 20MB bigger then after the image at the step 
RUN apk add  python py-pip

**Comment by walkerlee** [comment]
@th3w4y yes, but that base image, only need to pull that layer once

**Comment by th3w4y** [comment]
the we should split like below:

FROM alpine
RUN apk -U --no-cache add python py-pip

then Dockerfile continues...

**Comment by walkerlee** [comment]
@th3w4y you're right

**Comment by th3w4y** [comment]
@walkerlee i'm surprise we did not see it before 🎯

**Comment by walkerlee** [comment]
@th3w4y have you tried this Dockerfile command?
ADD http://pgoapi.com/pgoencrypt.tar.gz /dev/null

**Comment by th3w4y** [comment]
@walkerlee just to check if file was modified.. cool

**Comment by walkerlee** [comment]
@th3w4y let's me create a new PR :octocat:

**Comment by th3w4y** [comment]
@walkerlee  
actually... 
Is this invalidating the cache if there is a new image??? or is it invalidating every time cause it does not server the Last-Modified?

ADD http://pgoapi.com/pgoencrypt.tar.gz /dev/null

**Comment by th3w4y** [comment]
my bad... github.com also does not give the Last-Modified 👎

**Pull request merged**
