### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by sinijvas**
Short Description: 

Fixes:
- 
- 
- 

your console comand, which download api, does not work

### CODE REVIEW

**Comment by jtdroste** [comment]
It should work...I haven't ran into any issues.

According to [this page](http://codeinthehole.com/writing/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/) that's the correct syntax.  What error are you seeing when trying to use our current one?

**Comment by sinijvas** [comment]
script hangs on this place
 [image](https://cloud.githubusercontent.com/assets/20580072/17064002/e51fd046-5042-11e6-9d96-f04427c5fe06.png)

**Comment by jtdroste** [comment]
Please change it to:

```
-e git+https://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi
```

That way we're using a specific commit ID vs the HEAD

**Comment by jtdroste** [comment]
Also check if that fixes your issue

**Comment by sinijvas** [comment]
image

**Comment by Razapo** [comment]
Try installing git which you can get from [here ](https://git-scm.com/downloads).

Then right click on the folder, select git bash and then rush pip install -r requirements.txt
this should work.

**Comment by solderzzc** [comment]
let's close this for now.

**Pull request closed without merging**
