### PR TITLE
Smart pinap function

### LINKED ISSUE #6131: Smart pinap function
### Short Description

I made a "smart pinap" function to maximize the use of pinap berries.
Ex1) If catch rate is over 85% for a normal mon use a pinap, but spare 3 for VIPs
Ex2) If catch rate is over a threshold (90%) for a VIP use a pinap, if under that threshold the original razz berry logic kicks in.
The current logic for VIP is fixed to razz or pinap, and for normal mon the level or CP determines the use of pinap. I think the actual catch rate is more important.

How do I add this to the bot? I am new to github, and I want to contribute to this bot.

### Possible solution

I made something like this in pokemon_catch_worker.py
            # SMART_PINAP: Use pinap when high catch rate, but spare some for VIP with high catch rate
            if self.smart_pinap_enabled and ( (not is_vip and self.inventory.get(ITEM_PINAPBERRY).count > self.smart_pinap_to_keep and catch_rate_by_ball[current_ball] > self.pinap_threshold) or (is_vip and self.inventory.get(ITEM_PINAPBERRY).count > 0 and catch_rate_by_ball[current_ball] >= self.vip_berry_threshold) ) and not used_berry:
                berry_id = ITEM_PINAPBERRY
                new_catch_rate_by_ball = self._use_berry(berry_id, berry_count, encounter_id, catch_rate_by_ball, current_ball)
                self.inventory.get(berry_id).remove(1)
                berry_count -= 1
                used_berry = True

### How it would help others

Instead of throwing away pinap berries, you can get more candy!

### PR DESCRIPTION
**Pull request by ChiefM3**
## Short Description:
- Added a new "smart pinap" function. Throws a pinap berry according to the catch rate which does not interfere with the existing razz berry logic.
- ex: If `smart_pinap_enabled`=true && `smart_pinap_threshold` = 0.85 && `berry_threshold` = 0.4, pokemon with catch rate 0-0.4 will be razzed, 0.85-1 will be pinapped.
- descriptions added to configuration_files.md

## Fixes/Resolves/Closes (please use correct syntax):
- Closes #6131

### CODE REVIEW

**Comment by ChiefM3** [comment]
Thank you @nbq for walking me through my first PR!

**Comment by nbq** [comment]
@ChiefM3 you are very welcome!

**Comment by MerlionRock** [comment]
👍

**Comment by MerlionRock** [comment]
Congrats on your 1st PR

**Pull request merged**
