### PR TITLE
Mode/Cell Changes

### PR DESCRIPTION
**Pull request by heihachi**
Short Description: 
Should help fix the no catching pokemon after 1st/2nd pokestop. Modes can switch back to 'all' after farming 10+ pokeballs and losing 50 items in bags (recycle, login to app, or catching)
Fixes:
- Mode switching back and forth
- Cells update each tick and after a timer of 10 secs inbetween (this can be removed if theres no harm in doing constant scans)

### CODE REVIEW

**Comment by heihachi** [comment]
Mainly need feedback as to if its working for you or if the issue is still present.

**Comment by TheSavior** [comment]
I don't think we want this. This problem:
screen shot 2016-07-24 at 5 55 09 pm

is because of this code 
```
for fort in forts:
                    worker = MoveToFortWorker(fort, self)
                    worker.work()

                    worker = SeenFortWorker(fort, self)
                    hack_chain = worker.work()
```

It currently finishes looping through forts before it changes mode.

The solution we need to take is to have the worker only consider the first fort, which would then let it approach other forts on subsequent iterations. That would let it switch modes after the first fort that says it is full.

**Comment by TheSavior** [comment]
@heihachi: Happy to elaborate more on the previous comment if you need it. I'm going to close this PR as this approach isn't compatible with the architecture we are moving towards. Please feel free to open another PR if need be.

**Comment by heihachi** [comment]
@TheSavior will do thanks! and i can rework that if noone else is on it

**Comment by heihachi** [comment]
Also should i make another PR with just the switching back and forth from all -> poke and all -> farm?

**Pull request closed without merging**
