### PR TITLE
Fix evolve_all does not sleep problem

### PR DESCRIPTION
**Pull request by vicch**
Short Description: 
`EvolveAll` worker tries to evolve every tick, the `sleep()` after calling API does not affect the speed.

Fixes:
- Try to evolve every certain number of ticks.

### CODE REVIEW

**Comment by vicch** [comment]
Should be able to fix #1935

**Comment by vicch** [comment]
By setting the value to 10:
```
[19:34:27] [#] Successfully evolved Weedle with 301 CP and 0.53 IV!
[19:34:38] [#] Successfully evolved Pidgey with 297 CP and 0.53 IV!
[19:34:46] [#] Successfully evolved Caterpie with 281 CP and 0.53 IV!
[19:34:56] [#] Successfully evolved Caterpie with 196 CP and 0.53 IV!
[19:35:06] [#] Successfully evolved Pidgey with 348 CP and 0.51 IV!
[19:35:16] [#] Successfully evolved Pidgey with 268 CP and 0.51 IV!
[19:35:22] [#] Successfully evolved Spearow with 512 CP and 0.49 IV!
[19:35:31] [#] Successfully evolved Pidgey with 453 CP and 0.49 IV!
[19:35:38] [#] Successfully evolved Pidgey with 396 CP and 0.49 IV!
[19:35:48] [#] Successfully evolved Pidgey with 375 CP and 0.49 IV!
[19:35:58] [#] Successfully evolved Pidgey with 325 CP and 0.49 IV!
[19:36:08] [#] Successfully evolved Caterpie with 316 CP and 0.49 IV!
[19:36:15] [#] Successfully evolved Weedle with 283 CP and 0.49 IV!
[19:36:24] [#] Successfully evolved Pidgey with 262 CP and 0.49 IV!
[19:36:31] [#] Successfully evolved Pidgey with 490 CP and 0.47 IV!
[19:36:40] [#] Successfully evolved Pidgey with 430 CP and 0.47 IV!
```

**Comment by pokecunt** [comment]
download

**Comment by TheSavior** [comment]
The reason we sleep after evolving is to pretend like we are watching the evolve animation. Sleeping for a number of ticks would not give us that.

**Pull request closed without merging**
