### PR TITLE
Gym changes

### PR DESCRIPTION
**Pull request by davidakachaos**
## Short Description:
Multiple changes for the Gym feature.

- Ignore the CP limit for certain Pokemon
- Never place certain Pokemon in gyms
- Leave at least X spots in gyms for normal players (don't rob the last spot!)
- Take at most X gyms
- Pick a random Pokemon from the "order_by" or pick the top one
- Disable "drop chaining" Pokemon in gyms -> When we drop a Pokemon in a gym, give other workers a chance to work.

Removed all code about "feeding" Pokemon in gyms. This should be its own worker, or at least work. No need for this right now in the bot. (sorry @goedzo for kicking all that code out, you can leave it in your own fork!)

### CODE REVIEW

**Comment by MerlionRock** [comment]
👍

**Comment by goedzo** [comment]
What did you change? It looks like gympokemon is not working anymore. I don't see any messages from it. Originally bot started with a message showing all mons in gyms. I don't see this message anymore, and don't see any messages that it is looking for gyms. It now appears af is this walker is never called anymore.

**Comment by davidakachaos** [comment]
That's very strange! You can see what has changed in the diff... I can look
tonight, currently not at home

Op 23 jul. 2017 15:51 schreef "goedzo" <notifications@github.com>:

**Comment by goedzo** [comment]
I have no idea, what changed. It looks like MoveToFort is messing it up:

        {
            "type": "MoveToFort",
            "config": {
                "enabled": true,
                "lure_attraction": true,
                "lure_max_distance": 2000,
                "walker": "PolylineWalker",
                "log_interval": 60
            }
        },
   
Because that one is always working, and not gym pokemon. I suggest reverting this now, untill it works. I don't even see the starting message anymore that it has x pokes in gyms.

**Comment by goedzo** [comment]
Oh wait, I am very stupid :)

        {
            "type": "GymPokemon",
            "config": {
                "enabled": false,
                "order_by": "cp",
                "min_interval":360,
                "min_recheck":30,
                "max_recheck":120,
                "chain_fill_gyms": true,
                "ignore_max_cp_pokemon": ["Blissey"],
                "never_place": ["Machamp"],
                "leave_at_least_spots": 0,
                "take_at_most": 20,
                "pick_random_pokemon": true
            }
        },


I had it set to false. Stupid me!

**Comment by goedzo** [comment]
Yup, that was it :)

[2017-07-23 16:01:41] [GymPokemon] [INFO] Inspecting 15 gyms.
[2017-07-23 16:01:41] [GymPokemon] [INFO] Recent gyms: 0
[2017-07-23 16:01:41] [GymPokemon] [INFO] Active raid gyms: 0
[2017-07-23 16:01:41] [GymPokemon] [INFO] Gym Teams Instinct(6), Mystic(4), Valor(5)

Sorry about the confusion LOL

**Comment by davidakachaos** [comment]
Stop worrying me soooooooo much hahahaha

Op 23 jul. 2017 16:02 schreef "goedzo" <notifications@github.com>:

**Comment by goedzo** [comment]
Well got into another bug thoug. App crashes when deploying:

[2017-07-23 16:21:49] [       cli] [INFO] Most Perfect Pokemon: Swinub [CP: 10] [IV: 14/14/15] Potential: 0.96
Traceback (most recent call last):
  File "pokecli.py", line 884, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 834, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/gym_pokemon.py", line 154, in work
    result = self.move_to_destination()
  File "/usr/src/app/pokemongo_bot/cell_workers/gym_pokemon.py", line 320, in move_to_destination
    self.drop_pokemon_in_gym(self.destination, current_pokemons)
  File "/usr/src/app/pokemongo_bot/cell_workers/gym_pokemon.py", line 438, in drop_pokemon_in_gym
    stdout.write("\033[1A\033[0K\r")
NameError: global name 'stdout' is not defined

**Comment by goedzo** [comment]
You're missing:
from sys import stdout
Adding a hotfix now to code.

**Comment by davidakachaos** [comment]
Thanks

Op 23 jul. 2017 16:30 schreef "goedzo" <notifications@github.com>:

**Comment by goedzo** [comment]
Still crashing. Please test properly before pulling.

[2017-07-23 16:45:09] [       cli] [INFO] Most Perfect Pokemon: Goldeen [CP: 388] [IV: 15/7/14] Potential: 0.8
Traceback (most recent call last):
  File "pokecli.py", line 884, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 834, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/gym_pokemon.py", line 156, in work
    result = self.move_to_destination()
  File "/usr/src/app/pokemongo_bot/cell_workers/gym_pokemon.py", line 322, in move_to_destination
    self.drop_pokemon_in_gym(self.destination, current_pokemons)
  File "/usr/src/app/pokemongo_bot/cell_workers/gym_pokemon.py", line 465, in drop_pokemon_in_gym
    if not first_time:
UnboundLocalError: local variable 'first_time' referenced before assignment

**Pull request merged**
