### PR TITLE
improve docker pull speed

### PR DESCRIPTION
**Pull request by walkerlee**
## Short Description:

- docker pull speeded up when it need to update image layers (only pokemongo-bot src)
- it's not very often that we need to rebuild pgoencrypt

```
⋊> ~ curl -sI http://pgoapi.com/pgoencrypt.tar.gz | grep Last-Modified                                                                                                                                                                00:52:09
Last-Modified: Sun, 07 Aug 2016 00:36:22 GMT
```

### CODE REVIEW

**Comment by solderzzc** [comment]
👍

**Comment by solderzzc** [comment]
>This branch is out-of-date with the base branch

**Comment by th3w4y** [comment]
@k4n30 LGTM this can be merged... was previously discussed also on https://github.com/PokemonGoF/PokemonGo-Bot/pull/4886

this improves the pull speed for consecutive builds because it adds python as one of the first layers of the image... thus if requirements change you will not have to pull that layer again...

**Comment by mjmadsen** [comment]
:+1:

**Pull request merged**
