### PR TITLE
update config.json.path and config.pokemon item_filter

### PR DESCRIPTION
**Pull request by wdjwxh**
Short Description: 

Fixes:
config.json.path
config.json.pokemon 
item_filter use name like config.json
- 
-

### CODE REVIEW

**Comment by DayBr3ak** [comment]
You changed the Key, alright, but how does it works? You didn't change any code

**Comment by TheSavior** [comment]
:+1:

**Comment by surfaace** [comment]
:+1:

**Comment by surfaace** [comment]
please fix conflicts so we can merge

**Comment by DayBr3ak** [comment]
Isn't this already implemented ?

**Comment by TheSavior** [comment]
@DayBr3ak Yeah, looks like it. Thanks for pointing that out.

**Pull request closed without merging**
