### PR TITLE
Keep best CP pokemon after merging all changes.

### PR DESCRIPTION
**Pull request by koper89**
Former pull:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/880

### CODE REVIEW

**Comment by surfaace** [comment]
can you push in updated config.json.example(s) please

**Comment by koper89** [comment]
Added

**Comment by Nihisil** [comment]
Please, merge current dev into your PR and resolve all conflicts. I would like to have this PR merged 👍

**Comment by anziclone** [comment]
We need to filter by Pokemon ID than by name...This will ensure all Pokemon get checked. Besides this, the functionality doesn't seem to be working.

**Comment by surfaace** [comment]
@koper89 your code doesnt read specific configured pokemons, but you have included it into config example.
I like this feature, could you please correct your code, also as @Nihisil said. merge down current dev in order to resolve conflicts :)

**Comment by solderzzc** [comment]
Oh, no, conflict again...

**Comment by koper89** [comment]
@surfaace Correct me If I'm wrong but this line:
release_config = self._get_release_config_for(pokemon_name)
Is reading config based of pokemon if exists if not then goes to any. So it does take specific pokemons as well.

**Comment by Nihisil** [comment]
I think PR can be closed, because we pulled a little bit general version of it to the dev https://github.com/PokemonGoF/PokemonGo-Bot/pull/1302

**Pull request closed without merging**
