### PR TITLE
fix #1766

### LINKED ISSUE #1766: dev branch crash in incubate_eggs_worker
Expected behaviour is that the bot doesn't crash. :) Actual behaviour:
[06:05:41] Moving towards fort 71db06db5f9447bba4a35b33d3a2eaf2.16, 0.47km left
[06:05:46] Moving towards fort 71db06db5f9447bba4a35b33d3a2eaf2.16, 0.46km left
Traceback (most recent call last):
  File "pokecli.py", line 450, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "C:\Miniconda2\envs\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 84, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Miniconda2\envs\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\incubate_eggs_worker.py", line 29, in work
    self._hatch_eggs()
  File "C:\Miniconda2\envs\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\incubate_eggs_worker.py", line 134, in _hatch_eggs
    for pokemon in pokemon_data:
UnboundLocalError: local variable 'pokemon_data' referenced before assignment

Just above it looks to be try-except statement for assigning to pokemon_data. It's been over a decade since I've had to know Python intimately, so I'm not certain which circumstances could cause it to become unassigned. But it seems like either that except-branch needs to skip the whole following code, or the try branch needs to assign to temporary and assign it over to pokemon_data only if that succeeds.

### PR DESCRIPTION
**Pull request by CapCap**
Short Description: 
dont use variables before you declare them

Fixes:
- #1766

### CODE REVIEW

**Comment by Nihisil** [comment]
It is not fix, because `pokemon_data` not suppose to be empty.

So, something crashed inside `def _check_inventory()` and we need to fix it.

**Comment by Nihisil** [comment]
So, we need to find out why it crashed and fix it.

Also, as back up plan just in case we need to set `pokemon_data = []` as you did.

**Comment by CapCap** [comment]
yes, absolutely there is another problem: but there's no reason to try/catch if youre guaranteed to fail anyway

**Comment by Nihisil** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1777 more global fix

**Pull request closed without merging**
