### PR TITLE
Inventory refresh before hatching eggs

### PR DESCRIPTION
**Pull request by Gobberwart**
## Short Description:

Added inventory.refresh() to egg hatching, otherwise the inventory can't provide information needed for correct display.

## Fixes/Resolves/Closes (please use correct syntax):
- #4966 

Egg hatching needs a current copy of inventory (post egg hatching) to be
able to display details. Api call to refresh inventory occurs if there
are eggs to hatch.

### CODE REVIEW

**Comment by Gobberwart** [comment]
I *think* this should take care of the issue people are seeing where egg hatching reports "[IncubateEggs] [INFO] [egg_hatched] {'candy': 'error', 'iv': 'error', 'stardust': 'error', 'exp': 'error', 'cp': 'error', 'pokemon': 'error'}"

I've spent about 3 hours debugging and testing this... seems that the bot compares hatched egg ids (from api call) against inventory to get complete details, but if the inventory isn't 100% up-to-date it fails. 

This fix adds a new api call, but ONLY when the api says there are newly-hatched eggs, so should be very infrequent.

**Comment by Gobberwart** [comment]
For those playing at home, it works like this:

- If km left to walk <= 0...
- Send api request to server to get the ids of the newly-hatched pokemons, then...
- Look in the cached inventory for matching ids (that aren't still in eggs) and retrieve extended data

If the inventory is not 100% up-to-date, there won't be any matches, so the bot displays errors everywhere.

Does this make sense? I hope so, I'm tired.

**Comment by solderzzc** [comment]
👍

**Comment by Gobberwart** [comment]
Nooooooooooo!!! Looks like @DeXtroTip already did the same thing while I was faffing about. Now there's duplicate refreshes.

**Comment by Gobberwart** [comment]
Closing this as it's duplicated by https://github.com/PokemonGoF/PokemonGo-Bot/commit/fdcbd7644543c9b2b719fd1ab115f3225313d0d3

**Pull request closed without merging**
