### PR TITLE
Removed all references to i2f in code

### PR DESCRIPTION
**Pull request by LasseSkogland**
Short Description: 
Removed all references to I2F in code since it is no longer needed in newer pgoapi versions.
Fixes:
- I2F removed
- 
-

### CODE REVIEW

**Comment by douglascamata** [comment]
Are you sure this is the only necessary change?

**Comment by douglascamata** [comment]
Please test for at least 10 to 15 minutes.

**Comment by LasseSkogland** [comment]
Will do

**Comment by douglascamata** [comment]
@LasseSkogland btw, `get_cellid` is also bundled in `pgoapi.utils` can you test importing from there?

**Comment by Zgrkaralar** [comment]
First working perfectly

screen shot 2016-07-27 at 1 26 53 am

When visit pokestore that is error
screen shot 2016-07-27 at 1 27 44 am

**Comment by LasseSkogland** [comment]
Seems like geolocated locations like "Santa Monica Pier" needs the i2f to be converted to floats, pull request breaks the GeoLocator...

I'm to tired for this, if this is still a issue tommorow I'll look into it.
**Until then do not merge this PR**

**Comment by LasseSkogland** [comment]
@Zgrkaralar this issue has nothing to do with this PR (I think), I did not change anything but remove the i2f function calls...

**Comment by Zgrkaralar** [comment]
@LeaklessGfy Yes pgoapi is broke it all now :/

**Comment by LasseSkogland** [comment]
Closing this PR, because much more work than this is needed to use the new pgoapi

**Pull request closed without merging**
