### PR TITLE
Adding a test change

### PR DESCRIPTION
**Pull request by TheSavior**
Testing the mention bot

### CODE REVIEW

**Comment by TheSavior** [comment]
Sorry @tejado, we will blacklist you from the possible reviewers.

**Comment by TheSavior** [comment]
Blacklist added here: https://github.com/PokemonGoF/PokemonGo-Bot/commit/f7975bb33cbc5e9a735782a0bc9dcf961a75b6ec

**Comment by tejado** [comment]
why? ;-(

**Comment by douglascamata** [comment]
@TheSavior you made @tejado sad 😞

**Comment by TheSavior** [comment]
@tejado Would you like to be mentioned on pull requests? We'd be happy to have you! I figured you were too important. 👑

**Pull request closed without merging**
