### PR TITLE
After 1 hour relogin

### PR DESCRIPTION
**Pull request by unequaled86**
Fixes:
- because after 1 hour bot gonna stuck loop

### CODE REVIEW

**Comment by MikeDX** [comment]
Would be much better to check the expiry time of the login token and relogin when that has failed rather than some arbitrary time which may be wrong is the auth token expires sooner

**Comment by MikeDX** [comment]
Just tested this, and it doesn't work since you are setting the statedtime to the current time each loop, so it will never reach startedtime+60*60.

**Comment by unequaled86** [comment]
i tested man its worked. startedtime setted on bot login

**Comment by MikeDX** [comment]
It might work but it is a bodge. I've submitted a correct patch that checks the session time, which then refreshes once the token is about to expire.

**Comment by ProjectBarks** [comment]
#735 fixes this but thanks

**Pull request closed without merging**
