### PR TITLE
Detect and alert for permaban

### PR DESCRIPTION
**Pull request by net8q**
## Short Description:
Detect for permaban

Example of permaban proto response : 
1: 3
2: request_id
100: ""

GET_INVENTORY is the first affected in the login sequence, GET_PLAYER is not.

### CODE REVIEW

**Comment by TheSavior** [comment]
:+1:

**Comment by TheSavior** [comment]
I don't think this PR is quite right for the different responses. The bot says my account says it was permabanned, but when I sign in on a device, the app says:

"Our servers are humbled by your incredible response. We are working to resolve the issue. Please try again soon!"

**Comment by net8q** [comment]
Well, there are reports that this screen is symptom a permaban too. Main symptom I've observed at the API level is that GET_PLAYER is ok but GET_INVENTORY is not. At login, GET_PLAYER would come first, so if the servers are down, I'm hoping the server problem would be caught there.

**Comment by liwenzhuo1216** [comment]
@TheSavior ， hey， "Our servers are humbled by your incredible response. We are working to resolve the issue. Please try again soon!"  this definitely means you are banned, man!

**Comment by TheSavior** [comment]
Sad day.

**Comment by omeryagmurlu** [comment]
@liwenzhuo1216 Don't be so sure, my "main" bot account is getting this on mobile too, but I am able to connect using APIs. Getting that message doesn't mean anything.

**Comment by liwenzhuo1216** [comment]
@omeryagmurlu  hmmm, yeah, you are right. If the network condition is not so good, you will also get this on your mobile. But when you get this on your mobile and can't even use bots, a sad story....

**Pull request merged**
