### PR TITLE
file should be ignored and used as example

### PR DESCRIPTION
**Pull request by surfaace**
release_config.json will be edited by all users

### CODE REVIEW

**Comment by solderzzc** [comment]
@douglascamata  How do you think about?

**Comment by tehp** [comment]
Agreed. Looks good to me.

**Comment by solderzzc** [comment]
But without this, will the bot works normallY?

**Comment by tehp** [comment]
Yeah, all the gitignore does is prevent git from tracking changes on the file.

**Comment by solderzzc** [comment]
but without default value, will this work?
release_config.json → release_config.json.example

**Pull request merged**
