### PR TITLE
corrected logic to respect snipe = true

### PR DESCRIPTION
**Pull request by DBa2016**
- move_to_map was ignoring pokemons which were beyond "max distance" (which is normal for sniping); an "or" had to be changed to "and" in order to only ignore such pokemons if sniping was turned off.

### CODE REVIEW

**Comment by mjmadsen** [comment]
:+1:

**Comment by mjmadsen** [comment]
Closes #4837

**Comment by DBa2016** [comment]
Oops, did not realize there was an open issue for this. :)

Just wanted to fix it and get rid of manually editing the file upon new checkouts :D

**Comment by mjmadsen** [comment]
Can you rebase, I just merged something else.

**Comment by DBa2016** [comment]
sure... how do I do that? :)

**Comment by DBa2016** [comment]
Actually the label says it can be automatically merged, so you should be able to merge regardless?...

**Comment by mjmadsen** [comment]
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by DBa2016** [comment]
There are no conflicts, you can just merge this PR without rebasing...

**Comment by mjmadsen** [comment]
"This branch is out-of-date with the base branch
Merge the latest changes from dev into this branch."

**Comment by DBa2016** [comment]
Try now please (looks like this rebase can be taken care of by using "update branch"...).

**Comment by mjmadsen** [comment]
From what I can tell, the little pull approved thing changes what I see for conflicts. Sorry to be a pain, not sure if it would have made a difference. 

Thanks for the PR!

**Comment by Jasperrr91** [comment]
@mjmadsen please revert, this should not be merged. The issue was caused by an incorrect config by @dummyaja, @warxhead1, @daemonsyn, @DBa2016 . If anything, the readme should be updated.

The MoveToMapPokemon handler and it's config block handle the logic for sniping. The `Max_distance` in there needs to be correctly set to limit the snipe distance. Some people only want to snipe within 10km for example, others want to snipe the entire world. That's the sole purpose of `max_distance`.

This merge breaks that functionality. Which was restored in https://github.com/PokemonGoF/PokemonGo-Bot/pull/4772

**Pull request merged**
