### PR TITLE
Make the tracking of user data disabled by default

### PR DESCRIPTION
**Pull request by dvl**
I don't think it's ok to collect user data without the explicit permission of the user.

### CODE REVIEW

**Comment by Jasperrr91** [comment]
The data is solely used to keep track of bot usage and errors. It does not contain any personal information. I do not see any reason as to why it should be disabled.

**Comment by th3w4y** [comment]
Is anybody from the PokemonGoF organisation members using the data from the analytics?

**Comment by Jasperrr91** [comment]
@brantje can you give some more information?

**Comment by solderzzc** [comment]
Ip information was purged from the google analysis, so no user information leaking to server side. Leave it false by default will limit our motivation when seeing no users on the using list.

**Pull request closed without merging**
