### PR TITLE
Only catch Exception subclasses

### PR DESCRIPTION
**Pull request by cwild**
Do not use "except:" as this is unlikely to always behave as desired!

Fixes:
- Catch "Exception"s and let things like SystemExit, KeyboardInterrupt bubble up

### CODE REVIEW

**Comment by douglascamata** [comment]
@cwild errr.... every exception inherits from `Exception`. The bad behaviours are catching `Exception` and not exactly the type of exception you expect, and having a fucking lot of code in one `try...except` block.

**Comment by cwild** [comment]
Not every exception inherits from Exception, you can see the inheritance hierarchy on this page:
https://docs.python.org/2/library/exceptions.html

This is why ```except:``` is bad:
https://docs.python.org/2.7/howto/doanddont.html#except

If you try to raise a SIGINT during the ```try... except:...``` then it will swallow the resulting ```KeyboardInterrupt``` and won't close as expected.

**Comment by douglascamata** [comment]
@cwild I see.

**Comment by douglascamata** [comment]
👍

**Comment by surfaace** [comment]
:+1:

**Pull request merged**
