### PR TITLE
enable simple log output

### PR DESCRIPTION
**Pull request by rawgni**
## Short Description:

add -sl / --simplelog to pokecli.py

## Fixes/Resolves/Closes (please use correct syntax):
- #4800 
-
-

### CODE REVIEW

**Comment by Gobberwart** [comment]
This should work... ish, but I'm not a fan of this approach as it's putting logger logic into the main bot client and it should be kept separate. Additionally, it requires a command line switch (should be in config).

Suggest adding something appropriate to config, and setting the logging options in the logger class (both logging_handler and colored_logging_handler) initialization, eg.

if self.config.logging_simple:
    logging.basicConfig(level=logging.INFO, format='%(message)s')

**Comment by mjmadsen** [comment]
We finally merged #3706. I think it does a similar function. I'll leave up until further review.

**Comment by Gobberwart** [comment]
@mjmadsen Similar, but doesn't appear to strip date/time, just the "extra" info (process name etc.)

Needs another config option to strip d/t?

**Comment by mjmadsen** [comment]
@Gobberwart good eye. It would be nice if we could add to #3706 on which parts we want to see (each a separate config var).

**Comment by Gobberwart** [comment]
@mjmadsen Something like that. Maybe something like:

logging: {
    datetime: true/false,
    processinfo: true/false,
    otherstuff: true/false
}

**Comment by mjmadsen** [comment]
@Gobberwart Yeah, that'd be perfect.

**Comment by Gobberwart** [comment]
@mjmadsen I've done some work on this but I'm not entirely satisfied that the way I've read the config options is the best/correct way to do it. Could you please cast an expert eye over #4832

**Comment by Gobberwart** [comment]
I think PR #4832 can replace this as it provides even more options in a cleaner way.

**Comment by rawgni** [comment]
close in favour of #4832

**Pull request closed without merging**
