### PR TITLE
Make initial_transfer use release config

### PR DESCRIPTION
**Pull request by alvarogzp**
Modify the initial_transfer feature so that instead of releasing all pokemons below a certain CP, use the release config to decide whether release the pokemon or not.

### CODE REVIEW

**Comment by VictorChen** [comment]
would be good to update the documentation as well:

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/README.md#advance-configuration

**Comment by douglascamata** [comment]
@alvarogzp please fix readme because I love this PR.

**Comment by alvarogzp** [comment]
@solderzzc @douglascamata done! I have also set initial_transfer to false in config examples

**Comment by alvarogzp** [comment]
I have also added me to contributors :P

**Comment by douglascamata** [comment]
@alvarogzp try to reuse this code from PokemonCatchWorker to respect iv, cp and have a configurable logic between them(`iv AND cp` or `iv OR cp`)

```python
def should_release_pokemon(self, pokemon_name, cp, iv, response_dict):
        release_config = self._get_release_config_for(pokemon_name)
        cp_iv_logic = release_config.get('logic')
        if not cp_iv_logic:
            cp_iv_logic = self._get_release_config_for('any').get('logic', 'and')

        release_results = {
            'cp': False,
            'iv': False,
        }

        if release_config.get('never_release', False):
            return False

        if release_config.get('always_release', False):
            return True

        release_cp = release_config.get('release_below_cp', 0)
        if cp < release_cp:
            release_results['cp'] = True

        release_iv = release_config.get('release_below_iv', 0)
        if iv < release_iv:
            release_results['iv'] = True

        logic_to_function = {
            'or': lambda x, y: x or y,
            'and': lambda x, y: x and y
        }

        #logger.log(
        #    "Release config for {}: CP {} {} IV {}".format(
        #        pokemon_name,
        #        min_cp,
        #        cp_iv_logic,
        #        min_iv
        #    ), 'yellow'
        #)

        return logic_to_function[cp_iv_logic](*release_results.values())

    def _get_release_config_for(self, pokemon):
        release_config = self.config.release.get(pokemon)
        if not release_config:
            release_config = self.config.release.get('any')
        if not release_config:
            release_config = {}
        return release_config
```

**Comment by alvarogzp** [comment]
@douglascamata the problem is that the IV has to be calculated, and that logic is buried inside pokemon_catch_worker, but I will try :)

**Comment by douglascamata** [comment]
@alvarogzp oh crap, I forgot that. Maybe you can extract that logic too. I would be great!

**Comment by alvarogzp** [comment]
@douglascamata I think it is completed now

**Comment by Zgrkaralar** [comment]
Hello,

I try it first i catch one ratata 249 cp
screen shot 2016-07-26 at 10 14 40 pm
After that i stop to script and worked again
screen shot 2016-07-26 at 10 14 32 pm
Show to that massage 
 **Cleaning up Pokemon Bag using the release CP config**
Notting more it must be send to prof. :( 

screen shot 2016-07-26 at 10 15 16 pm

After few poke store show me that error "unfortunately I am not sure that error about this but i saw it"
screen shot 2016-07-26 at 10 18 10 pm

@solderzzc

**Comment by alvarogzp** [comment]
@Zgrkaralar please put your release config to see if it does not released because of it.

Also, please update to last commit (as now it uses also IV to decide if exchange or not).

**Comment by douglascamata** [comment]
Please test this a lot, guys. It's very important for release code to not have bugs.

**Comment by SteffanLong** [comment]
I have code that removes initial transfer entirely in favor of a worker that checks every loop what needs to be released. We can merge this, but my PR if accepted will just delete it. :)

**Comment by douglascamata** [comment]
@SteffanLong where is you PR, dude? Someone did this too and PR is open, just want to merge this first

**Comment by SteffanLong** [comment]
@douglascamata It was closed because diff was too large. I haven't had time to merge upstream, fix the conflicts, and then create multiple PRs yet. Go ahead and merge this, least it will help for the time being.

**Pull request merged**
