### PR TITLE
Adjusted parts of the ReadMe

### PR DESCRIPTION
**Pull request by BartKoppelmans**
I assume that these parts should be like this. Please deny the PR if it is wrong

### CODE REVIEW

**Comment by douglascamata** [comment]
@BartKoppelmans can you remove the duplicated requirements section close to the end of the readme?

**Comment by BartKoppelmans** [comment]
Done 😄

**Comment by douglascamata** [comment]
@BartKoppelmans it's still there... delete it, please.

**Comment by BartKoppelmans** [comment]
Like this? I thought that part was different, so that it should stay there (as it was there in the original file as well)

**Comment by douglascamata** [comment]
Yes, just like that. Merging, thanks!

**Comment by BartKoppelmans** [comment]
You're welcome!

**Pull request merged**
