### PR TITLE
Transfer Pokemon New Implementation.

### PR DESCRIPTION
**Pull request by techedlaksh**
Short Description: Transfer Pokemon while farming. 

Fixes:
- Takes consideration of cp set by user. Only transfer less than set cp.
- Leaves 1 unique highest CP pokemon of its category
- Showing information of pokemon which is being transferred using different color prints.
- Also shows how many total pokemon is transferred

### CODE REVIEW

**Comment by douglascamata** [comment]
@techedlaksh this is already being implemented at https://github.com/PokemonGoF/PokemonGo-Bot/pull/277 as an improved `-c` flag. It will support `-c smart` to leave just the highest CP pokemon of each kind.

**Comment by techedlaksh** [comment]
I actually was working on this but i guess somebody else did earlier than me !

**Comment by techedlaksh** [comment]
@douglascamata anyways can you accept my contribution PR. i forgot to add it when i made my first 2 PR's yesterday and can you send me that slack invite :) 
Thanks!

**Comment by douglascamata** [comment]
@techedlaksh sorry, I can't because you're imposing a behaviour without a switch to use it or not.

**Comment by douglascamata** [comment]
@techedlaksh btw, tomorrow there will be more slack invites and you will be able to join. We're looking forward to have you there!

**Comment by techedlaksh** [comment]
Oh its okay! 
Thanks anyways. :)

**Comment by douglascamata** [comment]
I'm sorry :(

**Pull request closed without merging**
