### PR TITLE
Improve IncubateEggs

### PR DESCRIPTION
**Pull request by DeXtroTip**
## Short Description:
Now it shows all eggs currently incubating, ordered from the first going to hatch to the last.
Added "min_interval" setting at config file to print eggs info periodically. It will still show if an egg hatched or was incubated outside this interval.

### CODE REVIEW

**Comment by solderzzc** [comment]
Oh, I need revert this since the CI build failed.

**Comment by k4n30** [comment]
@DeXtroTip Care to recreate as this was reverted

**Comment by solderzzc** [comment]
I think this my mistake ? I fixed another issue caused the CI thing. Any advise ?

**Comment by solderzzc** [comment]
OK, I didn't revert this one, just created a revert PR and then closed it.

**Pull request merged**
