### PR TITLE
Add simple nearby pokemon hunter cellworker (+ radar output feature)

### PR DESCRIPTION
**Pull request by z4ppy**
Generate simple search path and run it when pokemons are nearby bot (config : vips, count).
Can output the game radar (option)

TODO
- better search path
- an algorithm to approximate Pokemon vips
- handle vip or better place to hunt meanwhile started search (reinit)
- more options (start when no move, lures camping, bag full, ...)
- PokemonMap Synergie : vips position deduction (encounter_id)

### CODE REVIEW

**Comment by yungfrancis** [comment]
Awesome work fella, testing it and I love it.

**Comment by douglascamata** [comment]
There's already a task to snipe pokemons based on PokemonMap. 

This PRs has too much output, please only log as little as possible and only actions that are really necessary to be logged.

**Comment by Nik0lashka** [comment]
@z4ppy, in #1992 script loads data from https://github.com/AHAAAAAAA/PokemonGo-Map and tries to catch pokemons by simple logic and some hacks. But if you will add your path ideas or may be some sort of "best route", that helps to visit maximum amount of visible pokemons before they vanish using "Traveling Salesman Problem" algorythms - that would be great.

**Comment by z4ppy** [comment]
Fixed:  log  & snail speed

**Comment by TheSavior** [comment]
I'm not sure why this task looks like it does so many things. Catching pokemon should be separate from movement. What does this do that the other tasks don't do?

**Comment by k4n30** [comment]
@z4ppy this merge is severly outdated. How do you want to proceed?

**Comment by solderzzc** [comment]
Outdate, need close. Thanks for PR.

**Pull request closed without merging**
