### PR TITLE
Add Items option live stats (such as Pokeballs and Potions)

### PR DESCRIPTION
**Pull request by joaodragao**
# "How many pokeballs do I have?"
This is something missing in live stats or maybe this is the feature I want the most.

This update will allow users to see number of items in the bag storage.

`... | Pokeball x 145, Greatball x 5, Ultraball x 0, Razz Berry x 85 | ...`

or in abbreviation mode:

`... | Px149, Gx4, Ux0, Bx83 | ...`

(Sorry if I break the code.)

In the `stats` of `UpdateLiveStats` task, you just add a dictionary with providing `type` and `config` as shown in example below.

```
        {
            "type": "UpdateLiveStats",
            "config": {
                "min_interval": 120,
                "stats": [
                    "uptime",
                    ...
                    {
                        "type": "items_short",
                        "config": [
                            "Pokeball",
                            "Greatball",
                            "Ultraball",
                            "Razz Berry"
                        ]
                    }
                ],
            }
        },
```

 I want to generalize all stats. Thus, you also can put just only `type` without `config` which is equal to stats's name alone.

```
                    {
                        "type": "uptime"
                    }
```

These are all available items:

```
                            "Pokeball",
                            "Greatball",
                            "Ultraball",
                            "Masterball",
                            "Razz Berry",
                            "Potion",
                            "Super Potion",
                            "Hyper Potion",
                            "Max Potion",
                            "Revive",
                            "Max Revive"
```

### CODE REVIEW

**Comment by TheSavior** [comment]
Your build failed

**Comment by joaodragao** [comment]
@TheSavior Can you check it again? Can you tell me which part is failed to build? Now I fixed it and also added some examples in `config` files.

**Comment by Moonlight-Angel** [comment]
Noice. You broke it though. The build fails because the unit tests don't success anymore.
Also, you didn't provide unit tests for what you added.

**Comment by joaodragao** [comment]
@Moonlight-Angel Ok, I got it. I will fix the unit tests. Actually, my code works but one thing I noticed that I broke a rule there. The **stat** takes as string and returns as string and what my stat returns as dictionary.

**Comment by joaodragao** [comment]
@Moonlight-Angel @TheSavior Sorry guys! 😄 I don't know how to use UnitTest MagicMock thing. I'm learning now. Will be back to you after I figure it out. Or perhaps someone can help me with this.

**Pull request closed without merging**
