### PR TITLE
Revert "[Feature] added keep pokemon for batch evolution"

### PR DESCRIPTION
**Pull request by douglascamata**
Reverts PokemonGoF/PokemonGo-Bot#2255

Caused bug, added excessive logs and complicated code in an already complicated functions. Needs to be broken down into many smaller methods.

### CODE REVIEW

**Comment by MFizz** [comment]
Can you say what bug it caused?

**Comment by Fantastik71** [comment]
For my part, your PR made my bot release all my T2-T3 pokemon without even changing anything in my conf.

RIP my charizards, dragonites ....

**Comment by douglascamata** [comment]
@MFizz ppl had lots of pokemon released that shouldn't.

**Comment by MFizz** [comment]
I'm sorry you lost your pokemon, I specifically asked to help me test before releasing such a crucial PR. Guess that didn't happen.

**Comment by k4n30** [comment]
@MFizz any chance of revisiting this?

**Pull request merged**
