### PR TITLE
Fix bot crash on telegram egghatch

### PR DESCRIPTION
**Pull request by Gobberwart**
Fixes a crash when telegram_handler tries to send an egg hatched notification.

### CODE REVIEW

**Comment by Gobberwart** [comment]
Don't merge this yet. There's still a problem with egg_hatch events. Working on it.

**Comment by solderzzc** [comment]
Sure...

**Comment by Gobberwart** [comment]
Should be ok to merge now @solderzzc

**Comment by solderzzc** [comment]
👍

**Pull request merged**
