### PR TITLE
Randomize spins for softban #2247

### PR DESCRIPTION
**Pull request by scalp42**

### CODE REVIEW

**Comment by Kassius509** [comment]
Thx @scalp42!

**Comment by maestroi** [comment]
but why ? :)
we can set it to 60

**Comment by pokecunt** [comment]
download

**Comment by Kassius509** [comment]
@maestroi When we do the EXACT same number of spins, every single time, it creates a distinct and easily recognizable pattern that Niantic can use to flag accounts as run by a bot.

**Comment by TheSavior** [comment]
:+1:

Seems like a low risk change.

**Pull request merged**
