### PR TITLE
Snipping improvements (PR #5247)

### PR DESCRIPTION
**Pull request by YvesHenri**
Non-social information (url) are now validated against expiration (exists). This also allows other crowd-based applications/sites to work this bot (https://github.com/YvesHenri/PokemonGo-Bot).
Teleporting to target log is now yellow.

### CODE REVIEW

**Comment by solderzzc** [comment]
👍  Thanks for the PR, let's merge.

**Comment by NovaDev94** [comment]
Hi @YvesHenri, I'm seeing `update_map_location` removed (https://github.com/PokemonGoF/PokemonGo-Bot/pull/5303/files#diff-13dfb7470ca1360a74ad4eabf7bb11a2L230).  

Do we have alternate ways to update the location on `PokemonGo-Map` (based on the bot position)?

**Comment by YvesHenri** [comment]
MoveToMapPokemon was first made exclusively to work with PokemonGo-Map. It is going to be deprecated and support multiple urls/sources. Since move_map_location is PokemonGo-Map related (and useless, unless you prove me wrong), it was removed.

**Comment by NovaDev94** [comment]
@YvesHenri Oh no worry. I made a PR and only saw your PR after that. So I thought maybe I had misunderstood so I wanted to clarify/confirm it first before making any unnecessary changes that may conflict with your ideas. Well done 👍 .

**Pull request merged**
