### PR TITLE
GNU License!

### PR DESCRIPTION
**Pull request by maestroi**
Short Description: 
Add license GNU 3 so every code based on this needs to be opensource.

Fixes:
- 
- 
- 

We should add license to the product

### CODE REVIEW

**Comment by ironbishop** [comment]
shouldnt this be a single PR? it's the same as #2309

**Comment by maestroi** [comment]
@ironbishop yes but it derpt on website i have no git on my work laptop

**Comment by pokecunt** [comment]
download

**Comment by DayBr3ak** [comment]
@pokecunt nice spam

**Comment by th3w4y** [comment]
if this is currently under MIT why do you to change it to GNU License!?

**Comment by maestroi** [comment]
@th3w4y there is non atm :)

**Comment by solderzzc** [comment]
Thanks all for the discussion

**Pull request closed without merging**
