### PR TITLE
Update web submodule to latest commit

### PR DESCRIPTION
**Pull request by Moony22**
Updated the web submodule to the latest commit, which includes fixes for candy, etc.

An earlier pull request was supposed to do this, but the commit was much earlier than the latest.

### CODE REVIEW

**Comment by solderzzc** [comment]
This version is not working on my side.
screen shot 2016-08-01 at 6 06 10 pm

**Comment by MZorzy** [comment]
@solderzzc after edited /web/config/userdata.js ( with multi bot) & set ngix root directory to /web
 it work for me as old master

**Comment by ubu13** [comment]
to web directory , 
$ cd web
$ git reset --hard origin/master
$ git pull origin master

Config your userdata.js again and re-run your bot.

**Comment by solderzzc** [comment]
oh, I just recall the userdata.js was changed. 
Thanks @MZorzy @ubu13

**Comment by solderzzc** [comment]
It's working well here, I guess we need a wiki update.

**Pull request merged**
