### PR TITLE
Make a universal switchyard for GPS assignment. Add config for altitude.

### LINKED ISSUE #2762: Use the latitude and longitude to get the altitude from Google
look is time to remove zero 'altitude' here&there and check position

exemple: step_walkwe.py line 41 set alt to zero ?
other

https://github.com/PokemonGoF/PokemonGo-Bot/search?utf8=%E2%9C%93&q=position
and set alt in config?

### PR DESCRIPTION
**Pull request by BoboFraggins**
Short Description: 

Pull all calls to the assignment of the GPS coordinates into a single object. For now this allows for assigning the initial altitude to use instead of always claiming exactly 'sea level'. Longer term this will allow for simulating decaying GPS accuracy (e.g. - +/- 50m when the bot launches and dropping down to +/- 10m as it is running). Those sort of variables would also be configured in the 'gps' section of the config file.

Assumptions:

- Nowhere can I find any reference to the *units* that altitude should be in. I assume meters.
- I made a 'sensors' folder for these types of objects in anticipation of other sensors like the accelerometer.

Closes #2762

### CODE REVIEW

**Comment by MZorzy** [comment]
on pokemongo_bot/cell_workers/follow_spiral.py line 93
'current_position': (point['lat'], point['lng'], 0),

**Comment by BoboFraggins** [comment]
@MZorzy Yep, sorry missed that one.

**Comment by TheSavior** [comment]
@BoboFraggins It looks like you have merge conflicts.

@douglascamata Can you review this please?

**Comment by BoboFraggins** [comment]
Conflicts resolved.

**Comment by TheSavior** [comment]
@BoboFraggins, thanks

@douglascamata what are your thoughts here?

**Comment by douglascamata** [comment]
@TheSavior thoughts tomorrow, sorry... too late.

**Comment by douglascamata** [comment]
@BoboFraggins I'm thinking about starting a `lib`, `api_wrapper` or `services` folder where we will put all the classes the wraps API logic, like `inventory.py` and other stuff. You mind trying to start this already? What are you thoughts about this structure proposal?

**Pull request closed without merging**
