### PR TITLE
Update pokemon.json new moveset

### PR DESCRIPTION
**Pull request by KingTheRipper**
## Short Description:

Modify a new moveset and fix errors like:
 `Unexpected moveset [Tackle, Psychic] for #121 Starmie` 

Is not a full fix, but working well at the moment

## Fixes/Resolves/Closes (please use correct syntax):
- Resolve most ERRORS caused from new niantic moveset.
-
-

[pokemon.json.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/432069/pokemon.json.zip)

### CODE REVIEW

**Comment by th3w4y** [comment]
@KingTheRipper could you rebase / squash your commit?

**Comment by Calcyfer** [comment]
I don't think you intend to merge dev to master? If so, the title is a bit misleading.

**Comment by k4n30** [comment]
Don't create PRs against master - If you want your file added change it in dev

**Comment by KingTheRipper** [comment]
I don't understand why is incorrect? i ask to commit in to Master from dev, what I have to do? dev to master?

Please tell me (i use bitbucket and git have some difference :) )

**Comment by Calcyfer** [comment]
@KingTheRipper You need to make a fork (top right), then edit the file as needed, commit it to your fork, and open a pull request from your fork to the dev branch in this repo.

**Comment by th3w4y** [comment]
@KingTheRipper 

Usually you raise a pull request when you also authored something.

When you opened the pull request there were also some guidelines in the description, one of them things mentioned there was: 
1. We do not accept changes to `master`. Please make sure your pull request is aimed at `dev`.

Pulling from dev into master is done by the project maintainer when they feel that it is appropriate.

**Comment by th3w4y** [comment]
@KingTheRipper in case you wanted to do a PR from your fork branch master to he this master then I took a look at the differences and there are few issues:

1) json files don't support comments not in the why you made them in https://github.com/KingTheRipper/PokemonGo-Bot/blob/a6323cf5a14a42cbfc1847b8c366ac08212f24da/config/release_config_example.json
2) there is a valid reason why encrypt.so is not added to the repo

**Comment by KingTheRipper** [comment]
Thanks to all, update correctly #4666

**Pull request closed without merging**
